### ISSUE TITLE
Create the Vocabulary brand guidelines

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#10]
**Description**
We might need our styleguide to also present the brand identity of Creative Commons and Vocabulary. This will help us distinguish the functions of the styleguide from the storybook.

**References:**
- [Firefox brand](https://mozilla.design/firefox)
- [Mozilla brand](https://mozilla.design/mozilla/)

**Comment by kgodey** [comment]
We no longer use the styleguide.
