### ISSUE TITLE
CI Actions not getting triggered

### ISSUE THREAD

**Issue by MuluhGodson** [cc-archive/vocabulary-legacy#1000]
## Description

CI actions are not getting triggered as they are supposed to.
The images below are screenshots of CI actions run on two PRs opened today. On one of the PR's all the actions are displayed to run as expected, while on the other the actions are not triggered.

## Reproduction

1. Do a PR
2. See error (CI actions `build` , `lint` and `test` won't be triggered.

## Expectation
CI actions should be triggered

### **Actions are triggered**
![vocab-2](https://user-images.githubusercontent.com/40151808/137326690-05273bf0-eca3-45c7-b261-17e5530cb122.PNG)
---
### **Actions are not triggered**
![vocab-1](https://user-images.githubusercontent.com/40151808/137326677-465cd10e-1233-4a4d-a0f3-b9b8a5e958a7.PNG)

## Additional context
I believe the failures to be caused by what triggers the actions. For example: For the Build workflow, what triggers it is:
```bash
name: Build

on: 
  push:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main
```

I think above the logic is, when code is pushed to either of `packages`, `scripts`, or `src` AND on branch `main`, then this triggers this workflow to run. same with `pull_request`.

The reason the action was triggered in the screenshot above is due to the fact that the PR contained changes in the `scripts` directory and the PR was opened on `main` while in the screenshot where the issues are not triggered, the PR was opened because of changes in the `README.md` which is not in the context of what those triggers are looking out for. 

I did a little test of this theory on my forked branch and confirmed.

## Resolution

- [x] I would be interested in resolving this bug.

_Originally posted by @MuluhGodson in https://github.com/creativecommons/vocabulary/discussions/999_

**Comment by MuluhGodson** [comment]
@brylie I will be happy to submit a PR on this and get the CI pipeline up and running.

**Comment by MuluhGodson** [comment]
On the plus side, I created a new branch on my fork and change the `ci-build` to trigger when a PR is made on the branch without the other conditions and then initiated a PR. The action was triggered as I expected.

![image](https://user-images.githubusercontent.com/40151808/137364354-6ba891ca-0212-41d1-b78c-786e2895d71c.png)

**Comment by brylie** [comment]
@MuluhGodson, great research! I've assigned you to the task.

**Comment by MuluhGodson** [comment]
@brylie Thank you.
However, what I am proposing is to remove as many constraints as possible from what triggers these actions, 
and then slowly reintroduce them with time. 
An example, in the former repository structure, all three (`fonts`, `vocabulary` and `vue`) vocabulary were in their distinct folders in `packages` and the action that triggered it was any change made in the `packages/**` directory.
Today the packages folder just has meta information in json files for the three packages and there's hardly any PR's being made with changes in that folder so I assume that won't trigger an action. 

Just a hypothesis but I believe iit could be one of the reasons

**Comment by brylie** [comment]
Agreed on taking an incremental/experimental approach. Your help has been really valuable so far in stabilizing our CI, tests, and build process after the considerable upheaval.

**Comment by MuluhGodson** [comment]
Thank you. It's a pleasure for me and I am learning a lot as well.
