### ISSUE TITLE
Disable Netlify builds on pull requests

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#1002]
Netlify is currently running several jobs on each pull request submitted to this project. The Netlify jobs create a lot of noise and some confusion in our CI/review process.

## Task

- [ ] disable automatic Netlify builds on pull requests

**Comment by Akpjunior94** [comment]
@brylie  I will take up this issue. Thanks

**Comment by brylie** [comment]
@Akpjunior94, thanks! I've assigned you to the issue.

**Comment by Akpjunior94** [comment]
Thanks @brylie

**Comment by Akpjunior94** [comment]
@brylie Based on my research I realized that the netlify workflow is an App integration which means it can be disabled on the repo settings with the right permission. 

I raised a Dummy PR and I noticed that the netlify deploy is canceled 
![image](https://user-images.githubusercontent.com/56775903/137584236-8ad411ae-d0a5-4acc-b8c4-b945560444d7.png)

**Comment by dhruvkb** [comment]
This issue should've been staff-only. I had the Netlify GUI access so I've disabled preview deployments for PRs from the Netlify dashboard.

**Comment by brylie** [comment]
@dhruvkb, would you please grant me (brylie@creativecommons.org) access to the Netlify dashboard for CC organization repositories?

**Comment by dhruvkb** [comment]
@TimidRobot and @annatuma have the "Owner" permissions to modify team members. I'm a "Collaborator" to I'm only allowed to remove myself.

**Comment by Akpjunior94** [comment]
> This issue should've been staff-only. I had the Netlify GUI access so I've disabled preview deployments for PRs from the Netlify dashboard.

Okay @dhruvkb  thanks for the update
