### ISSUE TITLE
Error with build scripts

### ISSUE THREAD

**Issue by MuluhGodson** [cc-archive/vocabulary-legacy#1006]
## Description
This PR https://github.com/creativecommons/vocabulary/pull/996 reorganized the scripts files but the changes weren't updated in the `package.json` file.

The new `package.json` scripts should be:

```bash
 "scripts": {
    "serve": "start-storybook -p 6006 --ci -s ./src/assets",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint",
    "build:fonts": "bash ./scripts/build/fonts.sh",
    "build:storybook": "build-storybook -o ./docs -s ./src/assets",
    "build:vocabulary": "bash ./scripts/build/vocabulary.sh",
    "build:vue-vocabulary": "bash ./scripts/build/vue_vocabulary.sh",
    "test:vue-vocabulary": "vue-cli-service test:unit"
  },
```

## Reproduction

1. Run any build command, e.g `npm run build:fonts`
4. See error.

## Expectation
scripts should build correctly

## Screenshots
![image](https://user-images.githubusercontent.com/40151808/137531812-9e132bfa-22da-4e77-aca5-9ab411a31691.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by MuluhGodson** [comment]
@brylie Hello
I have already updated the changes and will be happy to open a PR if assigned.

**Comment by brylie** [comment]
Thanks. I've assigned you :smile:
