### ISSUE TITLE
Improve Vocabulary performance

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#1013]
Vocabulary currently has some performance issues, related to:
- File size of CSS files
- Runtime loading cascade (importing Vocabulary from the CDN then loads
  additional stylesheets and font files in sequence, instead of in parallel).
  We need to eliminate this waterfall.

Performance can also be further improved via documentation, and sharing best
practices for implementing vocabulary with consumers:
- Guidelines and suggestions for using [purgecss][purgecss] with Vocabulary
- Instructions on how/and what to prefetch or preload (with copy-pastable meta
  tags) (see: [Preload, prefetch and other link tags | CSS-Tricks][csstricks])
- Create tooling so that these performance improvements can be *maintained*
  over time. Some ideas:
  - Filesize monitoring via GitHub actions: [ampproject/filesize][filesize]
  - Add linting rules for Sass files [sds/scss-lint][scsslint]

These changes will be
quantifiable by measuring changes in page size (measured in kilobytes), and
reduced load times on the Google-defined metrics "[core web
vitals][corewebvitals]": Largest Contentful Paint (LCP), First Input Delay
(FID), and Cumulative Layout Shift (CLS).

[corewebvitals]: https://web.dev/vitals/
[vocabulary]: https://github.com/creativecommons/vocabulary/
[purgecss]: https://github.com/FullHuman/purgecss
[csstricks]: https://css-tricks.com/preload-prefetch-and-other-link-tags/
[filesize]: https://github.com/ampproject/filesize
[scsslint]: https://github.com/sds/scss-lint

**Comment by mayank2021** [comment]
@brylie I would like to fix this issue, can I?

**Comment by mayank2021** [comment]
@brylie I would like to work on this issue, can I?

**Comment by brylie** [comment]
@mayank2021, we are undertaking a large reorganization for the Vocabulary project so it might not be the best time to look into performance currently.

**Comment by mayank2021** [comment]
@brylie Sure, let me know please if I can help in reorganization for the vocabulary project.

**Comment by Anju-Narnolia** [comment]
hello, Is this issue open ??

**Comment by azyz123456** [comment]
Hi, I would like to work on this issue.

**Comment by possumbilities** [comment]
This project is moving towards being archived, and this item is no longer on the roadmap. Closing
