### ISSUE TITLE
Add Emoji to Vocabulary

### ISSUE THREAD

**Issue by kgodey** [cc-archive/vocabulary-legacy#102]
We need to add an Emoji component to Vocabulary. It can be based on the same Emoji component as the previous version of Vocabulary.

**Comment by brenoferreira** [comment]
I was looking at https://github.com/creativecommons/vue-vocabulary/issues/9

Are we going to be using Emoji so extensively to require use of Twemoji? What do you think about we using native emojis for now and if we realise later that we're having issues that Twemoji might fix, we can adopt it later

**Comment by dhruvkb** [comment]
@kgodey finally what are we doing about Emoji? Do we parse them and render SVGs for consistency or do we allow the OS to handle it without our interference?

**Comment by kgodey** [comment]
I don't think we'll be using emojis very much so I think we should close this and reopen later if we need it.
