### ISSUE TITLE
Remove `docs/` folder from revision contriol

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#1039]
The `docs/` folder contains auto-generated output from the command `npm run build:storybook`. We host the Storybook output on GitHub pages.

However, we should try to minimize the amount of auto-generated code we keep under revision control since committing that code to Git isn't meaningful and creates repository bloat.

Ideally, we would

- keep automated output in a separate Git branch, such as `docs`
- delete and re-create the `docs` branch each time the documentation is published, so we don't have a commit history for all files therein

## Possible solution

Netlify will automatically build and publish the contents of a specific folder allowing us to keep the build output out of revision control.

**Comment by clasick** [comment]
@brylie Could this potentially be resolved by adding the `docs/` folder to the `.gitignore` file? Or is there some limitation in that end for Storybooks/Netlify, etc.?

**Comment by brylie** [comment]
Yes, we will want to at least add `docs/` to `.gitignore`. Netlify will build and host the documentation without the need to commit the static output to our revision history.
