### ISSUE TITLE
Split Vocabulary packages into separate projects

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#1049]
## Problem

The structure of the Vocabulary project and lack of developer continuity has led to maintenance issues blocking the release of `styles` and `fonts` packages. We need to publish new versions of `styles` and `fonts` as the creativecommons.org redesign roadmap progresses.

## Description

The Vocabulary project includes transient dependencies preventing us from building and releasing the code, such as those related to `node-sass` and `storybook`. We have tried to reconcile the dependency issues for the past few months but are reaching the limit of our available resources to continue the struggle.

An alternative approach would be to revert the packages into separate, simplified projects containing only dependencies essential to their function. To the extent possible, we should separate dependencies for interactive documentation from core package dependencies to reduce complexity and adverse interactions. This restructuring will improve the immediate maintainability of the projects while leaving open the issue of providing a holistic documentation/development environment.

## Alternatives

Keep the monorepo structure and continue struggling to restore the project to a healthy state. However, the above restructuring would not preclude any further maintenance on this Vocabulary project but would provide some immediate respite and allow us to move forward with the creativecommons.org redesign.

## Plan

- [x] create new repositories with the contents of this `vocabulary` project
    - [x] `vocabulary-styles`
    - [x] `vocabulary-fonts`
    - [x] `vocabulary-components`
    - [x] `cc-assets`
- [x] [filter the repository contents](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html) to leave only relevant files
    - scss
    - index js (used by build tool)
    - relevant assets (namely the font files)
    - LICENSE.md, CONTRIBUTING.md, CODE_OF_CONDUCT.md, cc-metadata.yml
- [x] add new project metadata necessary for the build/publication process
- [x] open issues in downstream projects that currently import Vocabulary so we can change the dependency
- [x] publish the new packages on NPM
    - [x] `@creativecommons/cc-assets` 
    - [x] `@creativecommons/vocabulary-components` 
    - [x] `@creativecommons/vocabulary-fonts`
    - [x] `@creativecommons/vocabulary-styles`
- [ ] change downstream dependencies in a prioritized manner 

## Additional context

We hope to launch the new creativecommons.org redesign this month.

**Comment by brylie** [comment]
From what I can tell, the Vocabulary Vue components are not used in any downstream project, as they have not been packaged or published. Specifically, the Chooser project contains components in a `vocabulary/` subdirectory. So, we might also consider deprecating the Vocabulary Vue components

**Comment by MuluhGodson** [comment]
## List of CC Sites that import Vocabulary Styles/Fonts:
- `summit.creativecommons.org`: uses 3 versions of Vocabulary fonts
![image](https://user-images.githubusercontent.com/40151808/148434853-cd31224e-1a85-403e-8680-9d36120b79fb.png)

- `opensource.creativecommons.org`: uses fonts and Vocabulary JS (is this for the vue components??)
![image](https://user-images.githubusercontent.com/40151808/148435796-91e7e238-7fee-451d-b238-98f372b9232d.png)

- `chooser-beta.creativecommons.org`: uses fonts
![image](https://user-images.githubusercontent.com/40151808/148436451-672edbcb-18d1-4790-a052-a62ecc4ee417.png)

**Comment by brylie** [comment]
One thing I am considering is whether to publish the components CSS with the `vocabulary-styles` or `vocabulary-components` project. What are your thoughts about where the SASS files in the components tree should be published?

https://github.com/creativecommons/vocabulary/tree/main/src/components

**Comment by brylie** [comment]
Closing this since we have initial releases for all Vocabulary sub-projects and the CC Assets.
