### ISSUE TITLE
Link for the github repo in README is wrong

### ISSUE THREAD

**Issue by adrijshikhar** [cc-archive/vocabulary-legacy#106]
Can someone provide me the right repo link so that I can fix it?

**Comment by dhruvkb** [comment]
@adrijshikhar could you be a little more specific as to which link is wrong?

**Comment by Blackcipher101** [comment]
@dhruvkb this one
![ ](https://media.giphy.com/media/kfLJSIDykkX7e5CuXM/giphy.gif)
