### ISSUE TITLE
Add Locale element

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#107]
Add the **Locale** element based on the Design Library definition.

**Comment by dhruvkb** [comment]
@panchovm the Locale element is essentially just a select field right? That is already been styled with Vocabulary. The rest of the component has no discernable CSS properties. Can we close?

**Comment by fcoveram** [comment]
Select field but I will add an icon inside. Maybe it should be a new element, something called **select icon** or similar.

**Comment by fcoveram** [comment]
The component is updated. The sentence has changed and there is an icon.

**Comment by dhruvkb** [comment]
Select fields with icon should also a variant of the select element itself. `Locale` as en element seems to be like a component in Vue-Vocabulary with no counterpart in Vocabulary.

**Comment by kgodey** [comment]
I'm fine with select fields with icons being a variation of the select element rather than a separate element. @brenoferreira thoughts?

**Comment by brenoferreira** [comment]
I'm not sure exactly how Bulma `select` component handles icons in it. When someone decides to implement this feature, they can find out. If it's out of the box, then we can just close this. But I'd keep this open until then

**Comment by brenoferreira** [comment]
Bulma does support selects with icons, so we can use that https://bulma.io/documentation/form/select/#with-icons
