### ISSUE TITLE
The image links of creative commons,vocabulary are broken

### ISSUE THREAD

**Issue by Blackcipher101** [cc-archive/vocabulary-legacy#109]
**Description**
The image links are broken

**Screenshots**
![Screenshot from 2020-02-08 18-33-03](https://user-images.githubusercontent.com/33775493/74085668-83399300-4aa1-11ea-87d3-282c860808ad.png)

**Want to take up?**
Yes

**Comment by dhruvkb** [comment]
This has been fixed now.
