### ISSUE TITLE
Add the Progress layout

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#112]
Add the Progress layout and its components: the white boxes to indicate the different states. The section is in Design Library.

**Comment by mercyikpe** [comment]
Add the Progress layout  (#112 & #165)

https://github.com/creativecommons/vue-vocabulary/issues/165
https://github.com/creativecommons/vocabulary/issues/112

I'm working on this issue. 
Thank you.

**Comment by mercyikpe** [comment]
@dhruvkb 

![image](https://user-images.githubusercontent.com/29842348/76166421-b897d600-615e-11ea-9701-e63c72280230.png)
I don't understand what is causing this test to fail.

**Comment by jahnvigupta** [comment]
@panchovm I want to take this issue. Can you elaborate what has to be done.

**Comment by dhruvkb** [comment]
@jahnvigupta you can refer to @mercyikpe's PR #164 and build up on that. It's still pending review so that would not be too reliable.

**Comment by jahnvigupta** [comment]
@dhruvkb Can you tell what content has to be added in vertical navigation bar. Looking at the screenshot in draft pr suggests that there is no specific content.

**Comment by possumbilities** [comment]
This project is moving towards being archived, and this item is no longer on the roadmap. Closing
