### ISSUE TITLE
Update documentation deployment

### ISSUE THREAD

**Issue by brenoferreira** [cc-archive/vocabulary-legacy#116]
Currently, the automated build for all PRs are not passing 100% because of the Netlify automated documentation deployment, which was available in the old Vocabulary codebase, but is not currently available in this new codebase. 

We should, initially, build and deploy the Storybook to Netlify and automate its deployment during the build phase of all PRs

**Comment by ravisaxena23** [comment]
How Can I help in this. where should i start

**Comment by kgodey** [comment]
This should be done now, @dhruvkb please confirm.

**Comment by dhruvkb** [comment]
Yep this is actually ready now.
