### ISSUE TITLE
Document the grid definition in Design Library

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#118]
Create a page for the grid and its uses. The document should consider responsiveness and full-screen cases like CC Search.

**Comment by Dhruvi16** [comment]
I could take this up.
Thank you.

**Comment by kgodey** [comment]
I'll leave this up to @panchovm and @annatuma to decide if this is suitable for community work.

**Comment by dhruvkb** [comment]
@Dhruvi16 I've assigned to you a different issue which isn't blocked by time-consuming design and planning work.

**Comment by Dhruvi16** [comment]
Yeah! Thanks for assigning me an available issue. Apologies for the multiple requests.

**Comment by fcoveram** [comment]
The grid documentation [is available](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=3990%3A1666&viewport=119%2C45%2C0.28201159834861755) in the Design Library.
