### ISSUE TITLE
Update usage and contribution guidelines

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#120]
Once Vocabulary has been redeveloped, the usage and contribution guidelines will be out of date and will need major rewritings to be in sync with the new codebase. The goal is to update these guidelines and instruction documents.

**Comment by dhruvkb** [comment]
References creativecommons/vue-vocabulary#167.

**Comment by ravisaxena23** [comment]
is this issue over?

**Comment by dhruvkb** [comment]
Yeah @ravisaxena23, the PR #128 actually addresses the contribution guidelines. The usage guidelines can only be updated once the project is ready so there's nothing to do on this at the moment.

**Comment by ravisaxena23** [comment]
okay
