### ISSUE TITLE
Set up continuous deployment

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#121]
Currently Vocabulary is being manually pushed to `npm`. This can be automated with CircleCI so that it can automatically build and publish the package once all tests pass successfully.

Best way to do this is to use some mechanism on Github Actions to detect when a new *tag* is pushed and trigger the run the [deploy script](https://github.com/creativecommons/vocabulary/blob/master/deploy.sh). It can't be the release name. It has to be able to detect a new tag, because the tag name matches the version on package.json.

**Comment by dhruvkb** [comment]
References creativecommons/vue-vocabulary#5.

**Comment by kgodey** [comment]
@dhruvkb and @brenoferreira will flesh out this issue and mark as help wanted.

**Comment by dhruvkb** [comment]
GitHub actions has the ability to run jobs on [releases](https://help.github.com/en/actions/reference/events-that-trigger-workflows#release-event-release):
```
on:
  release:
    types: [published]
```

With GitHub Actions having replaced CircleCI, it's only a matter of adding another workflow to `.github/workflows/`.

**Comment by Dhruvi16** [comment]
I will be happy to help here.

**Comment by dhruvkb** [comment]
@Dhruvi16 I can put your name down for this, but you need to get the other PRs to completion before attempting this.

**Comment by Dhruvi16** [comment]
Makes sense. I will complete my other pending PR first. Up till then, others can take-up this issue so there is no delay here.

**Comment by SaurabhAgarwala** [comment]
I am interested to work on this

**Comment by hitesh1157** [comment]
@dhruvkb I would like to work on this issue as per my previous experience with #261 .
