### ISSUE TITLE
Update the Table styles

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#126]
Update the Table's styles following the design in Design Library. The styles applied are only for cells.

**Comment by ravisaxena23** [comment]
which table want to be updated please direct me I'm new

**Comment by dhruvkb** [comment]
@ravisaxena23 this actually refers to the new designs for the `Table` and `TableCell` component that @panchovm has created. Let's take the conversation of finding a good issue to work on to Slack.

**Comment by kgodey** [comment]
@dhruvkb will be working on this. @dhruvkb, please use Bulma's styles as much as possible while implementing this.
