### ISSUE TITLE
Update the style of Tab component 

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#127]
Update the style of Tab component based on the element available on [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=933%3A0&viewport=25%2C233%2C0.47611111402511597).

**Comment by kushaggarwal** [comment]
Hello,
I am Kush Aggarwal 
I would also like to work towards the development of components for vocabulary library  and contribute so, can you please help as if how can I proceed for the same
Thanks

**Comment by kushaggarwal** [comment]
Hello @dhruvkb please find the attached screenshot for the above element and guide if its fine so, that I can submit for the pull request of the same 
Thank You

**Comment by kushaggarwal** [comment]
![Screenshot 2020-03-04 at 2 51 15 PM](https://user-images.githubusercontent.com/44523552/75864485-17d8ac00-5e28-11ea-865b-05db9049e80d.png)

**Comment by kushaggarwal** [comment]
@dhruvkb please see for the above pull request and advise if something needs to be rectified.
And also as there are many other components in figma design library which are yet to be implemented in vocabulary so, can I take up another component and start working for the same please help
Thank you

**Comment by dhruvkb** [comment]
Breno incorporated the tab component with #178.
