### ISSUE TITLE
Update INSTRUCTIONS.md for vocabulary

### ISSUE THREAD

**Issue by sharmaadityaHQ** [cc-archive/vocabulary-legacy#128]
**Description**  

The `INSTRUCTIONS.md` file contains instructions which are not relevant to `vocabulary` like `$ git clone https://github.com/creativecommmons/vue-vocabulary.git` and `$ cd vue-vocabulary/`. Also the scripts to start the servers - `$ npm run serve:website` and `$ npm run serve:styleguide` are not present in the `package.json` and need to be updated.

**Want to take up?**

Yes

**Comment by dhruvkb** [comment]
This is actually part of #120.
