### ISSUE TITLE
Add webpack-dev-server as a development dependency

### ISSUE THREAD

**Issue by sharmaadityaHQ** [cc-archive/vocabulary-legacy#129]
**Description**

The `webpack-dev-server` provides us with a simple web server and the ability to use live reloading.  If we now change any of the source files and save them, the web server will automatically reload after the code has been compiled.

**Problems solved**

Currently we do not have any development tool for `vocabulary` and would have to refresh our browser every time we make changes to the code.

**Want to take up?**

Yes

**Comment by dhruvkb** [comment]
@sharmaaditya570191 this is actually incorrect. Vocabulary when run with Storybook using the two commands
```
$ npm run watch
```
and 
```
$ npm run storybook
```
updates automatically without the need to refresh the browser. Let me know if this does not fix the issue for you.

**Comment by sharmaadityaHQ** [comment]
I am able to run `Storybook` with the above commands but the main website is not running.

**Comment by dhruvkb** [comment]
If by main website you mean the landing page, that's no longer present in the library. It was removed by a commit and will be re-added later on. Since that's a different topic we will not discuss more on that here.

**Comment by dhruvkb** [comment]
The lack of autoreload was indeed present in the Storybook. Sorry @sharmaaditya570191 for dismissing the issue without a thorough check. It's now been addressed.
