### ISSUE TITLE
reducing build complexity.

### ISSUE THREAD

**Issue by ravisaxena23** [cc-archive/vocabulary-legacy#138]
**Description**
scripts build dist folder. when the build script is run it create SCSS files as well as CSS files. we only need css files during build.
Thus it increase the weight of build and increases space complexity and inconsisteny.

**Reproduction**
to check run current vocabulary repo.
**Expected behavior**
We Dont need scss in build as our everything is present in vocabulary.css

**Screenshots**
![Screenshot from 2020-02-24 16-15-59](https://user-images.githubusercontent.com/44205807/75147045-6dbf9c80-5722-11ea-905c-08a7af4d96ef.png)
![Screenshot from 2020-02-24 16-09-20](https://user-images.githubusercontent.com/44205807/75147062-7617d780-5722-11ea-8735-307481453472.png)

**Want to take up?**
Yes

**Comment by dhruvkb** [comment]
This issue is not valid as the SCSS files are actually needed by Vue Vocabulary in the components. Just shipping the CSS files is not enough.

**Comment by ravisaxena23** [comment]
thanks for review
