### ISSUE TITLE
Update the Header component 

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#149]
We need to update the Header component based on the current version of Design Library in Figma. The new version updates the black section where all CC products are shown in a new layout. 

The interactions should be applied as follow: 
1. The product name should show an underline text style for the hover state
2. The donate button changes its background-color to GoldBrighter (found it in the interaction color page).

**Comment by kushaggarwal** [comment]
If this issue is still open I would like to go for the same @hugosolar @dhruvkb @kgodey 
Thank you

**Comment by dhruvkb** [comment]
Chidi has already worked on building this component. @chidexebere could you point to this issue in your PR?

**Comment by kushaggarwal** [comment]
Okay no problem @dhruvkb can you please guide as if can I work on the implementation of other components of figma library 
Thank you

**Comment by JonillaTallawan** [comment]
Is it okay for me to work on this one?

**Comment by dhruvkb** [comment]
@JonillaTallawan it's already done.
