### ISSUE TITLE
CC Open Source Homepage Wireframes

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#151]
_This task is open for community contribution during the application periods for GSoC and Outreachy, and will remain open until the application deadline has passed. Multiple people may complete this task._

**Description**
An upcoming internship project at CC is to integrate Vocabulary into CC Open Source and CC Global Network sites: https://opensource.creativecommons.org/internships/project-ideas/all/#vocabulary-integration

We'd like to take the opportunity prior to this integration to redesign the CC Open Source website. Note, there will be **no content changes** but the presentation of the content can be redesigned.

Outreachy and GSoC applicants can submit a wireframe for a redesigned homepage for CC Open Source, using a tool of your choice, such as Moqups, Balsamiq, or other similar tool. Attach a public link to the wireframes as a comment, or upload a file of the wireframes. Bonus points if you decide to create wireframes for other pages on CC Open Source that you think would benefit from a redesign.

Please note this ties into an overall redesign of CC Open Source:
https://github.com/creativecommons/creativecommons.github.io-source/issues/189

**Comment by kushaggarwal** [comment]
Hello,
As in the issue mentioned above we have to redesign the look and feel of the CC Open Source and CC Global Network Site without any content change so, does the components of the site have to be aligned as per the vocabulary components 
Can you please help

**Comment by annatuma** [comment]
@kushaggarwal the redesigns during the internship will require the use of Vocabulary.

This ticket is for wireframes, and only for CC Open Source. As mentioned you could use e.g. Moqups or Balsamiq for this. The first step in this redesign, which does not include content changes, is designing the layout/flow of the CC Open Source homepage.

**Comment by pranshuls12** [comment]
Hi, Can I help  with this issue ?

**Comment by kgodey** [comment]
Go ahead @pranshuls12, post your wireframes here. This issue is open to multiple contributors, which means others can also do the same.

**Comment by kushaggarwal** [comment]
Thank you for your help will start working for the  same

**Comment by GeekBoySupreme** [comment]
This looks really interesting. Getting on this one.
We cannot change the contents but can change the visual hierarchy of the pages. 
Is that right?

**Comment by kgodey** [comment]
@GeekBoySupreme Yes. You can update the presentation of the content itself, but just not the actual content.

**Comment by kushaggarwal** [comment]
Hello @annatuma @kgodey as per the development of new wireframes for CC opensource do we have have to represent the updated design for all the pages at once or we can share some of the developed part with you prior to designing of all pages for feedback and suggestions
Can you please help
Thank you

**Comment by Romicodes** [comment]
@kgodey  @dhruvkb  Any chance I could pick this up for Outreachy May 2020?

**Comment by kgodey** [comment]
@Romicodes go ahead, this issue is open to multiple contributors.

@kushaggarwal sharing one page at a time is fine.

**Comment by kushaggarwal** [comment]
Okay @kgodey will do so

**Comment by Bob160** [comment]
Hello @annatuma and @kgodey,

As this issue is open to multiple contributors, I would like to take part in it.

Can I go ahead?

Thanks

**Comment by dhruvkb** [comment]
@Bob160 sure, please and thank you.
@kgodey I do think there should be a way for everybody to get involved with this without conflicting with each other.

**Comment by snunnington** [comment]
I would like to take a look at this too if possible?

**Comment by ernestmusong** [comment]
I am interested in this task, can I go ahead?

**Comment by kushaggarwal** [comment]
Hello @kgodey @annatuma 
Please find the below link for the wireframes of the CC Open Source and advise for any changes and improvements in the same. It currently consist of three pages of the current site
Link - https://www.figma.com/file/gN3puDIwMJXER8jxHEpuKR/CC-Open-Source?node-id=0%3A1
Thank you

**Comment by terrifricker** [comment]
Here are some of my first ideas.  I really like the icons, so I would increase their size as well as making them color. (I used the 2019 Style Guide)  Above the navigation bar, add a photograph that uses many of the colors.  Scrolling down the page would hide the image, but the navigation bar should stay at the top.  Get rid of the links under the icons and just link to whichever page was most commonly chosen.  When landing on that page, have the other option or options clearly visible.  The entire icon, plus heading, plus description should be the link - super, easy to click.  The bounce rate may in part have to do with clicking the icon and nothing happening.  After reading, CC Open Source Redesign #189, I see that increasing traffic to contributing code and current projects is desired.  They should be the first two icons.  In this moqup, I just colored the icons, but did not put them in any particular order.

https://app.moqups.com/RQ6fQZsfhm/edit/page/a50add8af

![Screen Shot 2020-03-07 at 7 27 15 AM](https://user-images.githubusercontent.com/51532684/76146122-264fdf00-6045-11ea-84f5-763f1c9504af.png)

**Comment by terrifricker** [comment]
Contribution Page - Based on the Open Source page with same navigation bar, same or different image using the same colors.  Then three or four obvious choices with large colorful buttons.

https://app.moqups.com/RQ6fQZsfhm/edit/page/ae2e7c544

![Screen Shot 2020-03-07 at 7 30 14 AM](https://user-images.githubusercontent.com/51532684/76146171-80e93b00-6045-11ea-818a-d5c836ce6b0d.png) ![Screen Shot 2020-03-07 at 7 33 12 AM](https://user-images.githubusercontent.com/51532684/76146229-f05f2a80-6045-11ea-96bd-119511b13323.png)

**Comment by terrifricker** [comment]
If traffic to current projects is important, it should have its own icon on the front page.

![Screen Shot 2020-03-07 at 7 48 04 AM](https://user-images.githubusercontent.com/51532684/76146495-0372fa00-6048-11ea-89ef-bb92aba5ec36.png) ![Screen Shot 2020-03-07 at 8 42 43 PM](https://user-images.githubusercontent.com/51532684/76156806-76b25580-60b4-11ea-8bc8-fa14c1ab99c8.png)

**Comment by ernestmusong** [comment]
I think a top fixed header. a side scrollable navigation bar will be pretty good.
https://www.figma.com/file/rJMgwmq0SMHsX2SKh2vsR6/Updated-homepage-for-CC-Open-Source?node-id=0%3A1
![image](https://user-images.githubusercontent.com/61872891/76151529-ca984c80-606a-11ea-8481-0b2b33c191ed.png)

**Comment by terrifricker** [comment]
@kushaggarwal  I like the look of yours.

**Comment by dhruvkb** [comment]
I'm no designer but @kushaggarwal you seem to be on the right track with regards to the use of Vocabulary rather than designing custom UI components. I would recommend all contributors to please go through the [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library) as that contains a lot of helpful guidelines to keep in mind while designing a new website.

**Comment by jahnvigupta** [comment]
Hi everyone, I would like to know why do you want to change the design? What are the features you are looking for in the design?

**Comment by terrifricker** [comment]
@dhruvkb Thank you for the link to the Design Library.  I had only found the 2019 Style Guide pdf.

**Comment by dhruvkb** [comment]
@jahnvigupta a redesign was already in order given that we had to integrate Vocabulary with the site. We thought it might be a good opportunity _to identify, and resolve,_ any problems posed by the current design.

**Comment by kushaggarwal** [comment]
Thank you very much @dhruvkb for your valuable feedback. Please guide for any suggestions and improvements for the same if you find any will be happy to work on them
Thank you

**Comment by Bob160** [comment]
Hello @dhruvkb and @kgodey and @hugosolar kindly find below the link to my wireframe for the CC Open Source: https://www.figma.com/proto/4t74EuJixiRICqub7fo3JV/CC-wireframe-Colors?node-id=14%3A68&scaling=min-zoom

**Comment by hugosolar** [comment]
Hey @Bob160 I got a 404 with the given URL

**Comment by Bob160** [comment]
Ooops, my sincere apologies @hugosolar @annatuma @kgodey @dhruvkb @panchovm 

Please find attached the link to my draft of the wireframe. It includes 2 pages: Homepage and Blog.

https://www.figma.com/file/4t74EuJixiRICqub7fo3JV/CC-wireframe-Colors

I'm open to suggestions and improvements.

Thanks

**Comment by jahnvigupta** [comment]
Please have a look at my design and I would love to hear your feedback.

https://www.figma.com/file/86FD6wRY3YEp5HPentZqU5/Untitled?node-id=0%3A1

**Comment by ernestmusong** [comment]
Hello @dhruvkb , @kgodey and @hugosolar I thank you all for your guide. Based on @Dhruvi16 reference to the Design Library I was able to come out with this. Please check the link below to see.
https://www.figma.com/file/BEIHKlkeNAnFhl7mNagKuQ/Untitled?node-id=0%3A1

![image](https://user-images.githubusercontent.com/61872891/76491463-f741c080-63ea-11ea-9e2d-902fbceea706.png)

**Comment by dhruvkb** [comment]
I've assigned @panchovm as he's the most qualified person for feedback on designs.

**Comment by jahnvigupta** [comment]
> Please have a look at my design and I would love to hear your feedback.
> 
> https://www.figma.com/file/86FD6wRY3YEp5HPentZqU5/Untitled?node-id=0%3A1

 @panchovm Please have a look at my design and tell if I am going in the right direction.

**Comment by Bob160** [comment]
Ooops, my sincere apologies @hugosolar @annatuma @kgodey @dhruvkb @panchovm

Please find attached the link to my draft of the wireframe. It includes 2 pages: Homepage and Blog.

https://www.figma.com/file/4t74EuJixiRICqub7fo3JV/CC-wireframe-Colors

I'm open to suggestions and improvements.

Thanks

**Comment by kushaggarwal** [comment]
Hello @panchovm please have a look at my design too and provide a feedback for the same as per what changes or improvements can be done for further enhancement 
Thank you

**Comment by ernestmusong** [comment]
Hello @panchovm please also have a look at mine by visiting the link below and throw some feedback.
https://www.figma.com/file/BEIHKlkeNAnFhl7mNagKuQ/Untitled?node-id=0%3A1

![image](https://user-images.githubusercontent.com/61872891/76526213-6db1e300-642a-11ea-81e2-095338f9e6a9.png)

**Comment by annatuma** [comment]
Thanks everyone for the many contributions over the past several days.

Some initial feedback:

@kushaggarwal the direction of your wireframes is excellent, although I will say they are closer to being full-fledged mockups. I appreciate your use of CC's brand colors. For Desktop 3, are you proposing a potential alternative to the top of the page design shown in Desktop 1? Not necessary, but I do recommend naming each asset by page, so e.g. Desktop - 4 would be "Desktop - Blog", etc. Either way, we look forward to reviewing your application when the time comes.

@terrifricker I appreciate how thoughtful you are being about the navigation flow for users. It definitely makes sense to reorder which icons/boxes link to which pages, based on our desired engagement for users. Making the whole clickable is a good suggestion as well, but I would think about if (I say if, because it may not suit) there is a way to include shortcuts to some of the links that currently exist on the homepage. However, there is merit to ensuring that people visit the Contributing Code page, before we give them a quick link to "Help wanted" issues. I was only able to review the screengrabs you posted, the Moqups link is private. I look forward to your application, and make sure that the Moqups link at that time is open for external viewing.

@Bob160 the homepage is in the right direction. The blog page I assume is still under construction, with the changing background color that doesn't match any obvious change in sections. Two things I'd encourage you to do: 1) look at the Header and Footer in the Figma Design Library (https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=1433%3A0) and use those designs instead, since those will be global across all CC products when they get integrated. 2) I'd encourage you to think about if you can reorder components at all to get the icons/boxes higher up the page. While a strong hero image can be aesthetically pleasing, we do also want to think about what the core actions we want people to take are on the site.

@676308067 thank you for contributing both wireframes for Mentorship Guidelines, as well as a mockup of the homepage. I'd love to see how you'd restructure the homepage content to keep in mind the Design Library (linked above) for header/footer styles.

@jahnvigupta I encourage you to rework your contribution to take into account the Design Library, and also to ensure that there are no content changes. The current suggestion removes the Get Involved text, and only has six cards, versus the seven currently present on the site. A flexible design on cards is also encouraged, because we may end up adding more things to the homepage to highlight areas of specific importance for folks arriving there.

@panchovm will be on hand next week to look through updated contributions, so please leave comments to indicate that changes have been made, and explain what those entail.

Thank you everyone for your work here. We are looking forward to project proposals.

**Comment by terrifricker** [comment]
Thank you for the feedback @annatuma.  It is really appreciated.  I've made my moqups public to enable people to be able to see my notes, etc.
Homepage: https://app.moqups.com/RQ6fQZsfhm/edit/page/a50add8af
next page: https://app.moqups.com/RQ6fQZsfhm/edit/page/ae2e7c544

Now that I understand that you would like to see what we do with the Figma Design Library, I'll work on some new ideas.

**Comment by kushaggarwal** [comment]
Thank You @annatuma for your valuable feedback and suggestions
Will definitely go accordingly and attend to all the changes and improvements as mentioned by you

**Comment by Bob160** [comment]
@annatuma your feedback is highly appreciated, Thank you very much.
 I have resumed work on the wireframe to effect the necessary changes.

**Comment by ernestmusong** [comment]
Hello @annatuma and @panchovm I do appreciate your guidelines with respect to the design library. I have updated the CC Open Source Website's home page. I have added a home link for easy navigation. I have also created wireframes for the blog and contribution pages. Please do visit the below link to view and guide my way. Thank you all.
https://www.figma.com/file/BEIHKlkeNAnFhl7mNagKuQ/OPEN-SOURCE?node-id=221%3A0

**Comment by fcoveram** [comment]
Hi @676308067 As Anna mentioned before. It's crucial to use the Design Library, specially Header, Footer, and the grid. The three layouts look very similar to the current design, and we are expecting something different that can stand out the CC brand. I will recommend you trying something different, align with the rules of color and typography.

**Comment by dwvicy** [comment]
@annatuma and @panchovm, Hey! I've been working on layout designs, so I was wondering whether you are looking to see the header provided in the design library (the black one) or the one used the CC.org and the current Open Source website (orange).

**Comment by fcoveram** [comment]
Hi @dwvicy. The header you should use is the one in the Design Library.

**Comment by dwvicy** [comment]
@panchovm Thank you for your help! Here's the link to my wireframe:

https://www.figma.com/file/0sSz0fG4a45dNlzo9ZP7gj/CCOpen-Source-by-Vaishnavi-Dwivedi?node-id=0%3A1

 Looking forward to your feedback! @annatuma

**Comment by 676308067** [comment]
Hello @panchovm, greetings. As regards your feedback and recommendation  with reference to the design library, I have re-examined my header and footer, and i've effected the changes, Please visit the below link to see the changes in my wireframes. The hero images are annimated. Thank you.

**Comment by ernestmusong** [comment]
Hello @panchovm, greetings. As regards your feedback and recommendation with reference to the design library, I have re-examined my header and footer, and i've effected the changes, Please visit the below link to see the changes in my wireframes. The hero images are annimated. Thank you.
https://www.figma.com/file/BEIHKlkeNAnFhl7mNagKuQ/OPEN-SOURCE?node-id=246%3A0

**Comment by fcoveram** [comment]
Here my comments:

@dwvicy In the case of the homepage, we are expecting a new layout. A different way of distributing the elements on the page. I encourage you to experiment with something different. For the remaining pages, the same suggestion. It is also important to follow the typography rules. Not allowed full-width paragraphs.

@676308067 The header and Footer must remain untouchable. In the case of the main image, I am not sure about this proposal. The image doesn't communicate something clearly and has contrast problems when text is placed over. Then, the section below, it overuses the yellow and boxes are too big. I will suggest trying something different from the colors that CC brand has.

**Comment by dwvicy** [comment]
@panchovm I have experimented a bit with the homepage, let me know if this is the right direction for the expected layout.

https://www.figma.com/file/0sSz0fG4a45dNlzo9ZP7gj/CCOpen-Source-by-Vaishnavi-Dwivedi?node-id=0%3A1

**Comment by jshreyans** [comment]
Hi everyone! This is the design that I've been working on for the last few days. Looking forward to reviews!
[Design Prototype - CC Open Source](https://www.figma.com/file/1UIzkXbeVYKSDG1T1YiooL/cc-open-source-website?node-id=0%3A1)

**Comment by ernestmusong** [comment]
Hello @panchovm please visit the below link to view changes to my wireframes. Thanks.
https://www.figma.com/file/BEIHKlkeNAnFhl7mNagKuQ/OPEN-SOURCE?node-id=287%3A493

**Comment by kushaggarwal** [comment]
Hello @panchovm as guided by @annatuma I have made some modifications in the design for CC Open Source. 
Please find the below link for the figma wireframes and advise for changes and improvements for the same
Link : https://www.figma.com/file/gN3puDIwMJXER8jxHEpuKR/CC-Open-Source?node-id=0%3A1
Thank you

**Comment by tacitonic** [comment]
Hello @panchovm @annatuma, would it be possible if I could invite you to view my design in order to maintain originality?
If not, I will post the link, but please take a note of the design originality.

**Comment by fcoveram** [comment]
Hi everyone, thanks for your proposals.

@dwvicy On the homepage, each element uses too much space of the layout. I will try having less space between elements and sections and smaller icons. On the other hand, putting dark text on tomato and gradient colors are not allowed.

@jshreyans Editing header and footer are not allowed. Despite that, the first section, paragraph on the left and image on the right, looks good. I will try not to use an effect on the image. At the same time, text-size is too big in every section. I will use the standard size.

@676308067 You're using a high contrast that is too difficult to read and colors that don't exist on our palette. The first paragraph is too rigid because of the background color and the wrapper. I will try applying less contrast by using colors like grays or yellow.

@kushaggarwal I am not sure which option (1 or 2) you prefer. I like more the first one. However, Ubuntu as font is not allowed, the same with editing button components. I will try using different icons or mini-illustrations for each section below. Also, we have more colors in our palette, try using others.

@tacitonic Please send the link.

**Comment by tacitonic** [comment]
@panchovm Here it is: 
https://www.figma.com/file/M5HUTZEYims7XxMkMqDjYf/CC-Open-Source-Redesign?node-id=0%3A1

**Comment by kushaggarwal** [comment]
Thank you @panchovm for your feedback and changes will do so

**Comment by fcoveram** [comment]
Thanks for sharing it @tacitonic. Here my comments:

1. The header should not be modified. Also, based on the typography definition, full-width paragraphs are not allowed.
2. The homepage layout is very similar to what we currently have. I will try a different distribution of elements. I like the use of colors but the icons are the same. Maybe try something different with those two elements.

**Comment by tacitonic** [comment]
@panchovm Thanks for reviewing!

1. Are full width paragraphs not defined for the header region or site-wide? For example, which page are you referring? 

2. Are the use of icons mandatory? If yes, the predefined design elements don't have any icons to use, so do I have the liberty to select them? I will modify my homepage design as well.

**Comment by fcoveram** [comment]
@tacitonic 
1. Sorry. I was referring to the homepage. Full-width paragraphs are not allowed in all cases.
2. You can choose new icons. No problem.

**Comment by tacitonic** [comment]
@panchovm
Not including the paragraphs from the current CC Open Source Homepage in the new redesign would mean that there is a change in content. Should I go ahead with that?

**Comment by kushaggarwal** [comment]
@panchovm can it happen that I can work with different colors as a base color for different pages
and also as per the font for the site we have roboto condensed for header but can you please guide for the paragraphs and other text as if which should I go for
Thanks

**Comment by ernestmusong** [comment]
Hello @panchovm please I need some clarification. Is full width not allowed only for paragraphs? 
E.g, can I distribute  blog posts on the same line across the body of the page? Please your response. Thanks.

**Comment by fcoveram** [comment]
@kushaggarwal The colors and fonts available are those indicated in the Design Library. For now, do not add more.

@676308067 Full-width is not allowed for texts. Other elements can be placed full-width, but, in this case, I don't think it will work. In most cases, full-width elements are difficult to read.

**Comment by jshreyans** [comment]
@panchovm Thanks for all your suggestions. I've made some changes. I'm currently reworking the Contribution Guidelines page and will soon post for reviews.

**Comment by ernestmusong** [comment]
Hello @panchovm please visit the link below and see the changes i've made to my colors. Thanks.
https://www.figma.com/file/BEIHKlkeNAnFhl7mNagKuQ/OPEN-SOURCE?node-id=341%3A1511

**Comment by tacitonic** [comment]
Hey @panchovm!
I finished updating my design according to your suggestions. Please have a look: https://www.figma.com/file/M5HUTZEYims7XxMkMqDjYf/CC-Open-Source-Redesign?node-id=0%3A1
Also, I've submitted my draft proposal and I would love to hear your thoughts and inputs on it as well.
Thanks!

**Comment by fcoveram** [comment]
@676308067 I like more this layout, the distribution of elements. However, you are using too much black color as a background with text over it. Have you tried using different icons? It will improve if you pick icons with a different style. The blue color should not be used as a background color for the main content.

@tacitonic I like your proposal. The layout looks clean and colors as border work well. The tomato color for the first section it's bold but difficult to read. The contrast of black/white over tomato should be changed. Besides, putting the CC logo again in that section is redundant and confused. 

Thanks for working on this

**Comment by tacitonic** [comment]
I'm pleased that you like the overall design aesthetic @panchovm.
I agree with the contrasts being sharp on the tomato section - I'll change it to orange.
Although I used the updated header and footer, the default logo branding is for CC only - not CC OS which is why I featured it. Is there any way I could get around with that? 
Thanks for the feedback!

**Comment by dwvicy** [comment]
@tacitonic you could select the logo from the header, delete it and replace it with the header for CC OS which is given in the logo assets.

**Comment by tacitonic** [comment]
@dwvicy This is what I had done before. But it falls on the fence of whether that's considered a change to the header or not. That is why I'm unsure.

**Comment by fcoveram** [comment]
For now, just keep the CC logo in the header. We are working on updating the logo of all our products.

**Comment by 676308067** [comment]
Hello @panchovm greetings,  I have worked on the issues you raised as regards my wireframes and some changes have been made. Please visit the below link and take a look. Thanks,
https://www.figma.com/file/BEIHKlkeNAnFhl7mNagKuQ/OPEN-SOURCE?node-id=301%3A1143

**Comment by kushaggarwal** [comment]
Hello @panchovm 
Please find and review the below link for the updated wireframes for the CC Open Source site as guided by you 
Link : https://www.figma.com/file/gN3puDIwMJXER8jxHEpuKR/CC-Open-Source?node-id=0%3A1
Thanks

**Comment by ernestmusong** [comment]
Hello @panchovm I have worked on the issues you raised concerning my wireframes and changes have been made. please visit the lijnk below to see these changes. Thanks.
https://www.figma.com/file/BEIHKlkeNAnFhl7mNagKuQ/OPEN-SOURCE?node-id=287%3A493

**Comment by silvinabt87** [comment]
Hi, @panchovm @dhruvkb. I've made a wireframe for the CCOS web page. Any feedback to improve it will be useful: 
https://www.figma.com/file/VqmcBCag1vnmxTAYk7N7HE/CC-Open-Source-Homepage?node-id=0%3A1
Shall we make a PR for this? Or is it enough for your revision with the link on this comment?

**Comment by dhruvkb** [comment]
@silvinabt87 I left some comments on your mockups. I didn't understand what you meant by "Shall we make a PR for this?". Implementing the redesign in code is one of the Outreachy and GSoC project ideas.

**Comment by fcoveram** [comment]
@kushaggarwal I like how you solved the Get involved section in terms of spacing and layout. However, the interaction is too bold and should be more subtle. It could be just displaying the link's information only when user hovers the item, not the whole section. On the other hand, colorful icons look a good idea, but only when are placed on non-color backgrounds. Regarding icons, the style are quite different between them. Stroke widths, stroke colors, internal shadows, and palette are all different. This is something where you can work on.

@676308067 The page's title looks too colorful for the intention of this site. I will change that and use the basic default color allowed. Regarding **Get involved** section, icons look good, but as the above comment, the styles are different. For the first row, you have a high-detailed icon in contrast with a symbolic icon. Plus, background color for boxes. I will pick one or another, not both.

@silvinabt87 I loved the illustrations, I will apply some improvement to express better the idea beneath the link. But in general, good selection. However, the header is a component that cannot be modified. Use the component as it is. A second observation is the background color, I will use white or the lightest gray of our palette. Basic styles like paragraph and title cannot be modified, except the fill color and other color mixes. But a very good proposal.

**Comment by silvinabt87** [comment]
@panchovm thanks for the feedback. I'll work on it. What I didn't understand fully, I think, was the paragraph and title part. Can I not make changes to that, regarding line spacing for example? @dhruvkb thanks for the comments. I already changed some stuff and answered to your comments. As regards the PR, for a moment I thought we could do one so that we could get the link to record our contribution, but I then read that we can leave our designs here as a comment and you'd revise them.

**Comment by fcoveram** [comment]
@silvinabt87 For now, we want to keep the Vocabulary definitions as they are. Especially text styles. When using the header component, you can hide the `CC products` layer to just keep the main nav of the site.

**Comment by kushaggarwal** [comment]
Thank you @panchovm for your suggestions will work towards the implementation of the same with the current designs

**Comment by ernestmusong** [comment]
Hello @panchovm, thanks for your feedback. Based on your comment I have made the following changes. Please visit the link below, thanks.
https://www.figma.com/file/BEIHKlkeNAnFhl7mNagKuQ/OPEN-SOURCE?node-id=287%3A493

**Comment by arushivii** [comment]
Hi @panchovm , I tried making the wireframes. Can you please have a look.
Here is the link: https://www.figma.com/file/GSCIs6W9jUL2mJIpjSfWb4/CC-OPEN-SOURCE?node-id=0%3A1

**Comment by silvinabt87** [comment]
@panchovm @dhruvkb Here go my new designs:
Homepage: https://www.figma.com/file/VqmcBCag1vnmxTAYk7N7HE/CC-Open-Source-Homepage?node-id=90%3A0
Blog section: https://www.figma.com/file/VqmcBCag1vnmxTAYk7N7HE/CC-Open-Source-Homepage?node-id=87%3A0
Join the Community section: https://www.figma.com/file/VqmcBCag1vnmxTAYk7N7HE/CC-Open-Source-Homepage?node-id=121%3A1810
Contribution guidelines section: https://www.figma.com/file/VqmcBCag1vnmxTAYk7N7HE/CC-Open-Source-Homepage?node-id=135%3A24

**Comment by 676308067** [comment]
Hello @panchovm, thanks for your feedback. Based on your comment I have made the following changes. Please visit the link below, thanks.
https://www.figma.com/file/BEIHKlkeNAnFhl7mNagKuQ/OPEN-SOURCE?node-id=287%3A493

**Comment by jahnvigupta** [comment]
@panchovm Please give feedback on my designs.
https://www.figma.com/file/fJlOSTOgFbNimyQ9nem3IO/CC_Open_Source?node-id=0%3A1

**Comment by yolande-prog** [comment]
Hello @panchovm please can i still help ?

**Comment by fcoveram** [comment]
@676308067 I see a new proposal for the home page but the same graphic resources regarding icons and palette. It is crucial solving the home page first and then internal pages.

@av-00 Thanks for participating. You should use the defined colors; for now, we are not adding new ones. Try using more text styles for the following sections; it looks too rigid and difficult to read. It is essential to apply contrast to texts by using the Vocabulary' styles.

@silvinabt87 I like the new version. Maybe the translate our content illustration might have more visual information. For instance, the `usability testing` item is very clear in communicating the content behind. For the `Code of conduct` pages, I will not hide content in sections. It is not necessary for the page's goal. The remained pages look suitable for the content displayed.

@jahnvigupta Thanks for participating. Regarding the home page, the links in the `Get Involved` section are too difficult to read, in terms of colors and contrast, and distribution. The links placed in the center generate an unnecessary white space in corners. 

Thank everyone for your contribution.

**Comment by jahnvigupta** [comment]
> @panchovm Please give feedback on my designs.
> https://www.figma.com/file/fJlOSTOgFbNimyQ9nem3IO/CC_Open_Source?node-id=0%3A1

@panchovm Please review my blog page as well.
https://www.figma.com/file/fJlOSTOgFbNimyQ9nem3IO/CC_Open_Source?node-id=1%3A2

**Comment by jahnvigupta** [comment]
@panchovm Please have a look at my new designs.
https://www.figma.com/file/fJlOSTOgFbNimyQ9nem3IO/CC_Open_Source?node-id=9%3A2360

**Comment by annatuma** [comment]
Thanks to everyone for their submission. Because the application period has passed, we are now reviewing final proposals, and are no longer accepting contributions on this task.
