### ISSUE TITLE
Integrate Figma with the storybook

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#153]
**Description**
The Figma file for design library contains a lot of instructions on the usage and development of more components. The contents of the Figma file make a valuable addition to the Storybook. A simple plugin embeds portions of the file in the storybook, so integrating it should meet our needs.

**Additional context**
- [Storybook addon](https://github.com/pocka/storybook-addon-designs)

**Comment by Tanuj22** [comment]
@dhruvkb I would like to work on this.

**Comment by kushaggarwal** [comment]
If this issue is still open I would like to go for same 
Thank You

**Comment by dhruvkb** [comment]
@kushaggarwal we have a 7-day of inactivity rule before an assigned issue is re-assigned. Can you work on some other issue in the meantime? @Tanuj22 I didn't formally assign it to you immediately, sorry for that. Please go ahead and work on it.

**Comment by kushaggarwal** [comment]
Okay sure no problem
