### ISSUE TITLE
Dotted outline in buttons in firefox

### ISSUE THREAD

**Issue by Vineet-Sharma29** [cc-archive/vocabulary-legacy#156]
**Description**

**Reproduction**
- Click on a button

**Expected behavior**
There shouldn't any outline around button

**Screenshots**
![Screenshot from 2020-03-03 20-11-56](https://user-images.githubusercontent.com/35156299/75787233-6afd2100-5d8c-11ea-8e1b-3ae3056b47a1.png)

**Conditions:**

 - OS: Ubuntu18.04
 - Browser : Firefox
 - Version : 73.0.1 (64-bit)

**Want to take up?**

Yes. Can CC team assign this to me?

**Comment by khelvn** [comment]
Hello, I would like to work on this.

**Comment by dhruvkb** [comment]
@khelvn I cannot assign it to you for a couple of reasons
- I'm not even sure this is an issue. The dotted border does look bad, but it is a functional part of accessibility and keyboard-driven usage.
- @panchovm might want to design a better looking version of the button that indicates focus. That would take time.
- @Vineet-Sharma29 already said he wanted to work on it, and since he found it, it would be fair that he get to fix it.

Could you please find some other issue to work on?

**Comment by khelvn** [comment]
@dhruvkb please is there any other issue you could assign me

**Comment by fcoveram** [comment]
I am not sure how firefox renders the focus state of buttons. I was pretty sure that the border was on the whole button and not on the label. Might that be a front-end issue? If it is not, then let's not change the native browser definition. It is crucial for accessibility.

**Comment by Vineet-Sharma29** [comment]
this can be resolved by adding `::-moz-focus-inner {border: 0;}` to button's class. It will not affect outline.

**Comment by dhruvkb** [comment]
@panchovm should we alter the CSS to ensure the border comes on the border of the component?

**Comment by kgodey** [comment]
adding the "blocked" label until @panchovm responds.

**Comment by fcoveram** [comment]
Let's apply what @Vineet-Sharma29 proposes.

**Comment by silvinabt87** [comment]
Hi! If this issue isn't solved yet, I'd like to contribute

**Comment by dhruvkb** [comment]
@silvinabt87 it is actually solved by @Vineet-Sharma29's PR #172. You (both) can contribute to #165 as that one's wide open!

**Comment by brenoferreira** [comment]
I couldn't reproduce this on FF 73.0.1 (64-bits) on Mac OS 10.15.3.

The proposed solution in #172 isn't recommended by Mozilla https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-focus-inner

**Comment by dhruvkb** [comment]
@brenoferreira I was also skeptical about its impact from an a11y perspective.

**Comment by brenoferreira** [comment]
No one on our team was able to reproduce this. It seems to me this probably doesn't affect many users. And since this solution isn't recommended, I'm closing this
