### ISSUE TITLE
Create separate bundles

### ISSUE THREAD

**Issue by brenoferreira** [cc-archive/vocabulary-legacy#167]
Vocabulary will be used in many different CC websites, such as:

* cc.org
* CC Network
* CC Summit
* CC Search

And Vocabulary can end up containing components that are particular to a couple of different websites, but not others.

Vocabulary is modular, so for websites that use SASS, it's easy to import the modules you need. But if we need to import individual modules all the time, usage of Vocabulary becomes unnecessarily difficult.

In order to mitigate that, we could create different bundles for different websites:

* vocabulary-base.css
* ccnetwork-base.css
* ccsummit.css
* ccsearch.css
* so on...

vocabulary-base.css would contain only base component styles (such as buttons, typography, spacing, etc..) and the remaining bundles (which would contain the base styles in them, so people don't have to import two css files, but rather only one) would contain site specific component styles

**Comment by hugosolar** [comment]
I don't think this is necessary at this point... websites are going to share a lot of components and that's the idea. 
I think it's enough just by using the components you need for the project, that's the idea of using Sass and turning vocabulary in a sort of framework. 
Frameworks like bulma or foundation come with a large number of different components and elements and it's not mandatory to use them all, and that's fine.
I would try vocabulary as it is and evaluate how it's working in a range of a year or less...

**Comment by brenoferreira** [comment]
Should I close this? If we need it in the future we can reopen it

**Comment by hugosolar** [comment]
Maybe we can wait for @kgodey feedback

**Comment by dhruvkb** [comment]
I think that the onus of making bundles should be on the sites rather than on Vocabulary. Sites can import the Sass files they need and their own Webpack setup will handle the bundling.

**Comment by kgodey** [comment]
Agreed with @dhruvkb and @hugosolar

**Comment by dhruvkb** [comment]
@brenoferreira I don't know about the status of this issue.

**Comment by brenoferreira** [comment]
Clients can figure out their own imports and build their own bundle instead of this being done in Vocabulary
