### ISSUE TITLE
Header is broken after token updates

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#174]
**Description**
A) The `header.scss` file breaks after the token changes made in #161. Changes to spacing tokens, color tokens break the stylesheet. 

B) Simultaneously changes to the Logos story breaks the Header story too.

**Reproduction**
A) Clone the repository and build the stylesheets on the `master` branch at 35484bb with `npm run build`
B) Start storybook with `npm run storybook`

**Expected behavior**
A) Stylesheets should get compiled into a `vocabulary.css` file. 
B) Stortybook should start up with all contents.

**Cause**
Work done on PR #161 should have marked PR #145 as blocked. The order in which they were merged might have been a factor too.

**Comment by dhruvkb** [comment]
A temporary measure would be to 
- remove `header.scss` from `vocabulary.scss`
- rename `header.stories.js` to `header.stories.js.bak`

**Comment by dhruvkb** [comment]
A proper solution would involve 
- finding all uses of tokens, mainly spacing and colors and replacing them with the proper names
- updating the stories to use MDX and not import content from other stories

**Comment by Chigael** [comment]
Hi I am Abigael, please i would love to work on this issue, is it still open?

**Comment by jahnvigupta** [comment]
I would like to take this issue.

**Comment by dhruvkb** [comment]
@Chigael and @jahnvigupta this was time constrained so I had to step in and solve it. Sorry but, as you can see, it was solved 10 hours before you asked.
