### ISSUE TITLE
Ensure Figma designs linked to all stories

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#181]
**Description**
Every story in [the Vocabulary storybook](https://cc-vocabulary.netlify.com) should be associated with a Figma node from the Design Library.

**Problems solved**
This allows us to immediately connect Figma designs with their implementation in code, making it easy to keep the design and code in sync.

**Comment by megha070** [comment]
@dhruvkb I would like to work on this.

**Comment by jahnvigupta** [comment]
I would like to work on this issue @dhruvkb .

**Comment by dhruvkb** [comment]
@megha070 and @jahnvigupta and **future contributors**, to avoid conflicts, I would recommend that
- you pick your component and state it in the conversation
- immediately open a draft PR (naming the component in the title)
- making individual, independent PRs per component to avoid merge conflicts

You can refer to the story of Input for examples. The Design Library can be found [here](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library).

**Comment by jahnvigupta** [comment]
I will do it for cards.

**Comment by jahnvigupta** [comment]
I will do it for buttons.

**Comment by megha070** [comment]
I will do for License Badges

**Comment by megha070** [comment]
@dhruvkb cards and global header files are not in MDX format. 
@jahnvigupta is working on buttons.
For License Badges, I am unable to figure out how do I get codes corresponding to all badges.
For Locale and Tabs, I have raised PR

**Comment by lily-dev** [comment]
@dhruvkb I would like to contribute and work on form, pattern, table & tabs.

**Comment by megha070** [comment]
Hey @lily-dev! I have raised PR for all missing links. Please find another issue.

**Comment by dhruvkb** [comment]
@lily-dev you could try #185.
