### ISSUE TITLE
Ensure that the code samples are correct

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#185]
A lot of stories feature repetitive code. To avoid duplication we generally use functions like
```js
export const heading = (level) => `<h${level}>Heading ${level}</h${level}>`
```
and then we write stories like 
```html
<Preview>
  <Story>{heading(1)}</Story>
</Preview>
```

This eliminates the code repetition but leads to incorrect code previews.
![Screen Shot 2020-03-18 at 11 45 35](https://user-images.githubusercontent.com/16580576/76931110-00142400-690e-11ea-96f6-0c74c8a10a04.png)

The correct code can be inserted into the preview using the `mdxSource` prop on the `Preview` component. So a better story would look like
```html
<Preview mdxSource={heading(1)}>
  <Story>{heading(1)}</Story>
</Preview>
```
An example can be found in PR #176.

The goal is to have this done across all stories in the storybook where such function-based code is used.

**Comment by jahnvigupta** [comment]
@dhruvkb Can you share some link that can help me the rules to convert functions to stories.

**Comment by megha070** [comment]
@jahnvigupta I found this very useful in order to get started with MDX Docs.
https://mdxjs.com/getting-started
The idea is to convert all src/<component>.stories.js files to MDX Docs.

**Comment by megha070** [comment]
@dhruvkb I would like to take this up.

**Comment by megha070** [comment]
@dhruvkb I have raised PRs for License_badge, github_corner and logos file.
@jahnvigupta is working on cards file
rest others are fine.

**Comment by dhruvkb** [comment]
@megha070 just finish this issue by updating Cards like you did for the other components.

**Comment by megha070** [comment]
Sure @dhruvkb!

**Comment by kgodey** [comment]
@dhruvkb will take a look to see if any components still need this.
