### ISSUE TITLE
Removing @yy from the PR template

### ISSUE THREAD

**Issue by yy** [cc-archive/vocabulary-legacy#193]
**Description**
Hi, whenever someone doesn't change the template, I get a notification because my GitHub username is "yy". Would you mind changing the template?

**Comment by kgodey** [comment]
Sorry about that @yy, we'll fix it.

**Comment by achilep** [comment]
hello please can i solve it

**Comment by achilep** [comment]
i will like to work on it if possible?

**Comment by kgodey** [comment]
Please do. Under our new [contribution guidelines](https://opensource.creativecommons.org/contributing-code/), if an issue is marked "help wanted", you do not needt permission to work on it.

**Comment by achilep** [comment]
ok thank you

**Comment by achilep** [comment]
please Mme  this link  :https://github.com/creativecommons/.github  to the  PR template is the right one or there is another one ?

**Comment by dhruvkb** [comment]
This is one of the strangest issues I've seen. @achilep would you mind making this change across all three repos: `vocabulary`, `vue-vocabulary` and `fonts`?

**Comment by achilep** [comment]
thank you

**Comment by achilep** [comment]
1- fonts :  https://github.com/creativecommons/fonts/pull/17

2-vocabulary:  https://github.com/creativecommons/vocabulary/pull/196

3-vue-vocabulary: https://github.com/creativecommons/vue-vocabulary/pull/191

this are the link to the  different Pr that i have made to fix the issue
