### ISSUE TITLE
Create Figma/Zeplin components for prototyping

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#2]
**Description**
Designers prefer tools like Figma, Adobe XD, InVision and Zeplin for UI prototyping. Having components and a playground is okay but for actual speedy prototyping we need these assets available readily.

**Problems solved**
Having assets for one or two of the most popular of these tools would greatly simplify using Vocabulary in other apps while also making it easier to ideate changes to Vocabulary itself.

**Additional context**
@panchovm is already using Zeplin for prototyping so those components could be used and reviewed by him.

**Comment by fcoveram** [comment]
I have discussed with the team to move from Sketch to Figma. The public component library will be a useful feature for future designs. However, right now, we just started by using Vocabulary in mockups.

**Comment by dhruvkb** [comment]
Figma is actually pretty great! 👍

**Comment by fcoveram** [comment]
Can we @kgodey close this issue? I think this belongs to our current workflow rather than a specific task.

**Comment by dhruvkb** [comment]
Since @panchovm is already making the Figma DL which is our SSOT, and I opened the issue for exactly that purpose, I'll close it.
