### ISSUE TITLE
Switch to declarative Storybook syntax

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#20]
The Storybook that has been set up in the project uses the old Storybook configuration syntax consisting of `config.js` and `addons.js`. With the new release, Storybook is moving towards a new syntax with the old one to be deprecated and eventually discontinued.

The goal is to implement the [new syntax](https://medium.com/storybookjs/declarative-storybook-configuration-49912f77b78) so that there are no issues in the future.

**Comment by Kirti2502** [comment]
I am an outreachy applicant and would like to work on it.
@dhruvkb may I take this issue?

**Comment by dhruvkb** [comment]
Unfortunately @Kirti2502 this has already been implemented. Please pick another issue to work on.
