### ISSUE TITLE
Adding usage instructions in getting started section in README.

### ISSUE THREAD

**Issue by techievivek** [cc-archive/vocabulary-legacy#200]
**Description**
The getting started section in README has no instruction related to the usage of Vocabulary for local development projects.

**Problems solved**
Clear and concise instruction to allow developers to use /integrate vocabulary design system in their local development projects.

**Additional context**
This will help developers to try and use the Vocabulary design system with their projects. This will basically instruct user to use Vocabulary CDN link for usage.

**Want to take up?**

Yes

**Comment by krysal** [comment]
Hi @techievivek, are you going to make a PR for this? It seems to me that it's important so I want to fix it if you don't.

**Comment by techievivek** [comment]
I am not able to create a PR as I am traveling back to my home due to COVID-19 pandemic.
If you would like to add a PR you can 😊

**Comment by krysal** [comment]
Oh, sorry to hear that, I hope you arrive safely.  🏠
I'll work on it.
