### ISSUE TITLE
Consistent priority of color, brand, tone and indication

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#22]
**Description**
Almost all components support functional colours (and shades), brand colours, tonal colours and contextual colours as means of customisation. These are implemented in Stylus using the mixins `colors()`, `brands()`, `tones()` and `indications()` respectively. The order in which they are invoked in the Stylus files determines the priority order should conflicts arise.

**Reproduction**
On a component that supports more than one of these mixins, pass both in the props. The final outcome cannot be predicted deterministically without a set priority order.

**Expected behavior**
The priority of colouring options should be well-defined and documented.

**Additional context**
The goal is to defined and document a logical priority order that results in predictable behaviour and ensure its consistent enforcement across all components.

**Comment by anisin97** [comment]
Hi @dhruvkb , this issue is labelled 'blocked', but can I work on it. Or should I work on an issue that is preventing this from progressing.

**Comment by dhruvkb** [comment]
@theprover97 this issue is marked blocked because some other work on the repo will cause work on it to become redundant. It would actually be good if you took up something else.
