### ISSUE TITLE
Replace src/stories/footer.stories.js with MDX Docs

### ISSUE THREAD

**Issue by kushaggarwal** [cc-archive/vocabulary-legacy#229]
**Description**

**Problems solved**

**Alternatives**

**Additional context**

**Want to take up?**

Yes

**Comment by kushaggarwal** [comment]
Hello
I saw that most of the components for vocabulary have been currently replaced with the MDX docs while I suppose this is still left 
So, if available and needed can I work on this issue 
Please help
Thank you

**Comment by dhruvkb** [comment]
@kushaggarwal please update the issue description and then start work on it.

**Comment by dhruvkb** [comment]
Also ensure that once all the stories are ported from `.stories.js` to `.stories.mdx`, you should remove the `.[tj]s` extension from `.storybook/main.js` to prevent future stories from being written in the JS format.

**Comment by kushaggarwal** [comment]
Okay will do so thank you @dhruvkb

**Comment by dhruvkb** [comment]
@kushaggarwal this issue has become a high priority issue as @makkoncept needs the code for the [CC Search browser extension](https://github.com/creativecommons/ccsearch-browser-extension).

**Comment by kushaggarwal** [comment]
Sure @dhruvkb will attend to this at the earliest

**Comment by kushaggarwal** [comment]
Please help @dhruvkb  as I am not able to figure out what should be added in design :figmaConfig("")
![Screenshot 2020-03-25 at 8 17 01 PM](https://user-images.githubusercontent.com/44523552/77549462-e0fd2f80-6ed5-11ea-8cde-04905b1e1d3d.png)
