### ISSUE TITLE
Hamburger and close button click event it's not optimal

### ISSUE THREAD

**Issue by hugosolar** [cc-archive/vocabulary-legacy#234]
**Description**
In both cases the click event is set to the lines of the elements and not the square itself. This isn`t recommended because it can lead sometimes to users get frustrated and cannot open the menu or close it.
Also, I think the dropdown menu should float over the content and not pushing it

**Expected behavior**
the recommended behavior is the event happens on the container surrounding the element (<a>)

**Screenshots**
![description image](https://dsc.cloud/c9cdcc/Screen-Recording-2020-03-25-08-27-14.gif)

**Comment by techievivek** [comment]
@hugosolar I will like to work on this one also can you please tell me which file I will get listener for hamburger icon.

**Comment by dhruvkb** [comment]
@techievivek you should look at `src/styles/header.scss` and `src/stories/header.stories.mdx`.

**Comment by techievivek** [comment]
> @techievivek you should look at `src/styles/header.scss` and `src/stories/header.stories.mdx`.

Thank you, I will check it.

**Comment by techievivek** [comment]
@dhruvkb I have added "dropdown item floating over content feature" and for the click event on the hamburger icon, I can see a 
```html
 <a role="button" class="navbar-burger is-active" aria-label="menu" aria-expanded="false">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
 </a>
```
should I play with this to achieve above functionality?

**Comment by dhruvkb** [comment]
@techievivek I don't quite get what you mean by that comment, but I think the best way to explain is to show us a demo with a draft PR.

**Comment by krhitesh** [comment]
@hugosolar Please have a look at #264

**Comment by dhruvkb** [comment]
@hitesh1157 submitting PRs to existing issues is only going to put them on hold. That does no one any good. I would recommend you work on the issues that are still looking for contributors.

**Comment by techievivek** [comment]
@hitesh1157 Just changing the width wouldn't work and that also you have just done for the hamburger icon, what about close icon?
This is different issue.

**Comment by krhitesh** [comment]
@techievivek @dhruvkb  As per my tests, the derived width of `a` tag that you pasted above is `0px`. Instead, this should be set to `3.25rem` according to bulma's own implementation. Setting `width` to correct value fixes the `navbar-burger`'s state for both burger and close buttons.

**Comment by krhitesh** [comment]
@techievivek The reason why you set `width: 3.25rem;` to `.navbar-burger` in your recent [commit](https://github.com/creativecommons/vocabulary/pull/254/commits/324934b7ae4b1f815231d6907b0d95ca2fa8e96e) to your existing PR #254 , can you please explain that?

**Comment by techievivek** [comment]
@hitesh1157 As you suggested earlier it's true there was no initial width, so I went up to CC search and checked in developer tools and played with it, and it was working just fine for the given width value and thus updated the PR to include change for both the issue.

**Comment by hitesh1157** [comment]
> and it was working just fine for the given width value

So you do not know why width is set to exactly `3.25rem`. See @techievivek, copying without attribution is condemned. This is a collaboration platform. So if you had thought that something in my commit was working, "we" could have merged branches and worked together.

@dhruvkb @hugosolar

**Comment by techievivek** [comment]
@hitesh1157 I do understand your contribution and have admitted it. But I haven't asked for review on my PR and Yes this is a collaboration platform and I was waiting for some response from @dhruvkb or @hugosolar so that we can discuss all the aspect.
And just for the note it wasn't that I wasn't aware that it could be possibly that the icon doesn't have height and width as of its parent container or the listener isn't set properly, and if you see my PR I have already stated few concerns and this issue can also be part of CC-catalog. Hope we get review soon and work on it together.

**Comment by krhitesh** [comment]
I have worked on this issue in #264 , @dhruvkb Could you assign this issue to me as well?

**Comment by dhruvkb** [comment]
@techievivek and @hitesh1157 I'll review both your PRs today. Please continue to work on other issues in the meantime.

**Comment by techievivek** [comment]
> I have worked on this issue in #264 , @dhruvkb Could you assign this issue to me as well?

I have reverted the part contributed by you, you have a scope to refactor your code as I did in my PR. Both of our PR can be merged now separately.
