### ISSUE TITLE
Replace Welcome story with a no-story MDX doc

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#236]
**Description**
Currently the Welcome page of the Storybook is a story. It should be replaced with a [no-story MDX doc](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/mdx.md#documentation-only-mdx).

**Problems solved**
This opens the door for additional helpful pages such as 'Installation', 'Getting started' or 'How to use' etc. It'll also be an asset in the resolution of #200 by #214.

**Additional context**
The Story was a quick fix hack. This presents a chance to actually solve what was once hastily implemented as a temporary solution.

**Comment by dhruvkb** [comment]
@cangreja533 I saw your message about lack of issues to get started. Would you be interested in this?

**Comment by jahnvigupta** [comment]
@dhruvkb If he is not interested, I would like to take this issue.

**Comment by dhruvkb** [comment]
@jahnvigupta let's give them some time to respond. If they don't, in a couple of hours, you can definitely take it up.

**Comment by dhruvkb** [comment]
@jahnvigupta please go ahead in steps, immediately opening a draft PR so that we can continuously review and course-correct as necessary.

**Comment by jahnvigupta** [comment]
@dhruvkb I think you want something like this:
https://taimoormk.github.io/react-commons-collection/?path=/docs/1-react-pakistan-intro--page
