### ISSUE TITLE
The small button component doesn’t have the correct font.

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#237]
In the single result page, the `small button` component should have the Source Sans Pro font. See the component style in the [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A222&viewport=140%2C-1687%2C1.4707506895065308).

**Comment by Tanuj22** [comment]
Would like to work to this :)

**Comment by arushivii** [comment]
how do we find out in vocabulary which font is being used?

**Comment by dhruvkb** [comment]
If I'm not misinterpreting your question, most browsers have Developer Tools (in the right click context menu, click on 'Inspect Element'). You can use them to know the font being used.

**Comment by arushivii** [comment]
Maybe i misinterpreted this, can you clear this up for me?
I thought the `small button` component was in respect to use in vocabulary, while being in the canvas area
@dhruvkb
