### ISSUE TITLE
The tag component doesn’t follow the Design Library style.

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#238]
In the single page result, the tag component in **Tags** section should have the same font and hover state style defined in the Design Library.

### Expected design
<img width="395" alt="Screen Shot 2020-03-24 at 17 47 34" src="https://user-images.githubusercontent.com/895819/77475418-8e4d4600-6df7-11ea-8bda-6d1b3dfbd9a1.png">

**Comment by av-00** [comment]
![button](https://user-images.githubusercontent.com/43967251/77579169-e1aabb80-6eff-11ea-996a-442704058ebb.png)
Does it refer to just buttons like these, which just brighten up on hovering, or other elements too?
@panchovm

**Comment by kushaggarwal** [comment]
Hello @kgodey @panchovm 
I would like  to work on this if its open
Thanks

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
I am not able to generate a pull request for this issue as the issue no. doesn't seem to match while linking it to cccatalog-frontend repository for changes made 
Can you please help 
Thank you

**Comment by dhruvkb** [comment]
@kushaggarwal this is `creativecommons/vocabulary#238` or `#238`.

**Comment by kushaggarwal** [comment]
So for the pull request in the fixes should I write creativecommons/vocabulary/238 as upon writing 238 it refers to some other issue marked on the cccatalog 
@dhruvkb please help

**Comment by kushaggarwal** [comment]
Got it @dhruvkb Thanks
