### ISSUE TITLE
The "clear filters" button should have the style defined in Design Library

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#239]
In the search result page, the `clear filters` button (SmallBorder button in Design Library) should change the following:

### Default state
* Source Sans Pro font

### Hover state
* Border color `#787878`
* Background color `#787878`

## Design Library reference
<img width="410" alt="Screen Shot 2020-03-24 at 17 04 33" src="https://user-images.githubusercontent.com/895819/77471738-90140b00-6df1-11ea-9af5-ae2a9d945a4c.png">

**Comment by kgodey** [comment]
@abhisheknaiidu this issue has been transferred to Vocabulary but feel free to work on it, you don't need our permission since it's marked help wanted.

**Comment by Tanuj22** [comment]
Would like to work on this

**Comment by dhruvkb** [comment]
@Tanuj22 I guess we should see if @abhisheknaiidu is still interested as it has been less than a day since he expressed an intention to work on it.

**Comment by Tanuj22** [comment]
Okay

**Comment by dhruvkb** [comment]
@Tanuj22 please go ahead.

**Comment by abhisheknaiidu** [comment]
@dhruvkb Actually I sent a PR for this one in CC frontend repo [#817](https://github.com/creativecommons/cccatalog-frontend/pull/817) but later I came to know that this issue has been shifted here! So, @Tanuj22 you can go ahead, if you need any help, you can look at my PR.
