### ISSUE TITLE
Integrate JavaScript Standard Style with ESLint

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#24]
**Description**
The project follows [JavaScript Standard Style](https://standardjs.com) but doesn't configure it in ESLint. This causes new developers to either manually configure Standard or end up following their linter and submit problematic changes involving spaces, semicolons and the like.

**Reproduction**
Set up the repository in a fresh editor or IDE. Run code format. A number of code styling decisions that are aligned with Stardard will either show up as errors/warnings or worse, be _corrected_.

**Expected behavior**
The code, which complies with Standard should not change at all. The default ESLint setup should automatically inherit rules from Standard.

**Comment by sharmaadityaHQ** [comment]
Hello @dhruvkb . Can I take this issue?

**Comment by dhruvkb** [comment]
Sure @sharmaaditya570191, please go ahead.

**Comment by dhruvkb** [comment]
@sharmaaditya570191 as we discovered in creativecommons/vue-vocabulary#109, this was actually a problem with `npm` rather than with ESLint or Standard. Closing.
