### ISSUE TITLE
Change the hover state of inputs

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#240]
Across all pages, the input has a border color change during hover state. We should maintain the change for the active state.

### Expected design
<img width="521" alt="Screen Shot 2020-03-24 at 15 57 13" src="https://user-images.githubusercontent.com/895819/77585679-a4283d00-6ec3-11ea-99f1-c528db18827d.png">

**Comment by silvinabt87** [comment]
Hi! @panchovm @kgodey @dhruvkb I'd like to contribute here, if possible. I can't seem to access the screenshot uploaded and I'd like to check it out to make sure I understand the issue fully. Also, are there any extra details I should take into account?

**Comment by dhruvkb** [comment]
@panchovm I agree with @silvinabt87 that the screenshot seems to not have been uploaded correctly. Could you reupload it or add another one to the issue?

**Comment by fcoveram** [comment]
Ops! I justed updated the initial comment.
