### ISSUE TITLE
Change the text color for the default color of Vocabulary

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#242]
In different pages and sections, texts are `#2c3e50` when it should be `#333333`. Here some examples:

<img width="675" alt="Screen Shot 2020-03-24 at 15 59 37" src="https://user-images.githubusercontent.com/895819/77466136-9782e680-6de8-11ea-9ebb-2fc4fa52706e.png">
<img width="559" alt="Screen Shot 2020-03-24 at 15 59 25" src="https://user-images.githubusercontent.com/895819/77466146-9b166d80-6de8-11ea-8d4a-d3948777d50f.png">

**Comment by kushaggarwal** [comment]
If nobody is on this issue shall I raise a PR for same @kgodey 
Please help

**Comment by kushaggarwal** [comment]
I have updated the color on the homepage, about page and feedback page

**Comment by dhruvkb** [comment]
@kushaggarwal I've assigned you another issue. You can come back to this after resolving those.

**Comment by Tanuj22** [comment]
@dhruvkb Is this issue available?

**Comment by kushaggarwal** [comment]
Hello @dhruvkb as guided by you,
I am done with one issue and halfway through the other one so is it fine if I can proceed with this one too
Thank you

**Comment by SaurabhAgarwala** [comment]
> @Tanuj22 I'm moving this issue to Vocabulary, this issue needs to be fixed there.

@kgodey I tried looking for the relevant code to fix this issue in this repo, but couldn't find. Instead found the code to be fixed in the cccatalog-frontend repo only. I have fixed it there.

Please review it @panchovm @dhruvkb
