### ISSUE TITLE
Create icon combinations

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#244]
Some [icons in Figma](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A135) are used as combinations of [simpler icons from Fonts](https://cc-fonts.netlify.com/?path=/docs/vocabulary-icons--page). 

**Examples:**
<img width="66" alt="Screenshot 2020-03-25 at 11 57 54 PM" src="https://user-images.githubusercontent.com/16580576/77572129-74ddf400-6ef4-11ea-9ee6-c5a200c2e5da.png"> = `circle-filled` + `facebook`
<img width="66" alt="Screenshot 2020-03-26 at 12 01 09 AM" src="https://user-images.githubusercontent.com/16580576/77572396-e8800100-6ef4-11ea-91b2-f5be15a37a01.png"> = `circle-filled`:blue + `facebook`
<img width="66" alt="Screenshot 2020-03-25 at 11 56 50 PM" src="https://user-images.githubusercontent.com/16580576/77572033-4cee9080-6ef4-11ea-817b-c8707a586c64.png"> = `circle-outline` + `chevron-left`

The goal is to offer these combined and colored forms of the icons as direct to use markups to be used by other projects.

This is also related to #95.

**Comment by kgodey** [comment]
This blocks https://github.com/creativecommons/cccatalog-frontend/issues/801 and is urgent.

**Comment by kushaggarwal** [comment]
As I have understood here we want to update the icons styles in the figma design library where in we need to use the above icons styles as a whole and not as a combination of multiple ones
@dhruvkb please help if I have understood right

**Comment by megha070** [comment]
While updating the icons do we have to import them again in icomoon and get tff and woff the file for the same, or changing the background would suffice the purpose.

**Comment by megha070** [comment]
Do we have to create these icons using icomoon or we have to use a combination of two icons so as to get desired icon?

**Comment by silvinabt87** [comment]
Hi, @dhruvkb. I'd like to contribute here if the previous applicants are not assigned.

**Comment by dhruvkb** [comment]
Hi, I don't think the combined forms of the icon are available for free so IcoMoon will be of no help there. You will have to create them with HTML and CSS wizardry.

For example, the 'left-chevron-circle-outline' icon can have the following markup
```html
<div class="icon left-chevron-circle-outline">
<i class="icon circle-outline"></i>
<i class="icon chevron-left"></i>
</div>
```
and corresponding CSS to line up the chevron with the circle (hint: absolute position, transforms and Z-indices).

**Comment by dhruvkb** [comment]
Seeing growing interest on the issue, I'll recommend you each pick one icon.

**Comment by megha070** [comment]
We have to do stacking of icons, right?

**Comment by megha070** [comment]
I will take "left-chevron-circle-outline".

**Comment by silvinabt87** [comment]
I can take the blue Facebook icon @dhruvkb

**Comment by kushaggarwal** [comment]
Then I will take the one left

**Comment by dhruvkb** [comment]
There are a lot of them left! See the Figma link.

**Comment by kushaggarwal** [comment]
Okay @dhruvkb 
Thank you :)

**Comment by silvinabt87** [comment]
True! I'll start with the Facebook ones and when I'm done, I'll check the others.

**Comment by dhruvkb** [comment]
@silvinabt87 you should take all versions the Facebook logo.
@kushaggarwal you should take all versions of the Twitter logo.

**Comment by dhruvkb** [comment]
@Bob160 would you like to work on some?

**Comment by Bob160** [comment]
@Dhruvi16, sure. 
I'm in!

**Comment by Bob160** [comment]
@dhruvkb , I'll handle the Linkedin icon.

**Comment by dhruvkb** [comment]
@Bob160 start with Instagram. LinkedIn and Pinterest aren't in Fonts yet.

**Comment by Bob160** [comment]
@dhruvkb okay.

**Comment by arushivii** [comment]
any other icons left?

**Comment by dhruvkb** [comment]
@av-00 you can work on adding LinkedIn and Pinterest in `creativecommons/fonts`. There isn't an issue yet but you can open one and work on it if you'd like.

**Comment by silvinabt87** [comment]
@dhruvkb any further guidance on how to start to go about this issue?

**Comment by megha070** [comment]
I guess the prerequisite of this issue is #95 or do we have to implement these in creativecommons/fonts?

**Comment by dhruvkb** [comment]
@megha070 we're opting to not use the chevron-in-circle icon for now. I'm sorry but you should not invest further time into this.

@silvinabt87, @av-00, @kushaggarwal and @Bob160 could you please pause work on this issue? We're internally dicuss the specifics of how the icons will be sourced and combined and styled and we'll update the issue with the outcomes.

Heartfelt apologies to all of you for hastily opening the issue without thorough planning. I assure you this sort of thing won't happen in the future.

**Comment by silvinabt87** [comment]
No worries! Thanks for letting us know. I'll move on to some other issue for the time being.

**Comment by Bob160** [comment]
It's alright@Dhruvkb.

**Comment by kushaggarwal** [comment]
No worries @dhruvkb will continue with others in the meanwhile
