### ISSUE TITLE
Use GitHub Actions for CI

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#245]
**Description**
GitHub Actions offers a free and unlimited CI package for open source repositories with features rivalling and integrations surpassing those offered by CircleCI. The goal is to move our CI pipeline from CircleCI to GitHub Actions to run tests on all branches and pull requests.

**Problems solved**
Switching to a better CI provider leads to better productivity in the long run. Plus GitHub Actions has been setup across other CC repos and consistency is always good.

We might also in the end use this CI pipeline to deploy Vocabulary to `npm` using a modified `./deploy.sh` script everytime the version in `package.json` changes on the `master` branch.

Related to #121.

**Comment by megha070** [comment]
Do we have to refer to this?
https://help.github.com/en/actions/building-and-testing-code-with-continuous-integration/setting-up-continuous-integration-using-github-actions

**Comment by dhruvkb** [comment]
I'll just share the links @kgodey shared with me:
- https://github.com/features/actions
- https://github.com/creativecommons/ccos-scripts/issues/5
- https://github.com/creativecommons/cccatalog-api/issues/438

**Comment by krhitesh** [comment]
I am starting to work on this issue.

**Comment by megha070** [comment]
Hey @hitesh1157 , I have raised a PR for this, Kindly take any other issue.

**Comment by krhitesh** [comment]
Sure @megha070, I could do that but I am through writing code for the this issue and was in process of creating pull request. I know that you are a long term contributor for this project and therefore, would love to get constructive comments. This way we could learn a lot.

Even then if you are not okay with it, let @dhruvkb step in and decide. I hope that's okay with you.

**Comment by krhitesh** [comment]
@dhruvkb Could you provide one or two sample test cases for testing github actions workflow so that I get a brief idea on how to frame proper test cases.

**Comment by megha070** [comment]
No worries @hitesh1157 , It is a learning process, will surely get to learn more about Github actions through your valuable contributions.

**Comment by dhruvkb** [comment]
@hitesh1157 you are on the right track with your PR. As for the tests, you won't have to write any. Tests are written within the code itself and just running `npm run test` will be sufficient to run all the tests.

@megha070 raising PR is not enough for other contributors to not try solving an issue. The more solutions we get, the better the final outcome. You can still update your PR if there is an even better implementation that you can think of.

**Comment by dhruvkb** [comment]
Closed by #261.
