### ISSUE TITLE
Sync feedback color tokens with Figma 

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#251]
**Description**
There are [new feedback colors](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=437%3A55) in Figma. Add them to Vocabulary in `src/styles/color.scss`.

**Comment by megha070** [comment]
@dhruvkb all the colors are included in color.scss could you please elaborate on this issue.
![image](https://user-images.githubusercontent.com/40516822/77629488-99c37d00-6f6f-11ea-8a1f-39565f91186b.png)

**Comment by kushaggarwal** [comment]
If this issue is open I would like to go for it 
@dhruvkb can you please help as if what new colors are needed in `color.scss`

**Comment by megha070** [comment]
Extremely Sorry @kushaggarwal, raised a PR before reading your comment.

**Comment by kushaggarwal** [comment]
Okay @megha070  but it would be really helpful if you could just confirm for attending the issue before raising a pull request as I also worked it out and was about to link a pull request
Thank you

**Comment by megha070** [comment]
Will keep in mind.
