### ISSUE TITLE
 Update Docker Compose configuration file

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#26]
The [Docker Compose file](https://github.com/creativecommons/vocabulary/blob/master/Dockerfile) for the project, written in the initial days of the project has now gone out of sync with the capabilities and features of the project. The goal is to update the file in accordance with the current state and eventually push for it to the the standard development environment for the project.

**Comment by krhitesh** [comment]
I would like to work on this. @dhruvkb or @kgodey please remove **blocked** label from it as it is now moved to **Ready for Development**.

**Comment by dhruvkb** [comment]
@hitesh1157 please go ahead.
