### ISSUE TITLE
Update group IDs in logo SVGs

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#273]
**Description**
All the SVGs in `src/assets/logos/cc` have the same ID. This will eventually cause problems down the line when more than one of them are used on a page that [patches them into the DOM](https://cc-vocabulary.netlify.com/?path=/docs/vocabulary-usage--page#assets-1) as a workaround from hotlinking to CDN.

**Reproduction**
Copy the given HTML snippet and load more than one file from the folder. The second will override the first.

**Expected behavior**
Each should be patched and be usable indepently.

**Comment by jahnvigupta** [comment]
@dhruvkb I want to take this issue.

**Comment by dhruvkb** [comment]
@jahnvigupta we'll first wait for you to finish #165.

**Comment by kushaggarwal** [comment]
If it's open can I take this up @dhruvkb

**Comment by dhruvkb** [comment]
@kushaggarwal you take it. @jahnvigupta has like a dozen PRs already!

**Comment by silvinabt87** [comment]
@dhruvkb if @kushaggarwal doesn't work on this for any reason, I'd like to try.

**Comment by kushaggarwal** [comment]
Thanks @dhruvkb will attend to this

**Comment by kushaggarwal** [comment]
@dhruvkb  can you please help as if what would be the appropriate replacement for the id in this
I am currently thinking of replacing it with the current svg file names
current - creativecommons.   ->  lettermark , letterheart, logomark

**Comment by dhruvkb** [comment]
@kushaggarwal yeah that would be right. Also make sure to update the documentation accordingly.

**Comment by kushaggarwal** [comment]
Okay will do so Thank you
