### ISSUE TITLE
npm audit reveals huge no. of vulnerabilities

### ISSUE THREAD

**Issue by AroraShreshth** [cc-archive/vocabulary-legacy#277]
**Description**
npm run command for handling installations have revealed 
```
found 3275 vulnerabilities (3270 low, 5 moderate) in 1228231 scanned packages
  run `npm audit fix` to fix 3229 of them.
  46 vulnerabilities require manual review. See the full report for details.
```

**Reproduction**
npm install

**Expected behavior**

Even though there are no high level vulnerabilities but there are 3275 low vulnerabilties and 5 moderate

**Screenshots**

**Additional context**
There shouldn't be so many vulnerabilities and require immediate attention

**Comment by arushivii** [comment]
How can I start on this? Any leads?

**Comment by dhruvkb** [comment]
I'm not sure you're on the latest version @AroraShreshth, because I tried setting it up fresh and got only 44 low severity vulnerabilities as of commit 2de9af2.

```
added 2546 packages from 1243 contributors and audited 1050817 packages in 64.849s

126 packages are looking for funding
  run `npm fund` for details

found 44 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by dhruvkb** [comment]
I'm adding a label that says reproduction is required to ensure the validity of this issue.

**Comment by jahnvigupta** [comment]
@dhruvkb I agree, I also get 44.

**Comment by dhruvkb** [comment]
@AroraShreshth can you try a fresh setup and let me know so that we can decide how to proceed with this issue?
