### ISSUE TITLE
Perform reliability testing of visual regression tests

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#290]
**Description**
I don't have a lot of faith in visual regression tests, largely because [computers and eyes are different](https://storybook.js.org/docs/testing/automated-visual-testing/#challenges) in how they perceive pixels.

**Expected behavior**
The goal is to test the Vocabulary snapshot testing framework in many CI environments and with many different resolutions and so on, till we can say with certainty that screenshot comparisons are reliable.

**Comment by jahnvigupta** [comment]
@dhruvkb can i work on this.

**Comment by kushaggarwal** [comment]
@dhruvkb can you please help as I would like to work on this but not able to completely make out how to proceed

**Comment by dhruvkb** [comment]
With the use of Docker, it looks like visual regression tests are running reliably.
