### ISSUE TITLE
Create the notification component

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#293]
We need to add two notification components. Those can be found in the [new homepage design](https://www.figma.com/file/K6kbDVsx4Zpluhd52yEdDB/Mockup?node-id=212%3A234&viewport=145%2C25%2C0.12057308107614517) of .org site. The components have the following notes:

## Warning notification
Created to show warning messages. This component can be a link or not. The hover state can be seen found the default frame.

<img width="1127" alt="Screen Shot 2020-03-31 at 15 44 35" src="https://user-images.githubusercontent.com/895819/78063418-93197900-7366-11ea-8555-95f7480a56c0.png">

## Content notification
Created to show highlighted messages, i.e. events, pages, posts, and so on. This component can be a link or not. The hover state can be found below the default frame.

<img width="1096" alt="Screen Shot 2020-03-31 at 15 44 46" src="https://user-images.githubusercontent.com/895819/78063446-9a408700-7366-11ea-8b8e-5e8f3f49ccff.png">

**Comment by kushaggarwal** [comment]
If this issue is open I would like to work on it @panchovm @hugosolar @dhruvkb 
Please help
