### ISSUE TITLE
Vocabulary logo (top left) in storybook goes to Open Source 404

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#30]
**Description**
Within Vue Vocabulary Storybook, e.g. here:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/vocabulary-welcome--welcome

The top left logo is linked to https://creativecommons.github.io/vue-vocabulary which redirects to https://opensource.creativecommons.org/vue-vocabulary which is a 404.

The logo should instead just take users to the Vue Vocabulary Storybook welcome page:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/vocabulary-welcome--welcome

**Comment by annatuma** [comment]
@hugosolar and @dhruvkb heads up on this minor navigational detail. Perhaps Chidi can get this sorted?

**Comment by chidexebere** [comment]
I will take this up
