### ISSUE TITLE
Run visual regression tests inside CI

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#300]
**Description**
With visual regression tests running stably inside Docker, we can consider merging them into the CI pipeline with GitHub Actions.

**Problems solved**
Visual regression tests bring a lot of the errors happening in the course of the development to light, such as a change in element dimensions, textual content and even subtle changes in colors

**Comment by arushivii** [comment]
Can I work on this?

**Comment by kushaggarwal** [comment]
Hello @dhruvkb I would like to take this up

**Comment by yolande-prog** [comment]
hello @dhruvkb please can i take this?

**Comment by Nonye55** [comment]
I Will like to work on this

**Comment by dhruvkb** [comment]
@kushaggarwal @yolande-prog and @Nonye55 It's already assigned but if you have an interesting or fresh approach, please submit a PR.

**Comment by dhruvkb** [comment]
Do note that we are looking for a way to run these tests inside GitHub Actions and *not* in CircleCI.

**Comment by arushivii** [comment]
Hi @dhruvkb , sorry got busy. Any suggestions how to start on this?

**Comment by dhruvkb** [comment]
Look into GitHub Actions and how to run a Docker container inside an action. We need to run the Storybook server on the host and `npm run test:snapshot` inside the Puppeteer container.
