### ISSUE TITLE
Column layout of footer to match the design

### ISSUE THREAD

**Issue by hemanth-hk** [cc-archive/vocabulary-legacy#322]
**Description**
The design [Footer @ Figma](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=639%3A24) needs to match with the code/layout of the footer, presently I feel like it's not aligned completed with the design

**Alternatives**
I was working on an [issue](https://github.com/creativecommons/vue-vocabulary/issues/196) and this issue was noticed

---

![cc_footer](https://user-images.githubusercontent.com/43946715/79483588-1ce86800-8030-11ea-8e7e-a6fa8b0f6056.png)

In the above image the 1st box/design almost represents the column layout of the figma design.   
The 2nd one is the current layout which is present in the vocabulary now.   
The 3rd one is the layout which I am proposing.   

We can't go with the first one cause for the mobile devices the links will appear below the logo but the address and social media icons should appear. So I made the 3rd one which will be same as the present layout in the mobile devices and will match the design in the desktop resolutions

**Additional context**
I implemented my design to test things and this is what it looks like
![footer_demo_story](https://user-images.githubusercontent.com/43946715/79484513-5ff70b00-8031-11ea-8d94-4c7e1b77bcbb.png)
**Want to take up?**
Yes

**Comment by dhruvkb** [comment]
@hemanth-hk how did you come to the conclusion of what should appear in the mobile layout? There are no mockups for the mobile version.

**Comment by hemanth-hk** [comment]
The present version of the footer does that so I assumed that there should be address and social media links below the logo and it somehow makes sense that address should be below the logo right!!

**Comment by dhruvkb** [comment]
Out of the three box drawings, which is the current and which is the one that you think is correct?

**Comment by hemanth-hk** [comment]
The current is the 2nd one and to me, the 1st one/box is closest to the design and to be compatible with the present version of the footer I proposed the 3rd one which would be same as the 2nd one in mobile devices and would be pretty close to the design to desktop resolutions
