### ISSUE TITLE
Broken styles on Collections page in CC Search

### ISSUE THREAD

**Issue by brenoferreira** [cc-archive/vocabulary-legacy#325]
I loaded the latest code on `master` into CC Search, and I noticed that the Collections page now has some broken styles.

<img width="2157" alt="Screen Shot 2020-04-16 at 17 41 46" src="https://user-images.githubusercontent.com/707019/79504742-bd776180-8009-11ea-9f26-1e8688bab408.png">

The production build is still running on version 1.0.0-beta.9, and it looks fine

<img width="2141" alt="Screen Shot 2020-04-16 at 17 44 31" src="https://user-images.githubusercontent.com/707019/79504891-eef02d00-8009-11ea-85db-fcc0126f2edf.png">

There were no changes in the markup, so it seems like a bug in Vocabulary.

**Comment by dhruvkb** [comment]
Which component is that? Is it `Card`?

**Comment by krhitesh** [comment]
I would like to take on this issue.

**Comment by brenoferreira** [comment]
This is a blocker for https://github.com/creativecommons/cccatalog-frontend/pull/880

**Comment by brenoferreira** [comment]
@dhruvkb no. It doesn't use any vocabulary specific component. It just uses the margins, paddings and columns. Not sure what the problem is yet.

**Comment by brenoferreira** [comment]
Found the problem. The column margins are looking a bit weird because of the change in `$column-gap` https://github.com/creativecommons/vocabulary/pull/307/files#diff-9263db093c4df1fd69fbf0a30ac0a866R2

I'll take a look at this and see if the fix should be here or on the frontend
