### ISSUE TITLE
Card snapshots are flaky because of large images

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#327]
**Description**
Visual regression testing on cards is made complicated by the large images in use. This can be improved drastically by using simpler placeholders like [this](https://via.placeholder.com/500/333333/f5f5f5/?text=Vocabulary).

**Reproduction**
Run the card tests a few times in succession. They sometimes pass, sometimes fail.

**Expected behavior**
The tests should consistently pass (or in the very least, consistently fail).

**Comment by jahnvigupta** [comment]
@dhruvkb I want to take this.

**Comment by Bob160** [comment]
Hi @dhruvkb  can I take up this issue?

**Comment by Bob160** [comment]
Hi @dhruvkb , to reproduce this issue, the instruction says to run the card test a few times. Can you please provide guidance on how to solve this issue?

**Comment by dhruvkb** [comment]
The instructions on running the visual regression tests are [here](https://cc-vocabulary.netlify.app/?path=/docs/vocabulary-contribution--page#visual-regression). HMU on Slack if you need anything.

**Comment by Dishebh** [comment]
@dhruvkb I would like to work on the issue. Can you pls assign it to me?

**Comment by dhruvkb** [comment]
Reassigned because of inactivity.

**Comment by Dishebh** [comment]
@dhruvkb I am trying to run the current tests for `Cards` (`jest run card.test.js`), but neither of the tests written in `card.test.js` is passing, throwing error:
`ReferenceError: page is not defined`
I tried re-installing `jest-puppeteer` and re-running the tests, but the error still holds. Can you pls help me identify with why that error is showing up and / or where I am going wrong? Thanks!

**Comment by dhruvkb** [comment]
@Dishebh are you running the tests from inside Docker as [instructed here](https://cc-vocabulary.netlify.app/?path=/docs/vocabulary-contribution--page#testing)?

**Comment by kgodey** [comment]
We're not doing snapshot tests, closing this.
