### ISSUE TITLE
Reduce screenshot area in snapshot tests

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#328]
Since the viewport for snapshot tests is set to 1920px &times; 1080px &times; 2dpi each snapshot comes out to be a bitmap image of 3840px &times; 2160px. These images are too huge
- to store in the repository and track changes over time
- to compare in every run of the test

With most of the space being blank white anyways, it seems like a huge waste of storage and computing power to run these tests. A simpler way would be to just screenshot the node instead of the whole viewport.

Better approach: [Element screenshot](https://pptr.dev/#?product=Puppeteer&version=v3.0.0&show=api-elementhandlescreenshotoptions)

Current approach: [Page screenshot](https://pptr.dev/#?product=Puppeteer&version=v3.0.0&show=api-pagescreenshotoptions)

**Comment by megha070** [comment]
I would like to take this up.
