### ISSUE TITLE
Snapshots can sometimes misbehave due to loading times

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#329]
**Description**
A page with images can look different if the snapshot is taken before all images have loaded. A page with fonts may look different depending on whether the snapshot was taken before or after the fonts were applied. These uncertainties in the timing can lead to false outcomes in the test results.

Using the [right `waitUntil` values](https://pptr.dev/#?product=Puppeteer&version=v3.0.0&show=api-pagegotourl-options) can, for the most part, resolve this issue.

**Reproduction**
Since these are unpredictable and random events, it's hard to reproduce them. But run enough tests and they will present themselves.

**Expected behavior**
The tests should consistently pass (or in the very least, consistently fail).

**Comment by jahnvigupta** [comment]
@dhruvkb I want to take this.

**Comment by aryamanpuri** [comment]
Are you still working on this issue @jahnvigupta 
If no @hugosolar @dhruvkb  Can I give this a try ?

**Comment by kgodey** [comment]
We're not doing snapshot testing any more, closing this.
