### ISSUE TITLE
Fix broken tests and re-enable them

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#330]
**Description**
Presently the card and header tests have been de-activated by changing the name from `.test.js` to `.test.js.x`. This is because the card tests are flaky (#327) and because there is an inexplicable error in the header test. The goal is to fix both test suites, update code, styling and snapshots as required and make them pass.

**Reproduction**
Re-enable the tests and run on GitHub Actions.

**Expected behavior**
Tests should pass.

**Comment by arushivii** [comment]
Can i take this?

**Comment by arushivii** [comment]
How to run on actions? how do i test them?

**Comment by dhruvkb** [comment]
@av-00 GitHub Actions will automatically run on your PR. You can however run the tests by following the [contribution instructions](https://cc-vocabulary.netlify.app/?path=/docs/vocabulary-contribution--page) in the Storybook.

**Comment by arushivii** [comment]
![Screenshot from 2020-04-28 18-52-08](https://user-images.githubusercontent.com/43967251/80492268-6797a780-8981-11ea-83a0-d122543c6c91.png)
Can you please explain the difference between tests passed and snapshots passed as mentioned?

**Comment by dhruvkb** [comment]
Each test suite contains multiple tests. Each of these tests is associated with a single snapshot. So the number of passing tests will equal the number of passing snapshots.

**Comment by Cronus1007** [comment]
@dhruvkb Shall I implement this one?

**Comment by dhruvkb** [comment]
@Cronus1007 we are currently not enabling visual regression testing on our apps because of large dev overhead.

**Comment by Cronus1007** [comment]
@dhruvkb  So shall I close this PR #847

**Comment by Lovelynchristian** [comment]
I would love this to be assigned to me please

**Comment by brylie** [comment]
Thanks, @Lovelynchristian! I've assigned you to the issue :smile:

**Comment by Lovelynchristian** [comment]
Great! Thanks

**Comment by Lovelynchristian** [comment]
Good evening @brylie , I'm having issues installing Docker on my mac and windows. Please i need your assistance. Thanks.

**Comment by brylie** [comment]
@Lovelynchristian, Docker isn't required for Vocabulary development. All that is needed are Node and npm. Please follow the [Vocabulary installation instructions](https://github.com/creativecommons/vocabulary#installation) to get started with development.

**Comment by Lovelynchristian** [comment]
@brylie Thank you.

**Comment by Lovelynchristian** [comment]
Hi @brylie , trust you're doing great. 
In trying to replicate this issue on my local machine, I've been able to install all necessary dependencies and run the unit test within the unit directory. It took me sometime to locate the header.test.js file eventually i found out that the current version of the main branch does not have this file. How do i get a version of a branch that has all the necessary files for me to fix this issue?

**Comment by brylie** [comment]
@dhruvkb, are you able to assist @Lovelynchristian with their question?

**Comment by dhruvkb** [comment]
@Lovelynchristian this file was likely removed during the restructuring. You can get that file from an older commit. [Here](https://github.com/creativecommons/vocabulary/blob/5e7f4331d62267a4332da2ca484d29b0575e6007/packages/vocabulary/tests/snapshot/header.test.js.x) it is.

**Comment by Lovelynchristian** [comment]
@dhruvkb Thank you.

**Comment by Lovelynchristian** [comment]
@dhruvkb, Thanks once again.

However, I still am not able to replicate the broken issue, on the latest version of the vocabulary repo. All test seems to pass with no failures. I was also able to get the test.js.x file as mentioned. It does not seem to impact the current version from my findings. 

Kindly assist. I will like to first replicate the issue.

**Comment by Lovelynchristian** [comment]
@brylie Please i would appreciate your assistance .I would need response to my question. Thankyou.

**Comment by brylie** [comment]
@Lovelynchristian it would help if I could try out the changes you have made. Would you open a pull request with the changes you have tried so I can review them?

**Comment by possumbilities** [comment]
This project is moving towards being archived, and this item is no longer on the roadmap. Closing
