### ISSUE TITLE
Figure a way to get diffs for failing snapshots from GitHub CI

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#332]
**Description**
GitHub Actions offers the concept of artefacts that can be downloaded or uploaded to pass data into or out of the CI pipeline. Using these artefacts once can get the failing snapshots (the `_diff_snapshots__` directory) to be examined if the CI job has failed.

**Problems solved**
While the job output lists the components that failed the test, it's not nearly enough. Seeing the actual difference in the component via the diff images helps to pinpoint the exact nature of the change.

**Comment by jahnvigupta** [comment]
@dhruvkb I want to take this issue.

**Comment by brylie** [comment]
I believe we could resolve this issue by running the tests locally to reproduce the failure.
