### ISSUE TITLE
Update the description in Footer

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#334]
We need to update the description text in Footer, below the subscription section. The text should say at the end: **Icons by Font Awesome.**

[Link to Figma component](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=639%3A185&viewport=-454%2C233%2C0.514668345451355)

**Comment by dhruvkb** [comment]
This can be resolved in pairing with #339.
