### ISSUE TITLE
To include new social share icons for the ccsearch frontend

### ISSUE THREAD

**Issue by DantrazTrev** [cc-archive/vocabulary-legacy#344]
**Description**
To include new social share options to increase the share-ability of images and being easy for a wider audience.
The proposed share options will include
Tumblr , image boards ( that can be discussed ). Also Instagram could be a viable option

**Problems solved**
To include social media share options icons to be used in the sites 

**Additional context**

> @DantrazTrev you're welcome to propose a change to the Share tab. Please let us know which icons specifically you'd want to include. Please make use of FontAwesome icons, as that's what we'll be using on CC Search.
>
> Before this change can be implemented on CC Search, however, we'll need to add the additional social media icons into Vocabulary. @DantrazTrev please create a ticket for that and work on it before this one. Please comment on this ticket to confirm the ticket you've created in Vocabulary, so workflow can be tracked. This ticket will remain **blocked** until the Vocabulary ticket work is complete.
>
>Separately - it is possible we don't need these in the Design Library, since they are FontAwesome, but @panchovm and I will review that.

_Originally posted by @annatuma in https://github.com/creativecommons/cccatalog-frontend/issues/728#issuecomment-598381960_

**Comment by dhruvkb** [comment]
@DantrazTrev if you just want to include more social media websites, please name them and if possible, justify how adding them would add value. If you're proposing a redesign of the Share tab, adding hand-drawn or Figma mockups would help.

I'm assigning this to @panchovm and @annatuma as it seems they are yet to review if the icons should be in the Design Library.

**Comment by DantrazTrev** [comment]
I think including a few more sites or mediums would make it more accessible and better for the widespread users, 
Here are a few suggestions with the reasonable explanation and queries

1. Messaging services such as iMessage and WhatsApp . Considering the popularity of the services and the link sharing features , it would be reasonable to include these , further considering these are used to share images and info mostly formally and informally. 

2. Social media sites like Tumblr and possibly Instagram (not much suggested due lack of link sharing features ) can be included appealing the users who are mostly working creative content development on such sites could be useful

3. image boards and Forums , A popular example would be considered like reddit and an option of various popular image boards if needed (although this point could be discussed )

Further an link sharing feature that would allow us to integrate it more popular but less conventional sharing platforms such as instant messaging and email services 

Further other used messaging services and more options could be placed in a 3 dot style dropdown menu ,  making it more easier and allowing enough whitespace to be rendered on smaller screens

**Comment by Dishebh** [comment]
@DantrazTrev @dhruvkb I would like to work on it, add more social media icons, if we are moving forward with the issue.

**Comment by dhruvkb** [comment]
@Dishebh I'm not really sure if we're proceeding with it. @DantrazTrev's argument is compelling but we don't have our main man @panchovm's feedback on this so far.

**Comment by fcoveram** [comment]
We are aware and agree with adding more sharing options, but our roadmap might include this feature in future implementations. Let me check with @annatuma how this fits.

**Comment by annatuma** [comment]
As next steps, we have a list of certain platforms/services that we will include in this round. Currently we have 200-300 users per month making use of the Share feature. (In comparison, we have over 10x the user for our Attribution feature). Therefore we'd prefer to iterate, versus building out an extensive list at this time.

To be added:
iMessage
WhatsApp
Messenger (from Facebook)
Tumblr
Reddit

We can revisit stats a few months after these, and if use of the feature has increased we can continue to iterate.

@panchovm will add these to the Design Library. Once they've been added, we will unassign this ticket, mark for contribution, and it will be ready for work.

**Comment by fcoveram** [comment]
Fontawesome has not icon for iMessage, but since iMessage is an app for SMS messages, I will add a general SMS icon.

**Comment by fcoveram** [comment]
[The Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A135&viewport=45%2C155%2C1.0786082744598389) has been updated with the platforms mentioned above.

**Comment by Dishebh** [comment]
@panchovm shall I update the `/tokens-icons-figma` part of the vocabulary with the new social icons added?

**Comment by fcoveram** [comment]
@Dishebh, let me tag @dhruvkb for a correct response.

**Comment by dhruvkb** [comment]
@Dishebh the icons are present in `@creativecommons/fonts`. Please address this issue on that repository.

**Comment by kgodey** [comment]
All these are in Fonts already, except for Medium, which has its own issue and an open PR, so I'm closing this.
