### ISSUE TITLE
CD Workflow failing

### ISSUE THREAD

**Issue by SaurabhAgarwala** [cc-archive/vocabulary-legacy#349]
**Description**
The CD workflow present in this repo which is based on the official GitHub Actions documentation is failing when a new release is published with the following error:
`npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/@creativecommons%2fvocabulary - You must be logged in to publish packages.`
On searching the web for the possible reasons for this error, I found that since there are two package repositories, namely `npm` and `GitHub Packages` available, and also since Vocabulary is a scoped package, so both the `registry-url` and `scope` has to be explicitly specified in the workflow.

**Reproduction**

The error can be observed by visiting [this link.](https://github.com/creativecommons/fonts/runs/622557954?check_suite_focus=true#step:5:197)

**Expected behavior**

The workflow shouldn't fail.

**Additional context**

The problem may be resolved by specifying the `registry-url` and the `scope` in the workflow.

**Want to take up?**

Yes

**Comment by brenoferreira** [comment]
I think the env key has to be in the same scope of the deploy job https://sergiodxa.com/articles/github-actions-npm-publish/

**Comment by SaurabhAgarwala** [comment]
@brenoferreira The way the environment variable has been currently defined makes it available for the entire workflow and is available to all jobs and steps in the workflow as documented [here](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#env). But if you want, I can try setting the env key in the same scope of the deploy job as well.

**Comment by SaurabhAgarwala** [comment]
@brenoferreira Any updates on how we shall proceed on this now?

**Comment by brenoferreira** [comment]
@SaurabhAgarwala you can try that and see if it fixes it. I'm still not too familiar with GH Actions. I posted that link because it's one thing I noticed that's different and could point to the problem

**Comment by SaurabhAgarwala** [comment]
Okay, I will make a PR with the proposed changes and then we can see how it works.
