### ISSUE TITLE
Determine Negative/Positive/Probably Ranges & Add to Figma DL

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#35]
**Description**
We need to:
1. Review the currently named Negative/Positive/Probably colors in Vocabulary:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/tokens-colors--contexts
(Note, they will be moved to "Functional" shortly, so the link may change).
2. Determine which gradients of each color we will keep (currently 10, should be 3).
3. Add those colors to Figma DL
4. Create a ticket to "Remove unnecessary gradients of select Functional colors", assign to Breno.

**Comment by fcoveram** [comment]
After trying the colors in feedback messages, I decided to keep one green gradient for success feedback. However, errors and warnings color have changed. This because of accessibility contrast check and color saturation.

**Comment by fcoveram** [comment]
The three final colors meet the AAA accessibility contrast.
