### ISSUE TITLE
Extra padding in the Rich Content Table.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#358]
**Description**

Comparing the Figma design and the story, there seems to exist extra padding in the first column of the Rich Content table.

**Reproduction**

![image](https://user-images.githubusercontent.com/34674462/80913331-7b685280-8d61-11ea-89de-cbb0755ee35c.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/34674462/80913356-9cc93e80-8d61-11ea-9f05-9d5fdcfd761b.png)

**Conditions:**

 - OS: [Ubuntu 16.04]
 - Browser [Mozilla Firefox]
 - Version [75.0]

**Want to take up?**

[Yes]

**Comment by bigdevlarry** [comment]
Hi @Dhruvi16 looking to contribute as a first timer if the issue is still open ... I will be willing to work on it

**Comment by dhruvkb** [comment]
By all means @LarrySul, go ahead! 🚀

**Comment by bigdevlarry** [comment]
@Dhruvi16 @dhruvkb Done with the assigned task ✔✔

**Comment by dhruvkb** [comment]
@LarrySul while your PR is being reviewed, you can freely pick and work on another issue.
