### ISSUE TITLE
Update the logos of products

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#360]
We need to update the following product's logos:
1. Open Source
2. Chooser
3. Search
4. Global Network
5. Global Summit
6. State of the Commons
7. Certificates
8. Vocabulary

The SVG files can be exported from [the Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=784%3A0&viewport=252%2C-29%2C0.8688915371894836)

**Comment by kushaggarwal** [comment]
Hello,
I would like to take this up @dhruvkb @hugosolar if its still open 
Thanks

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
There are certain logos with different colors and styles like that of CC Certificates in the current set of product logos
So, can you please help as if how to proceed for the same
Thank you

**Comment by dhruvkb** [comment]
@kushaggarwal update all the logos to the new ones, removing all extraneous styles and variants.

**Comment by dhruvkb** [comment]
@panchovm the new logos are superb. I just gotta say, each character is its own path, ordered by the position of the letter in the word, there is no bloat metadata and the heights are all exactly equal. Beautiful!
