### ISSUE TITLE
Update alignment of Donate section in Footer in Vocabulary

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#361]
The footer in Vocabulary no longer matches the [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=639%3A24). We need to center align the Donate section.

Note, there are two other open tickets related to the Footer right now, one regarding social media icons and another regarding the description.

**Comment by hemanth-hk** [comment]
@annatuma Please see #323, I'll update the snapshot tests but I think the column layout matches with the design!

**Comment by grininja** [comment]
I want to work on this project

**Comment by bigdevlarry** [comment]
Hi @annatuma is this issue still open ? Looking to contribute to vocabulary as a first timer ...

**Comment by dhruvkb** [comment]
@LarrySul actually we have all the code submissions needed to close it, it's only a matter of reviewing and merging. I'd encourage you to try another issue.

**Comment by krysal** [comment]
This is solved by @hemanth-hk's works and PR #450, so this can be closed.

**Comment by dhruvkb** [comment]
Confirmed as fixed. Closing.
