### ISSUE TITLE
Alerts in Components

### ISSUE THREAD

**Issue by nitin10s** [cc-archive/vocabulary-legacy#363]
**Description**
Alerts are an important part of a platform and user experience that helps maintain consistency. Currently, the Vocabulary doesn't contain any components for Alerts.

**Problems solved**
Alerts should be added to the Vocabulary section

**Want to take up?**

Yes, I would like to add the documentation and Figma file but I would require support from the team that writes the documentation and creates Figma files, so as to streamline and understand the process.

**Comment by dhruvkb** [comment]
New component suggestions should be reviewed by @panchovm and will only be developed if green-lit.

**Comment by fakela** [comment]
I would love to work on the documentation for this if this component is approved

**Comment by fcoveram** [comment]
I agree with the problem description. However, we are adding components to Figma while we need them. For now, we haven't faced a situation to add it.

**Comment by nitin10s** [comment]
Yes, I was thinking this might be the case, on one hand, these are the basic components that design systems should ideally consist, for when the need arises, guidelines for all the basic components is present, on the other hand, the Vocabulary guide clearly states, if it doesn't have a use case already, don't add it. 

I would prefer the former because design systems should offer all the guidelines beforehand rather than adding them whenever the need arises.

**Comment by nitin10s** [comment]
Let me know what do you think, I observed some more basic components are missing. I would open more issues in case you guys decide to add them. @panchovm @annatuma

**Comment by fcoveram** [comment]
We are aware that more basic components are needed. But we will add them when we will have a specific page to work on. Thanks

**Comment by dhruvkb** [comment]
@nitin10s we need to consider the following points:
- **We are designing Vocabulary with an incredibly lean scope.**
  It's meant to style just CC sites, not be a general purpose design system like Material Design or Bootstrap or Bulma (which is a dependency of the project itself).
- **We are on a stringent timeline.**
  Designing components that have no immediate need puts the ability to deliver on time in jeopardy and delays designs that are more urgently needed.
- **We are a very small team.**
  The cost of maintenance and documentation that comes with superfluous components is hard to justify when only a couple of people are working on it full-time.
- **As for having all guidelines beforehand, we do already do that.** 
As soon as the first need for a component arises, we develop the full-fledged guidelines for it with all possible use cases for it.

It's not just alerts, there are many other components like progress bars or toasts or pagination or spinners that we don't have. But we can't create them until a site needs them.
