### ISSUE TITLE
Add a List component

### ISSUE THREAD

**Issue by rajat2502** [cc-archive/vocabulary-legacy#364]
**Description**

A List component should be added to the design system 

**Problems solved**

Uniformity in design.

**Additional context**

![image](https://user-images.githubusercontent.com/42200276/81831417-f21fff80-955a-11ea-82dc-90fb4ac389f6.png)
Lists like these are used everywhere on the website and it would be good if we have a component for that.

**Want to take up?**

Yes.

**Comment by jahnvigupta** [comment]
We already have design for font, I think it's better if we go for design of bullets.

**Comment by rajat2502** [comment]
@jahnvigupta Yeah I meant the same...sorry if it sounded the other way.

**Comment by dhruvkb** [comment]
Although I personally feel a lists component would be redundant, given that `ol` and `ul` work perfectly fine, I'll still let @panchovm decide which component requests need to be implemented.

**Comment by fcoveram** [comment]
I agree with @dhruvkb. It is redundant and `ol` and `ul` are enough.

**Comment by dhruvkb** [comment]
@panchovm do we need to have specific colors like the orange used in the `ul` bullets?

**Comment by fcoveram** [comment]
We might have color depending on the website. For now, we are using one of the gray shades

**Comment by dhruvkb** [comment]
Closing as we don't need colored or styled bullets for now.
