### ISSUE TITLE
Add Contributing and Usage guide to the README

### ISSUE THREAD

**Issue by rajat2502** [cc-archive/vocabulary-legacy#365]
The guides for `contribution` and `usage` should also be there on the `README.md` of the project. I think it's better to add the content there then just links.

**Comment by dhruvkb** [comment]
@rajat2502 the main problem with that is that we will need to sync changes in two places. It's better to have a single source for all documentation, and that includes guides.

**Comment by dhruvkb** [comment]
I'm closing the issue till you can...
![download](https://user-images.githubusercontent.com/16580576/81852223-500f1000-9578-11ea-9c39-a7aef1ef3517.jpeg)

**Comment by rajat2502** [comment]
> @rajat2502 the main problem with that is that we will need to sync changes in two places. It's better to have a single source for all documentation, and that includes guides.

Yeah, I agree on that but we could remove the docs from the website/storybook and keep them here in the README section, or maybe just add the contributing guides to the repository because that's the first thing anyone would think of after viewing the repository.

**Comment by fakela** [comment]
@rajat2502 I agree to your point

**Comment by dhruvkb** [comment]
@rajat2502 they're pretty long and detailed. Even @fakela in their PR pasted a small portion and lined to the Storybook for the full docs. But there's no harm in having a discussion on it. It's Season of Docs after all, so all docs are up for change.

**Comment by rajat2502** [comment]
Okay, agreed! I feel there is not much need for the contributing guidelines on the storybook. I mean that's something meant for the repository. If not in the readme maybe we can add them to the contributing.md file.

**Comment by fakela** [comment]
@dhruvkb  @rajat2502 we can always have a discussion on a better approach for this.

**Comment by rajat2502** [comment]
@dhruvkb So, should I make another issue for moving the contributing guidelines to the markdown files?

**Comment by dhruvkb** [comment]
Still deliberating on it. I'm still on the fence about putting in that effort. @rajat2502 are the instructions hard to find in the Storybook?

**Comment by fakela** [comment]
Not exactly but it's always easier when approaching the project few
important details are present in the readme then for more detailed
explanation the user can move to the story book

**Comment by rajat2502** [comment]
> Still deliberating on it. I'm still on the fence about putting in that effort. @rajat2502 are the instructions hard to find in the Storybook?

It's not hard to find them, but in a normal production app that is open source they just provide you the link to the repository and all the guidelines related to contributions, best practices are listed there on the repository.

**Comment by dhruvkb** [comment]
I'll tag some other developers for their inputs as well. @hugosolar and @brenoferreira would you have some comments?
