### ISSUE TITLE
The tab component doesn't follow the style defined in the Design Library

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#369]
## Describe the bug
The active and inactive states of the tab component don't follow the style defined in the Design Library.
<img width="521" alt="Screen Shot 2020-05-14 at 11 42 05" src="https://user-images.githubusercontent.com/895819/81955525-330a2980-95d8-11ea-9512-f1722782feff.png">

## Expected behavior
The active and inactive states have a different line weight and size, without padding. See the [mockup in Figma (Mockup S3)](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=205%3A60&viewport=6496%2C3630%2C1).

**Comment by Tanuj22** [comment]
@dhruvkb Can I take this?

**Comment by Dishebh** [comment]
@panchovm I would like to work on this.
