### ISSUE TITLE
Color Usage Guidelines Work

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#37]
**Description**
We need to:
1. Complete Color Usage Guidelines in Figma LT
2. Transfer to Color page in Figma DL
3. Create ticket for Breno to update the Color page in Vocabulary to include the newly added documentation. _We will try to have the Vocabulary page reflect Figma as closely as possible, exact outcome TBD._

**Comment by fcoveram** [comment]
The **Color page** has been transferred to DL. I will put a note on the new ticket that **Interaction colors** are in review based on the second work session's outcomes.
