### ISSUE TITLE
Text buttons don't follow the Figma designs

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#370]
## Describe the bug
1. The label "report this content" uses a different text style
2. During hover state, it moves slightly to the right.
3. During hover state, it should show an underline in the label.
4. It doesn't have the 8px spacing parameter to separate it from the above paragraph.

<img width="357" alt="Screen Shot 2020-05-14 at 11 47 05" src="https://user-images.githubusercontent.com/895819/81956138-f428a380-95d8-11ea-88b9-199b4ba2b3c5.png">

## Expected behavior
Use the correct hover style and interaction, the text style, and adding a spacing parameter. See the mockup in [Figma (mockup S3)](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=205%3A60&viewport=6496%2C3630%2C1).

**Comment by brenoferreira** [comment]
This is an issue with `.is-text` buttons

**Comment by Dishebh** [comment]
@panchovm I would like to work on this. Can you assign it to me?

**Comment by zackkrida** [comment]
FYI point 2 is fixed by #496

**Comment by zackkrida** [comment]
I would also note that the `.is-text` buttons specifically need `background: transparent` set otherwise they can inherit the default bulma button background color when they are hovered.
