### ISSUE TITLE
Hover state of default link

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#371]
## Describe the bug
The hover state of default links it shows a different style than defined as general interaction. This occurs in all default (tomato) links.
<img width="472" alt="Screen Shot 2020-05-14 at 12 06 54" src="https://user-images.githubusercontent.com/895819/81958082-74500880-95db-11ea-92d5-ca4ed0642f4a.png">

## Expected behavior
It should show an orange underline

**Comment by Dishebh** [comment]
@panchovm shall I work on this?

**Comment by Dishebh** [comment]
@panchovm can you please share the link where I can find the attached screenshot in the issue description? Thanks!

**Comment by fcoveram** [comment]
@Dishebh that bug appears often on the single result page. That example is part of the attribution toolbox, present in every single result page.

**Comment by Dishebh** [comment]
> @Dishebh that bug appears often on the single result page. That example is part of the attribution toolbox, present in every single result page.

I have opened a pr for the issue. Let me know if the changes done are fine.

**Comment by dhruvkb** [comment]
@panchovm do we want the text to become black on hovering? By default link underlines have the same color as the text and the cause of the black underline is actually the link text itself turning black on hover.

**Comment by fcoveram** [comment]
During hover, we want the text in the same color, just adding an underline.
