### ISSUE TITLE
Text style and icon size are incorrect in Header component

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#374]
**Description**
The text style and its hover state, and the icon size don't follow the Design Library definition.

**Expected behavior**
1. Text style should be font-size 16px, line-height 24px and letter spacing 2%.
2. During hover state, the text color changes from `DarkGray` to `DarkSlateGray` without an underline. 
3. The icon size should be within 15px square.
See the example in [the Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=591%3A0&viewport=-298%2C-40%2C0.3940659165382385).

**Screenshots**
<img width="1288" alt="Screen Shot 2020-05-14 at 13 21 07" src="https://user-images.githubusercontent.com/895819/81965554-386e7080-95e6-11ea-8eff-cc2a17ae2e1d.png">

**Comment by bigdevlarry** [comment]
Hi @panchovm is anyone working on the issue yet ? I'm open to picking it up  ...

**Comment by dhruvkb** [comment]
@LarrySul you can definitely pick it up as no one else has asked to.
