### ISSUE TITLE
Don't let the title in the image component to flow on multiple lines

### ISSUE THREAD

**Issue by makkoncept** [cc-archive/vocabulary-legacy#375]
**Description**
If the title of the image is long enough, then it is displayed on multiple lines. This would not look very aesthetic for the images that are narrow and short.

**Alternatives**
One alternative is to change the [text-overflow](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) to _ellipsis_. Also, the _title_ attribute of the HTML element can be set so that the user can see the full title in the tooltip when they hover over it.

**Additional context**
This would be particularly beneficial for cc-search extension because it is more likely to face this problem. This fix would prevent some ugly vocabulary rules overriding on the extension.

**Screenshots**

![Screenshot from 2020-05-15 00-01-08](https://user-images.githubusercontent.com/34679965/81977892-58368080-9648-11ea-9284-49c0db7b0ed4.png)
![Screenshot from 2020-05-14 23-58-05](https://user-images.githubusercontent.com/34679965/81977916-5f5d8e80-9648-11ea-85cf-50d051ff48ee.png)

**Want to take up?**

No

**Comment by bigdevlarry** [comment]
Hi @makkoncept I can take this up .

**Comment by makkoncept** [comment]
No one seems to be working on this, therefore you can take this up. Tagging @dhruvkb for confirmation.

**Comment by bigdevlarry** [comment]
Alright

**Comment by bigdevlarry** [comment]
Fixed the issue. 
I made use of style attribute text-overflow and set value to ellipsis. 
PR #368..
![image stories](https://user-images.githubusercontent.com/29729601/82007818-1c5ce480-9663-11ea-997e-4696b45ebb90.JPG)

**Comment by dhruvkb** [comment]
@LarrySul sorry for the delay, please go ahead and open a PR.

**Comment by dhruvkb** [comment]
@makkoncept you can now add the `is-ellipsised` class on the title to limit text to one line with ellipsis, but it will still reveal the full text on hover, serving your purposes.
