### ISSUE TITLE
Add a TextArea component

### ISSUE THREAD

**Issue by rajat2502** [cc-archive/vocabulary-legacy#376]
**Description**

A `TextArea` component can be added to the `vocabulary` as it is used many times on the websites.

**Problems solved**

Consistent design over all the websites.

**Additional context**

![image](https://user-images.githubusercontent.com/42200276/81978689-82d50900-9649-11ea-9d1f-4b740e197395.png)

**Want to take up?**

[Yes]

**Comment by dhruvkb** [comment]
@panchovm, we would need your inputs here.

**Comment by fcoveram** [comment]
We are using `textareas` in different sites, if that can be used as a component, then it makes sense to create it. [CC Search](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=199%3A354&viewport=1170%2C-6623%2C1.246282696723938) has a style for this element. Please follow it.

### Screenshot
<img width="454" alt="Screen Shot 2020-05-15 at 09 24 21" src="https://user-images.githubusercontent.com/895819/82055018-e08b4480-968d-11ea-9e82-dba19352bd40.png">

**Comment by fcoveram** [comment]
Meanwhile, I will add the component to the Design Library. I'm thinking to add it into the **Form** page, what do you think @dhruvkb ?

**Comment by rajat2502** [comment]
> [CC Search](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=199%3A354&viewport=1170%2C-6623%2C1.246282696723938) has a style for this element. Please follow it.
Sure I will make a PR for it.

**Comment by fcoveram** [comment]
⚠️ Something important I did not put in the design, we need to consider the three diagonal lines that allow changing the text-area' size.

**Comment by dhruvkb** [comment]
> Meanwhile, I will add the component to the Design Library. I'm thinking to add it into the **Form** page, what do you think @dhruvkb ?

I agree that this belongs in the Form section. 



> ⚠️ Something important I did not put in the design, we need to consider the three diagonal lines that allow changing the text-area' size.

Those three lines are determined by the browser. Some browsers show three diagonal lines, some show a small triangle and some don't have it at all. It's not customisable via CSS.
