### ISSUE TITLE
address tag inside p in footer

### ISSUE THREAD

**Issue by heraldofsolace** [cc-archive/vocabulary-legacy#387]
**Description**
While working on https://github.com/creativecommons/chooser/issues/161 I came across this problem.
Currently the storybook for footer contains this following code - 

```
 <p>
    <address class="margin-bottom-normal"> Creative Commons <br> PO Box 1866, Mountain View CA 94042</address>
    <a href="mailto:info@creativecommons.org" class="mail">info@creativecommons.org</a>
    <a href="tel://+1-415-429-6753" class="phone">+1-415-429-6753</a>
</p>
```
However, according to the [Official HTML spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element) 

> A p element's end tag can be omitted if the p element is immediately followed by an address, article, aside, blockquote, details, div, dl, fieldset, figcaption, figure, footer, form, h1, h2, h3, h4, h5, h6, header, hgroup, hr, main, menu, nav, ol, p, pre, section, table, or ul element, or if there is no more content in the parent element and the parent element is an HTML element that is not an a, audio, del, ins, map, noscript, or video element, or an autonomous custom element.

This causes the `p` tag to close immediately, for example when used with Vue lint. I believe this is also causing the render error in the storybook.

**Reproduction**
Include the code in a Vue JS file and run `vue-cli-service lint`. This closed the `<p>` tag and reports `error: Parsing error: x-invalid-end-tag (vue/no-parsing-error)`

**Expected behavior**
The code should compile correctly.

**Screenshots**

This is the screenshot from the stroybook when you click on "show code". The code fails to render.

![Screenshot_20200516_205825](https://user-images.githubusercontent.com/12252677/82123639-09a7f400-97b8-11ea-94db-d34405b8bbef.png)

**Want to take up?**

Yes

**Comment by dhruvkb** [comment]
@Herald-Of-Solace are you suggesting we change the `<p>` tag to a `<div>` tag because paragraphs can't contain addresses?

**Comment by heraldofsolace** [comment]
@dhruvkb Yes, I think that should fix the issue

**Comment by heraldofsolace** [comment]
Hmm. So changing `<p>` to `<div>` makes it a valid HTML as can be checked here https://validator.w3.org/#validate_by_input

However, my assumption that the invalid code caused the render to fail was not correct. There are other places where also the code fails to render (e. g. Locale, Tabs etc.). What I found was that writing the stories like this fixes the issue

```
export const footer = () => `
<footer ...>
...
</footer>
`

<Preview mdxSource={footer()}>
  <Story name="Default" parameters={{
    design: figmaConfig("639%3A185")
  }}>{footer()}</Story>
</Preview>
```

![Screenshot_20200518_121210](https://user-images.githubusercontent.com/12252677/82181812-dae96500-9900-11ea-8848-c3895f1bb06a.png)
