### ISSUE TITLE
Add profile image component as per the new designs.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#388]
**Description**

The new websites designs have a recurring use of the profile image. For the ease of development, it can be added to the vocabulary.
![image](https://user-images.githubusercontent.com/34674462/82139686-61417080-9847-11ea-9383-42113911bf22.png)

**Want to take up?**

Yes

**Comment by hugosolar** [comment]
Regarding this, I think that maybe a "general class" can be added to add it on any image in order to make it round. eg.
```
<img src="image.png" class="rounded-image" />
```

Tagging @dhruvkb and @panchovm to know your thoughts

**Comment by fcoveram** [comment]
It seems perfect for me

**Comment by Dhruvi16** [comment]
If everyone is fine with that then should I make a PR?
@hugosolar @dhruvkb

**Comment by fcoveram** [comment]
As @kgodey said, we are creating this element as a component. I will update the Design Library.

**Comment by dhruvkb** [comment]
To add to @hugosolar, I also notice a black border around the image, so just the rounding class will not be enough.

**Comment by Dhruvi16** [comment]
I guess the idea of a class is correct but we can come up with a generalized name of that class. What say? @hugosolar @dhruvkb

**Comment by fcoveram** [comment]
The Design Library has been updated with this component. Here is [the link](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=6728%3A328&viewport=83%2C311%2C0.48122164607048035)
