### ISSUE TITLE
Add blog banner as per the new designs.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#393]
**Description**

The new designs for the CC OS website extensively use banners to present blogs. This might give us a reason to add it to the Vocabulary.
![image](https://user-images.githubusercontent.com/34674462/82195363-d11e2c80-9915-11ea-8dbf-f2d96de2e7ad.png)

**Additional context**

This component scope is yet to be discussed.

**Want to take up?**

Yes

**Comment by hugosolar** [comment]
This component could be a variation from the Card/Quote component

**Comment by Dhruvi16** [comment]
Yes! That is what I meant.

**Comment by fcoveram** [comment]
As @kgodey said, we are creating this element as a component. I will update the Design Library.

**Comment by fcoveram** [comment]
The Design Library has been updated with this component. Here is [the link](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=776%3A0&viewport=-1019%2C-956%2C1.0975457429885864) to see the new card.
