### ISSUE TITLE
Add project banner according to the new designs.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#394]
**Description**

A banner is extensively used to present a project's details. It might be helpful to add it as a component to the vocabulary.
![image](https://user-images.githubusercontent.com/34674462/82196171-0119ff80-9917-11ea-8ddc-9ba72e02f619.png)
 
**Additional context**

The scope of the component is yet to be discussed.

**Want to take up?**

Yes

**Comment by dhruvkb** [comment]
@Dhruvi16 this seems to be a card. I'm not entirely sure it's a new component.

**Comment by hugosolar** [comment]
I agree. It can be a new variation of a Card

**Comment by Dhruvi16** [comment]
Yes, I meant the same but as said by @panchovm on slack, we are not adding it to the library, right?

**Comment by fcoveram** [comment]
As @kgodey said, we are creating this element as a component. I will update the Design Library.

**Comment by fcoveram** [comment]
The Design Library has been updated. Here is [the link](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=776%3A0&viewport=-2930%2C-636%2C0.6898031234741211) to see the new card.
