### ISSUE TITLE
Make Vocabulary compliant with the CC style guide

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#4]
The new [CC style guide](https://creativecommons.org/wp-content/uploads/2019/10/Creative-Commons-Style-Guide-2019.pdf) (from the [blog post](https://creativecommons.org/2019/10/30/cc-style-guide/) by @victoriaheath) contains a lot of differences from Vocabulary, notable in the color palette and typoraphical departments). Moreover, while the document outlines the guidelines for the copy and imagery, it omits setting guidelines for code and UI. That has been Vocabulary's domain so far.

The goal is to unify the two styleguides into a web document, a living styleguide if you will, that outlines guidelines for styling text, images, icons, copy, code, UI and UX across CC across media. 

There are also differences in details which must be resolved and merged:
- colour palette (#23)
  - **Vocabulary:** 9 hues x 4 shades + 8 tones + 4 overlays
  - **Styleguide:** 6 hues x 1 shade + 1 tone
- fonts (#63)
  - **Vocabulary:** Source Sans Pro, Fira Code
  - **Styleguide:** Source Sans Pro, Roboto, Accidenz Commons (also see creativecommons/vue-vocabulary#63)

**Comment by kgodey** [comment]
Will this issue be updated with the new colors we decided on?

**Comment by dhruvkb** [comment]
This issue is redundant considering #5.
