### ISSUE TITLE
We need to add the card collection component

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#400]
We need to add a new component: the card collection. This component is present in CC Search, Sources page, and works as a link. Here is [the link to the Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=776%3A0&viewport=-3514%2C-324%2C0.6717029213905334).

### Expected behavor
When the component works as a link, the hover state should change the border color and have a box shadow. The visual reference is in [CC Search Mockup S3](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=205%3A5130&viewport=12%2C113%2C0.7707639932632446).

### Screenshot
<img width="381" alt="Screen Shot 2020-05-19 at 11 12 11" src="https://user-images.githubusercontent.com/895819/82344069-9a055500-99c1-11ea-8012-cae1f6d12cd5.png">

**Comment by dhruvkb** [comment]
@panchovm and @brenoferreira it seems to me that card collection is a set of cards placed in a grid. I'm a little confused about the implementation specifics of having 'card collection' as a new component.

**Comment by fcoveram** [comment]
You are right. But could be the possibility of having the component using more or fewer columns. However, for now is tied to CC Search uses. If you think that is not necessary, then I'm with you.

**Comment by kgodey** [comment]
We are no longer going to be using this component, it will be removed from the Design Library.
