### ISSUE TITLE
Hovering over social media icons in the footer shows an underline

### ISSUE THREAD

**Issue by makkoncept** [cc-archive/vocabulary-legacy#405]
**Description**
The social media icons in the footer are wrapped in a link and that link has rule `text-decoration: underline` set for hover pseudo-class.

**Reproduction**
Go to  https://cc-vocabulary.netlify.app/?path=/docs/patterns-footer--default-story and hover over the social media icons.

**Expected behavior**

No underline should be visible. The footer on [CC Search](https://search.creativecommons.org/) has this expected behavior.

**Screenshots**

![Screenshot from 2020-05-21 15-42-09](https://user-images.githubusercontent.com/34679965/82548875-ab915d00-9b79-11ea-9d31-a2a6fc9d3bde.png)

**Conditions:**

 - OS: Ubuntu 19.10
 - Browser: Chrome 80.0.3987.149

**Want to take up?**

No

**Comment by kushaggarwal** [comment]
Would like to take this issue @dhruvkb if still open
