### ISSUE TITLE
Explain the usage of CC lettermark and logomark

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#407]
**Description**
Both CC lettermark and letterheart have icons in Vocabulary Icons. This should be mentioned in the docs for the corresponding logos to offer the alternative for people looking to embed them in places like the button.

**Problems solved**
An alternative is offered that provides ease-of-use in many scenarios.

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
I would like to take this up

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
With the current logos of Lettermark and logomark is there anything else apart from the presence of the icons for these that is to be mentioned in it 
Thanks

**Comment by dhruvkb** [comment]
@kushaggarwal I can't think of anything other than just mentioning the existence of the icons. You're free to point out if you think something is missing or needs to be added.

**Comment by kushaggarwal** [comment]
Okay @dhruvkb
