### ISSUE TITLE
Replace the old Vocabulary logo with the new

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#408]
**Description**
The Vocabulary logo is used in a number of places such as
- the `README.md` file
- the sidebar and welcome page of the storybook
- the `og:image` and `twitter:image` meta tags

in both Vocabulary and Vue Vocabulary. These haven't been updated after #366.

**Reproduction**
View any of the files mentioned above. The old logo 'vo·cab·u·lar·y' still appears in those places.

**Expected behavior**
The new logo '(CC) vocabulary' should have appeared.

**Additional context**
While changing the logos in most places is easy, changes to the meta-images will need a little bit of image manipulation skills, such as proficiency with either Inkscape or GIMP.

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
Would like to work on this if still open

**Comment by dhruvkb** [comment]
@kushaggarwal you can take this up after #407.

**Comment by kushaggarwal** [comment]
Okay no problem

**Comment by jahnvigupta** [comment]
@dhruvkb Can I work on the issue?

**Comment by dhruvkb** [comment]
@jahnvigupta which parts of this issue are you aiming for?

**Comment by kushaggarwal** [comment]
If it’s fine I can go for Readme and Welcome Page

**Comment by dhruvkb** [comment]
Nice that you divided it among yourselves. @jahnvigupta just make sure you get some GIMP or Inkscape experience because changing `og:image` and `twitter:image` does need that. You can reach out if you need some help with that.

**Comment by jahnvigupta** [comment]
@dhruvkb  Although I am familiar with using inkspace but I am unclear about which images you are talking about.

**Comment by dhruvkb** [comment]
@kushaggarwal in your PR for the `README.md` file, set the logo height to `40px` and remove the Creative Commons logo just above it (as the new logo already contains CC in it).
