### ISSUE TITLE
Disabled button doesn't follow mockup

### ISSUE THREAD

**Issue by brenoferreira** [cc-archive/vocabulary-legacy#411]
The disabled state of the next button should follow the Design Library definition.

Related to https://github.com/creativecommons/cccatalog-frontend/issues/963

**Comment by dhruvkb** [comment]
@brenoferreira can you please expand upon the issue by attaching some expectation vs reality screenshots. That would be very helpful in identifying and patching the issue. Thanks!

**Comment by zackkrida** [comment]
This issue was in cc search, not vocabulary. The wrong button class was in use.
