### ISSUE TITLE
Some color helper classes are not working

### ISSUE THREAD

**Issue by makkoncept** [cc-archive/vocabulary-legacy#412]
**Description**
The colors section of the storybook (https://cc-vocabulary.netlify.app/?path=/docs/tokens-color--figma) lists some colors that can be used directly with the help of helper classes but some of them are not displaying any color.

Check out [this Codepen](https://codepen.io/makkoncept/pen/XWmQgdv).

**Want to take up?**

No

**Comment by dhruvkb** [comment]
Currently these classes are only set up to work with brand colors, namely
- Tomato
- Orange
- Gold
- Forest green
- Dark turquoise
- Dark slate blue
- Dark slate gray

Do you have requirements for them to support other colors?

**Comment by makkoncept** [comment]
Yes, currently I require feedback colors but may need other ones too in the future. Right now I am using CDN to load vocabulary so it would be helpful.

**Comment by dhruvkb** [comment]
For feedback colors you can directly use

```html
<div class="buttons">
  <button class="button is-info">Info</button>
  <button class="button is-success">Success</button>
  <button class="button is-warning">Warning</button>
  <button class="button is-danger">Danger</button>
</div>
```
as demonstrated in the [Bulma docs](https://bulma.io/documentation/elements/button/#colors).

We've replaced Bulma's colors with our own so you'll see the expected result. Let me know if that fulfils your usecase.

**Comment by makkoncept** [comment]
Thanks, but these are only working on buttons. I need the colors for text and background also. Also, most probably the need for interaction and neutral colors would also arise in the future.

**Comment by dhruvkb** [comment]
For text and backgrounds, you can again use Bulma helpers:
- `.has-text-*`
- `.has-background-*`

as given [here](https://bulma.io/documentation/modifiers/color-helpers/). We're just trying to limit Vocabulary to the minimum necessary classes and not build based on speculations.

**Comment by makkoncept** [comment]
Okay, Make sense. Thanks! 
Shall I close this?

**Comment by dhruvkb** [comment]
No problems, I'll do it.
