### ISSUE TITLE
Separate tokens from Bulma

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#414]
**Description**
Mixing tokens and Bulma integrations in the same file makes it hard to use tokens in our own code because of Bulma not being found. This can be fixed by keeping tokens separate and then importing them in the files where Bulma is integrated.

**Expected behavior**
Tokens should be usable without installing Bulma.

**Comment by Dhruvi16** [comment]
This also means moving the bulma tokens with the imports. Can we afford that?

**Comment by dhruvkb** [comment]
Keep the Bulma variables in the existing file, just move "our" constants outside.
