### ISSUE TITLE
The headings are not rendering as "headings" anymore

### ISSUE THREAD

**Issue by makkoncept** [cc-archive/vocabulary-legacy#424]
**Description**

The rendered sizes of the headings element are not the same as described [on storybook](https://cc-vocabulary.netlify.app/?path=/docs/tokens-typography--figma). Their font-weight is also normal.

**Reproduction**

Check out this [codepen](https://codepen.io/makkoncept/pen/XWXrWNq?__cf_chl_jschl_tk__=c6ef000ac9a21be8e730f1248afdff005e6402e8-1590962886-0-AYQfw3_I3L93qQBiwx14Aytg3KV5NUPzGeoKYeQRZONJeVoP6-TB1pNJgVkYeM0CF6T8RqkeT9uOdwZ81l4xzvVnaKwOpF8tKk5rS7bJmQjcO4JtrX7NU6xZ4F3HohDcuWXFUXnL6EXKjf6M1OyIjZ9v37ATKY0R5lKKohp3fIxXBKmWIQcfgi1Ku_4rM3t0uYyofuGKUw9xMIurJCO_qMl5LB0RhnZnKyN-FeqReo5Nctr1OVRUFw1lC4q4SGa7kSyiX9ImH2kE8rSr1bFQgMmXxAXqbneaMjDcb6hFE3v39YVatskP5dsLYJyUx-qI6gcbImzOJ5rIiBqE2G8efkI) or the screenshots below.

**Screenshots**

**Before**

![Screenshot from 2020-06-01 03-36-52](https://user-images.githubusercontent.com/34679965/83363893-9bb81b00-a3ba-11ea-9686-579ad6775ace.png)

**After**

![Screenshot from 2020-06-01 03-36-58](https://user-images.githubusercontent.com/34679965/83363890-9b1f8480-a3ba-11ea-9ea3-c7940051fd58.png)

**Before**

![Screenshot from 2020-06-01 03-36-33](https://user-images.githubusercontent.com/34679965/83364029-c060c280-a3bb-11ea-97c8-f30b19652345.png)

**After**

![Screenshot from 2020-06-01 03-36-41](https://user-images.githubusercontent.com/34679965/83363895-9e1a7500-a3ba-11ea-9d40-b99739f8f2c9.png)

**Conditions:**

 - OS: Ubuntu 19.10
 - Browser: Chrome Version 80.0.3987.149
 - Version: vocabulary@1.0.0-beta.15

**Additional context**

Client side inspection shows that the following rule is overding the heading sizes
``` css
h1, h2, h3, h4, h5, h6 {
    font-size: 100%;
    font-weight: normal;
}
```
**Want to take up?**

No

**Comment by dhruvkb** [comment]
#426 is a quickie fix for this bug and concrete long-term refactoring will be taken up under #425.
