### ISSUE TITLE
Organise tokens to interoperate with Bulma variables

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#425]
**Description**
Bulma offers a large amount of flexibility via [Sass variables](https://bulma.io/documentation/customize/variables/#initial-variables). Instead of manually overriding a lot of styles, we can achieve a lot of similar functionality by just mapping the right Bulma variables to the right token values.

**Problems solved**
Reduces the amount of Sass we need to write, because we can build build on top of Bulma rather than first having to undo it.

**Alternatives**
Reordering Sass imports was considered in #414 but that led to #424. So shortcuts won't work. It's time to do it the right way.

**Comment by jahnvigupta** [comment]
@dhruvkb I want to take this, any pointers for getting started?

**Comment by jahnvigupta** [comment]
![Screenshot from 2020-06-01 22-09-27](https://user-images.githubusercontent.com/43217070/83431220-a6bf8980-a454-11ea-9da5-e37291541c00.png)
@dhruvkb Here,  $space-big has been defined as $card-content-padding. Is it that I have to replace space-big class by card-content-padding and similarly in other sass files?

**Comment by dhruvkb** [comment]
@jahnvigupta no, the goal is to set the Bulma variables to match the tokens. We don't have to modify any components in this issue.

**Comment by chidexebere** [comment]
@dhruvkb  If I understand you clearly, 

this 

```$color-orange: rgb(251, 119, 41) ```

should change to this

```$color-orange: $orange```


And for variables not defined in Bulma, like

```$color-tomato: rgb(237, 89, 47)```

 should be left the same way.

**Comment by dhruvkb** [comment]
@chidexebere, I'm talking the other way around. Variables provided by Bulma should be replaced with values from Vocabulary.

**Comment by chidexebere** [comment]
@dhruvkb  okay you mean this

```$orange: rgb(251, 119, 41)```

```$tomato: rgb(237, 89, 47)```

instead of 

```$color-orange: rgb(251, 119, 41)```

```$color-tomato: rgb(237, 89, 47)```
