### ISSUE TITLE
Add Do's and Don'ts

### ISSUE THREAD

**Issue by jahnvigupta** [cc-archive/vocabulary-legacy#427]
**Description**

To make the usage of Colors easier from storybook, do's and don'ts need to be added. 
**Problems solved**

Better usage of colors will be more likely.
**Alternatives**

**Additional context**

**Want to take up?**

[Yes|No]
Yes

**Comment by dhruvkb** [comment]
Please elaborate on what you mean by 'Dos and Don'ts' with a couple of examples. That would be helpful to understand what problems we're trying to solve and how.

**Comment by jahnvigupta** [comment]
@dhrub I meant the do's and don'ts given in figma design library
https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A72

**Comment by dhruvkb** [comment]
Those instructions are very image intensive. The effort to recreate these in MDX will be too high, and the return on that effort will just be a copy of the existing rules.
