### ISSUE TITLE
Add Sidebar menu.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#428]
**Description**

The new designs for CC OS consist of a sidebar menu. 
![image](https://user-images.githubusercontent.com/34674462/83442559-fc506200-a465-11ea-963f-ce9c1f3f31e0.png)

**Additional context**

The scope of the component is yet to be discussed.

**Want to take up?**

Yes

**Comment by fcoveram** [comment]
[The Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=6990%3A0&viewport=45%2C261%2C0.22026315331459045) has been updated with this new component.
