### ISSUE TITLE
Add Table of content component.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#429]
**Description**

The new design for CC OS consists of Table of content component.
![image](https://user-images.githubusercontent.com/34674462/83442716-3de10d00-a466-11ea-9be2-658690068cd0.png)

**Additional context**

The scope of this component is yet to be discussed.

**Want to take up?**

Yes

**Comment by fcoveram** [comment]
[The Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=6990%3A0&viewport=45%2C261%2C0.22026315331459045) has been updated with this new component.
