### ISSUE TITLE
Add step progress component.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#430]
**Description**

The new design for CC OS consists of a step progress component.
![image](https://user-images.githubusercontent.com/34674462/83442876-826ca880-a466-11ea-913e-77c8c74d5102.png)

**Additional context**

The scope of this component is yet to be discussed.

**Want to take up?**

Yes

**Comment by dhruvkb** [comment]
Related to #112?

**Comment by Dhruvi16** [comment]
Yes! It will a part of it AFAIK. Let's wait for @panchovm for the final take.

**Comment by jahnvigupta** [comment]
@dhruvkb @Dhruvi16 I have already a open PR on this issue. Please check if that makes sense.
https://github.com/creativecommons/vocabulary/pull/310

**Comment by fcoveram** [comment]
Sorry I missed the point here. What should I take @Dhruvi16?

**Comment by Dhruvi16** [comment]
@panchovm we wanted to have an open discussion about how is this component is going to be added in the DL and if it is neccesary to add this step progress or not?

**Comment by fcoveram** [comment]
[The Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=6990%3A0&viewport=45%2C261%2C0.22026315331459045) has been updated with this new component.

**Comment by Dhruvi16** [comment]
> Related to #112?

So, as per DL, it is related to the navigation part.

**Comment by fcoveram** [comment]
I put it there because it is a navigation component. I can change it if @dhruvkb and @hugosolar think we should take a different approach. No problem

**Comment by dhruvkb** [comment]
Step progress does not seem related to navigation in my opinion as navigation is used to move to a different part of a website, which this component does not do.

**Comment by Dhruvi16** [comment]
Yes, I agree with @dhruvkb.
