### ISSUE TITLE
Add pagination component to the library.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#431]
**Description**

The new designs consist of a pagination component and adding it to the library would make it reusable.
![image](https://user-images.githubusercontent.com/34674462/83548720-db4d4700-a521-11ea-91cf-c9c0716cb514.png)

**Want to take up?**

[Yes]

**Comment by dhruvkb** [comment]
@panchovm please link the DL here.

**Comment by Dhruvi16** [comment]
Here is the [link](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=7005%3A35&viewport=45%2C266%2C0.4650000035762787)
