### ISSUE TITLE
Illustrate usage of vocabulary components

### ISSUE THREAD

**Issue by megha070** [cc-archive/vocabulary-legacy#433]
**Description**
So as to make it easier for newbies to get started with vocabulary an illustration guide is needed as people tend to understand things when they are depicted in the form of visual elements.

**Problems solved**
This would help in getting a clear understanding of how to use vocabulary components along with additional guidelines(on what not to do).

**Alternatives**

**Additional context**

**Want to take up?**

[Yes|No]
Yes

**Comment by megha070** [comment]
@dhruvkb @hugosolar @panchovm I intend to integrate Codepen so as to illustrate vocabulary usage of various components. Below is my approach to take this forward. Would love to hear your suggestions on this.
[vocab.pdf](https://github.com/creativecommons/vocabulary/files/4721278/vocab.pdf)

**Comment by fcoveram** [comment]
I agree with your approach, thanks for bringing it. Currently, we are working on something similar but embedding the Figma's view into the documentation. We discussed this but I'm not aware of the integration and then the public release. Waiting for other responses to be sure that this fits our approach.

**Comment by dhruvkb** [comment]
This is actually a duplicate of two existing issues #427 and #377.
