### ISSUE TITLE
"Getting Started" Guide 

### ISSUE THREAD

**Issue by megha070** [cc-archive/vocabulary-legacy#437]
## Problem Description
So as to help newbies getting started with vocabulary usage, a "Getting Started" guide would be useful by giving a hands on experience to new developers thereby making them comfortable with vocabulary.

## Solution Description
Having a "Getting Started" Guide would make it easier for new developers to communicate and understand usage of Vocabulary. This can be accomplished by building a starter "Hello World" application by making use of vocabulary components.

**Comment by megha070** [comment]
@hugosolar @dhruvkb @panchovm Would love to know your thoughts on this. If this is a valid issue, I will share a rough draft of basic outline of one such guide. 
I would like to take this up.

**Comment by dhruvkb** [comment]
@megha070 this is also covered in #377.
