### ISSUE TITLE
Make Vocabulary Icon font usable as Bulma icons

### ISSUE THREAD

**Issue by ayanchoudhary** [cc-archive/vocabulary-legacy#440]
## Describe the bug

The icon in the locale selector is supposed to be like this:
![Design Library – Figma - Brave 05-06-2020 23_26_06](https://user-images.githubusercontent.com/45792768/83908037-10f16a80-a784-11ea-9784-4fa446e9aa87.png)

But on actual usage, the icon gets positioned like this:
![Design Library – Figma - Brave 05-06-2020 23_27_32](https://user-images.githubusercontent.com/45792768/83908151-3bdbbe80-a784-11ea-8519-1afa1a2fe345.png)

## To Reproduce

The associated code is:
```
  <div class="locale">
      Languages available
      <div class="control has-icons-left">
        <div class="select">
          <select>
            <option disabled>Select</option>
            <option selected>English - English</option>
            <option>le Français - French</option>
            <option>Japanese - 日本語</option>
            <option>Russian - Русский</option>
            <option>Spanish - Español</option>
          </select>
        </div>
        <div class="icon globe is-small is-left">
            <i class="icon globe">locale</i>
        </div>
      </div>
    </div>
```

## Desktop (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser Brave
 - Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by dhruvkb** [comment]
Bulma allows for icons to be used in a number of places, such as
- [Breadcrumbs](https://bulma.io/documentation/components/breadcrumb/#icons)
- [Button](https://bulma.io/documentation/elements/button/#states)
- [Input](https://bulma.io/documentation/form/input/#with-font-awesome-icons)
- [Standalone](https://bulma.io/documentation/elements/icon/)

Vocabulary Icons should also be usable, identically in all of these places.

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
If this is still open would like to take it up

**Comment by kushaggarwal** [comment]
@dhruvkb 
Can you please help as if for the above problem should I add a new class for icons dropdown component as I think bulma natively doesnt support this features

**Comment by dhruvkb** [comment]
Bulma natively allows icons inside select fields. See [documentation](https://bulma.io/documentation/form/select/#with-icons).
