### ISSUE TITLE
Contrast Issues in caption, search placeholder and tags

### ISSUE THREAD

**Issue by ayanchoudhary** [cc-archive/vocabulary-legacy#455]
## Problem

There is an issue with the contrast ratios of text in search placeholder, image captions and filter and photo tags

## Additional context

![CC Search - Brave 12-06-2020 15_27_24](https://user-images.githubusercontent.com/45792768/84492382-bb591880-acc3-11ea-9668-2dc7825ee68c.png)

![CC Search - Brave 12-06-2020 15_29_30](https://user-images.githubusercontent.com/45792768/84492393-beec9f80-acc3-11ea-956e-ea22f1874dc1.png)

![CC Search - Brave 12-06-2020 15_34_18](https://user-images.githubusercontent.com/45792768/84492414-c744da80-acc3-11ea-88de-40c00725f888.png)

![CC Search - Brave 12-06-2020 15_39_53](https://user-images.githubusercontent.com/45792768/84492434-cdd35200-acc3-11ea-98df-800114727e44.png)

![CC Search - Brave 12-06-2020 15_41_51](https://user-images.githubusercontent.com/45792768/84492451-d3309c80-acc3-11ea-8155-8f66c648f787.png)

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by ayanchoudhary** [comment]
@panchovm @annatuma

**Comment by dhruvkb** [comment]
@AyanChoudhary please break these into separate issues that can be worked on individually. We can retain this as a parent issue to track progress as a big picture.

**Comment by ayanchoudhary** [comment]
Linking relevant smaller issues: https://github.com/creativecommons/vocabulary/issues/472, https://github.com/creativecommons/vocabulary/issues/473, https://github.com/creativecommons/vocabulary/issues/474, https://github.com/creativecommons/vocabulary/issues/475, https://github.com/creativecommons/vocabulary/issues/476
