### ISSUE TITLE
Add font & typography definition

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#46]
**Reference**: "Typography" page in our Figma Design Library: https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A110

We need to integrate everything from the Typography page in Figma Design Library into a new "Typography" page in Vocabulary.

**Comment by tinaShyp** [comment]
Hi, my name Tina. I am an Outreachy applicant for May 2020. I would like to work on your project. Can I please work on this issue, if it's still available?

**Comment by dhruvkb** [comment]
@tinaShyp PR #161 already adresses this issue. Could you find another issue to work on?
