### ISSUE TITLE
A smaller version of the header component [Feature request]

### ISSUE THREAD

**Issue by makkoncept** [cc-archive/vocabulary-legacy#464]
## Problem
The CC Search Extension mockup uses a header component that any of the current Vocabulary header component is not able to  replicate. See the [Figma Mockup file](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=892%3A4577&viewport=505%2C72%2C0.28836095333099365) and a quick [Codepen](https://codepen.io/makkoncept/pen/LYGZgrX) for reference.

## Description

Some differences that I noticed:
- The height of the header seems to be little larger than the one in the mockup.
- The class of `has-text-tomato` class on `nav-item` links is not able to override the default `nav-item` color.
- The `nav-item` also has larger margin and font-size.
- Changing `logomark` icon with `search` icon does not work by default. Changing the `viewBox` attribute of `svg` element from `0 0 304 73` to  `0 0 170 50` does the trick but now the icon is not vertically alligned.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by kushaggarwal** [comment]
Hello @dhruvkb @makkoncept 
If this issue is open I would like to take this up

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
Can you please help with the story name for the component of header described above
Thank You

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
For the above mentioned changes is a new component need to be introduced or class has to mentioned for the desired changes 
Please help
Thanks

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
Can you please help

**Comment by hugosolar** [comment]
@kushaggarwal I would say you can use a class to transform the header instead of creating a new component.

**Comment by makkoncept** [comment]
The figma file has been moved. [New link](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562)

**Comment by kushaggarwal** [comment]
Sure @hugosolar will follow the same 
Thank you

**Comment by makkoncept** [comment]
@kushaggarwal are you still working on this?

**Comment by kushaggarwal** [comment]
Yes @makkoncept will open a pull request soon
