### ISSUE TITLE
A modified image component for CC Search Extension [Feature Request]

### ISSUE THREAD

**Issue by makkoncept** [cc-archive/vocabulary-legacy#465]
## Problem
The CC Search Extension mockup uses a modified image component that is not currently present in CC Vocabulary. See the [Figma Mockup file](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562) and a quick [Codepen](https://codepen.io/makkoncept/pen/MWKexxL) for reference.

## Description

Some differences that I noticed:

- The image component for extension won't be needing an image title. Though this can easily be done by not including the `image-title` div when dynamically building the component and appending them in the masonry grid in the extension.
- The space between the license icons is a bit less.
- A `bookmark` icon is also there on the top-right corner.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by makkoncept** [comment]
I would also like to tell @panchovm about a little design issue.

On searching for images, a scrollbar also appears on the right side of the extension. It fits in the already capped width of the extension (`640px`) and therefore other spaces are reduced to make way for it. This becomes evident as small gaps between elements are reduced (like the `16px` gap between the "Search" and "Filters" button: Please check [Codepen with scrollbar](https://codepen.io/makkoncept/pen/MWKexxL) and [Codepen without scrollbar](https://codepen.io/makkoncept/pen/ZEQpbdP)). 

I think that having a width less than `640px` in the designs would help because it would prepare the extension to have a consistent design when the scrollbar appears. I would love to hear your and @dhruvkb thoughts on this.

_side note_: Firefox reserves the space for scrollbar by default, even if there is no search result.
![Screenshot from 2020-06-15 20-15-07](https://user-images.githubusercontent.com/34679965/84671504-164d7280-af45-11ea-89cf-c4b392785335.png)

**Comment by dhruvkb** [comment]
I'll let @panchovm look into the designs in detail. My two cents:
- You can now style the scrollbar ([to some extent](https://github.com/dhruvkb/portfolio/blob/master/src/styles/utils/scrollbars.scss)) in most modern browsers. If your extension supports Firefox or Chrome, you're most likely already targeting that demographic.
- You can add the width of the scrollbar to the width of the popup and make it permanent and to avoid the elements from reflowing when it appears or disappears.
- You can use some tiny JS library to replace the scrollbar with a faux one made out of `div`s. This might be overkill for extensions but it's a viable option for apps.

**Comment by fcoveram** [comment]
I think @dhruvkb's answers are way better than what I have to say  😄

**Comment by makkoncept** [comment]
Hi @hugosolar , Does the following strategy regarding the implementation sounds good?

- Add a div with class `bookmark-icon` that will encapsulate the bookmark icon (`i` tag). 
- A class `is-bookmarked`, which can be added to the above div to show a "bookmarked" icon (instead of the default "un-bookmarked" icon).

Also, I have a question.
The image component in the [CC Search mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562) has smaller icons and less padding (see the screenshots below for comparison). So, what class name would be better for this. I can only think of `.is-compact`.

![Screenshot from 2020-07-17 00-16-41](https://user-images.githubusercontent.com/34679965/87710247-21edbc80-c7c3-11ea-8c0d-4e9e54fda9ca.png)
![Screenshot from 2020-07-17 00-21-38](https://user-images.githubusercontent.com/34679965/87710592-91fc4280-c7c3-11ea-8eda-c0137252cd90.png)

I'll first try to complete https://github.com/creativecommons/fonts/issues/105 and then submit a PR for this issue.

**Comment by hugosolar** [comment]
> Hi @hugosolar , Does the following strategy regarding the implementation sounds good?
> 
>     * Add a div with class `bookmark-icon` that will encapsulate the bookmark icon (`i` tag).
> 
>     * A class `is-bookmarked`, which can be added to the above div to show a "bookmarked" icon (instead of the default "un-bookmarked" icon).
> 
> 
> Also, I have a question.
> The image component in the [CC Search mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562) has smaller icons and less padding (see the screenshots below for comparison). So, what class name would be better for this. I can only think of `.is-compact`.
> 
> ![Screenshot from 2020-07-17 00-16-41](https://user-images.githubusercontent.com/34679965/87710247-21edbc80-c7c3-11ea-8c0d-4e9e54fda9ca.png)
> ![Screenshot from 2020-07-17 00-21-38](https://user-images.githubusercontent.com/34679965/87710592-91fc4280-c7c3-11ea-8eda-c0137252cd90.png)
> 
> I'll first try to complete [creativecommons/fonts#105](https://github.com/creativecommons/fonts/issues/105) and then submit a PR for this issue.

Hey @makkoncept I think your approach is correct
Let's define `.is-compact` for all the components that need a compact version. is that sounds ok for you?

**Comment by makkoncept** [comment]
@hugosolar Sounds good :+1:
