### ISSUE TITLE
A minimal notification component [Feature Request]

### ISSUE THREAD

**Issue by makkoncept** [cc-archive/vocabulary-legacy#466]
## Problem

The CC Search Extension mockup uses a small, minimal notification component that any of the current Vocabulary notification component is not able to replicate (unless the padding, font-size and width is overridden). See the `home bookmarked` [Figma mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562) to see the intended design of notification component.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by kushaggarwal** [comment]
Hello @dhruvkb 
I would like to take this up

**Comment by kushaggarwal** [comment]
@dhruvkb 
Can you please help as if by what story name is it to be named with 
Thank you

**Comment by dhruvkb** [comment]
Call it `notification`.

**Comment by makkoncept** [comment]
@kushaggarwal are you still working on this?

**Comment by kushaggarwal** [comment]
Yes @makkoncept was a bit occupied will soon update the following changes

**Comment by makkoncept** [comment]
@kushaggarwal Since this is a time-sensitive issue. I am going to take it over. These components are needed in the CC Search Extension.

**Comment by kushaggarwal** [comment]
Okay @makkoncept 
Apology for not attending to this issue on time 
Thank you
