### ISSUE TITLE
Issue with building documentation & library

### ISSUE THREAD

**Issue by nilshah98** [cc-archive/vocabulary-legacy#47]
**Description**

After installing all dependencies and devDependencies using - `npm i --dev`
When I tried to build documentation using the command - `npm run build:documentation`
Also, produces the same error while trying to build library - `npm run build:library`

**Reproduction**

- Create a folder having space in the name like - `Creative Commons`
- Also folders having non ASCII values such as - `GSOC 2020 🚀`
- `git clone https://github.com/creativecommons/vocabulary.git`
- `npm i --dev`
- `npm run build:documentation`
- `npm run build:library`

**Expected behavior**

- Should allow clean build for even folders having space in their names

**Screenshots**

**Issue- with space in name**
![image](https://user-images.githubusercontent.com/22821480/72831147-40f21280-3ca8-11ea-8dd5-f0e8e004c1e7.png)

**Issue with space along with non ASCII characters**
- Even though this shows a clean build, this generates new folders at the location
- Example name - `GSOC 2020 🚀`

**Without space in name**
![image](https://user-images.githubusercontent.com/22821480/72831346-a8a85d80-3ca8-11ea-9d36-290663e2170b.png)

**Conditions:**

 - OS: Ubuntu 18.04
 - Browser: Google Chrome
 - Version: 79.0.3945.117

**Additional context**

- The issue is definitely due to space in folder name, to resolve it should resolving the build script at `documentation/build` work or something else, I am not sure.
- Additionally the issue is only caused when calling CLI commands from javascript files, as they are unable to handle the spaces or non ASCII characters, whereas nodes library can use those path properly.

**Want to take up?**

[Yes|No]
Yes

Would love some guidance on the same.

**Comment by dhruvkb** [comment]
You’re welcome to work on it @nilshah98. The build process is all inside `documentation/build.js`.

**Comment by nilshah98** [comment]
Thank you I'll try to work on the same.
Although at this stage I am unsure whether this is a bug in the `documentation/build.js` or developer dependencies for the application.

But, I'd like to claim this issue.

**Comment by nilshah98** [comment]
The same issue exists for - `npm run build:library`.
![image](https://user-images.githubusercontent.com/22821480/73123699-a56ae580-3fb8-11ea-9047-08ff7e328d6b.png)

Whereas - `npm run build:tokens` run perfectly well.

Should I open a new issue, for `npm run build:library` ?

**Comment by dhruvkb** [comment]
It's all working fine now. We have the Netlify build and `npm` deployment both working as expected.
