### ISSUE TITLE
Modified tab components [Feature request]

### ISSUE THREAD

**Issue by makkoncept** [cc-archive/vocabulary-legacy#471]
## Problem

I observed that `tabs` component used in the [CC Search Extension Mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562) have a different design. 

I see two new flavours of the component :

![Screenshot from 2020-06-16 18-21-01](https://user-images.githubusercontent.com/34679965/84776867-7eac5a80-affe-11ea-8637-5aac15eccde3.png)

![Screenshot from 2020-06-16 18-14-11](https://user-images.githubusercontent.com/34679965/84776877-81a74b00-affe-11ea-8c51-93e6cfeda66c.png)

Maybe more discussion is needed for the second one. Is it really a tab component or something else(a header?). It do functions like a tab in the [Mockup](https://www.figma.com/proto/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=892%3A4577&viewport=505%2C72%2C0.28836095333099365&scaling=min-zoom).

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by fcoveram** [comment]
I need to add as a component the tab used in Browser extension. We have faced different levels of content navigation and that's why the component difference. Thanks for bringing this.

**Comment by fcoveram** [comment]
The [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=6990%3A0&viewport=-2149%2C170%2C0.37196049094200134) is updated with the two navigation components.

**Comment by zackkrida** [comment]
@panchovm The 'Line Tab' should replace the existing tab style here: https://cc-vocabulary.netlify.app/?path=/story/layouts-tabs--tab, yes? Just want to confirm 😸

**Comment by fcoveram** [comment]
Yes @zackkrida. It should be replaced.

**Comment by makkoncept** [comment]
@zackkrida @panchovm I am working on this issue. The "line tab" in the design library looks very similar to the existing tab style except for the thicker bottom border. Am I missing something else?

**Comment by zackkrida** [comment]
@makkoncept please also see the length of the bottom border (aligns with the text, no extra left+right spacing, and various hover/active differences:

> new
<img width="533" alt="Screen Shot 2020-07-27 at 3 28 38 PM" src="https://user-images.githubusercontent.com/6351754/88583366-25ccda80-d01e-11ea-8438-c3d270c951dd.png">


> existing
<img width="377" alt="Screen Shot 2020-07-27 at 3 30 00 PM" src="https://user-images.githubusercontent.com/6351754/88583380-29f8f800-d01e-11ea-91ba-5abce31b5521.png">

**Comment by fcoveram** [comment]
As @zackkrida said, the extra left and right spacing are truly important. They give the alignment effect when is placed above/below paragraphs. Thank you both.
