### ISSUE TITLE
Contrast Issue of Image caption

### ISSUE THREAD

**Issue by ayanchoudhary** [cc-archive/vocabulary-legacy#475]
## Problem

![84492393-beec9f80-acc3-11ea-956e-ea22f1874dc1](https://user-images.githubusercontent.com/45792768/84813316-699af000-b02d-11ea-8550-c89d45d1868d.png)

## Description

This one is kind of weird because it triggered lighthouse to give a contrast ratio error while the same did not happen with accessibility insights or pa11y. On checking with the chrome devtools contrast checker the ratio turned out to be **21.0** which is excellent. So this is up for discussion.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by ayanchoudhary** [comment]
@panchovm @dhruvkb

**Comment by zackkrida** [comment]
I think we leave these as is, I verified as well that the contrast is sufficient manually.
