### ISSUE TITLE
Updates to Vocabulary buttons

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#48]
**Description**
We need to make a series of updates to the Buttons in Vocabulary.

There should only be four button styles in Vocabulary:
- Primary
- Secondary
- Tags
- Donate

We should use Knobs to manage the: color, size, font style for _all_ buttons except tags. Tags should allow for changes to size and font style, but not color, they should always be White and Gray (gray on hover). The choices for color should be tomato, forest green, gold, and white. Buttons with a white background selected should always have a grey border that matches the grey color of the text.

We need to define which hover color matches which color. Using Knobs allows us to not have many versions of the same button predefined, and gives maximum flexibility.

Note, @panchovm will write up definitions of which hover colors match which brand colors, so this current ticket cannot be completed until https://github.com/creativecommons/vocabulary/issues/49 is completed.

**Comment by annatuma** [comment]
@brenoferreira do not start work on this until you see that https://github.com/creativecommons/vocabulary/issues/49 is complete.

**Comment by fcoveram** [comment]
The **blocked tag** has been removed. The new Forest green color for interaction is up to date. Now you can start @brenoferreira

**Comment by tinaShyp** [comment]
Hi, my name Tina. I am an Outreachy applicant for May 2020. I would like to work on this issue, if it's still available?

**Comment by dhruvkb** [comment]
@tinaShyp the `Button` component has been developed. You could help write MDX stories to illustrate all the forms of the button as seen in Figma.

**Comment by kgodey** [comment]
Reopening this issue since buttons in Vocabulary/Figma are not in sync. Currently we don’t have all the buttons in Figma available in Vocabulary, and we have some extra buttons in Vocabulary that are not in Figma and should be removed.

**Comment by kushaggarwal** [comment]
If this issue is open can I attend to this 
@dhruvkb @kgodey please help

**Comment by dhruvkb** [comment]
@kushaggarwal this issue might move slowly due to feedback-update iterations with Francisco. I've shared a different issue with you that's good for new contributors.

**Comment by kushaggarwal** [comment]
Okay @dhruvkb will go for the issue as guided by you.
Thank you very much for your help

**Comment by rochisha0** [comment]
Can this issue now be addressed?
