### ISSUE TITLE
Fix wobbly animation in Global Header

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#481]
## Description
To open and close, the Global Header changes three CSS properties between the `.is-active` and normal (inactive) states:
- `max-height`
- `padding-top`
- `padding-bottom`

These properties transition from different values to zero in the same amount of time making the animation slow down and speed up instead of smoothly maintaining speed throughout.

## Reproduction

1. Open the Global Header, observe carefully.
2. Close the Global Header, observe carefully.
3. Repeat till you...
4. ..see error.

## Expectation
The animation should be smooth and maintain consistency in speed.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by arushivii** [comment]
Can I take this?

**Comment by arushivii** [comment]
I think applying `transition-delay` with different timings to the properties might work. Should i go forward?

**Comment by dhruvkb** [comment]
That might not adequately fix the issue because the height of the header changes with screen width.

**Comment by zackkrida** [comment]
It would likely be best to refactor the animation to use translations (`transform: translate`) for animation instead of height and padding properties as well, for performance purposes. 

https://csstriggers.com/

**Comment by chidexebere** [comment]
Because of the way the header was built, `transform: translate` is not working ( from what I tried) but I noticed that changing the "global-header-content" transition from `transition: all 0.4s ease-in` to `transition: all 1s ease` reduces the wobbliness.

**Comment by zackkrida** [comment]
@chidexebere that's good for now then, feel free to make a pull request. thank you!
