### ISSUE TITLE
Image component demonstrating "selected" state 

### ISSUE THREAD

**Issue by makkoncept** [cc-archive/vocabulary-legacy#483]
## Problem

The [Mockup](https://www.figma.com/file/nJk4krHryIjzYGvaioMsAu/Browser-extension?node-id=892%3A4562) of CC Search extension indicate "selected" images as following:

![Screenshot from 2020-06-18 19-22-10](https://user-images.githubusercontent.com/34679965/85028694-06c66780-b199-11ea-89bc-b8d2e9b551ca.png)

I also have a question regarding this. Does it makes sense to add this to Vocabulary (maybe to fully cover the components used in the Mockup and therefore, finally in the extension itself) or is it to be implemented by the application? since, technically it's only a border around image component.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
Tagging @hugosolar for his opinion but I think this should be a part of Vocabulary as other apps might need the selected state too (can only think of the WordPress plugin at the moment).

**Comment by Dishebh** [comment]
@dhruvkb @makkoncept can I work on the issue?

**Comment by kgodey** [comment]
I agree that putting this in Vocabulary makes sense.

**Comment by hugosolar** [comment]
sorry for my late reply but yes, I think it make sense to putting it on Vocabulary.  also, I think it makes sense to use a `.is-selected` class (or something like that) in order to follow the bulma's naming convention

**Comment by makkoncept** [comment]
@dhruvkb Can I work on this?

**Comment by kgodey** [comment]
@makkoncept go ahead

**Comment by kgodey** [comment]
@makkoncept also, you don't need to ask permission for anything already assigned to you.
