### ISSUE TITLE
Define hover colors for buttons

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#49]
**Description**
Currently there is insufficient contrast for Tomato and Forest Green buttons, as shown in Figma DL.

Contrast for Gold and White is sufficient.

We need to change the contrast color for Tomato and Forest Green, before we can work on this ticket: https://github.com/creativecommons/vocabulary/issues/48

**Comment by annatuma** [comment]
@panchovm when this ticket is complete, go to https://github.com/creativecommons/vocabulary/issues/48 and remove the "blocked" tag and leave a comment for Breno to indicate he can start work on that ticket. Thank you!

**Comment by fcoveram** [comment]
I checked the contrast of Tomato with @hugosolar and worked well in code. The problem was Figma's color rendering. In the case of **Forest Green**, I defined a new color that is now available on Design Library. I will create a ticket.
