### ISSUE TITLE
Add removable tag component

### ISSUE THREAD

**Issue by krysal** [cc-archive/vocabulary-legacy#493]
## Description
This is a feature request to add the **Removable tag** button as showed in the [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=1404%3A1).

![removable tag](https://user-images.githubusercontent.com/9145885/85631715-0bc96200-b644-11ea-8123-c210b2ad7522.png)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by hugosolar** [comment]
@krysal take a look of [Bulma's tag list](https://bulma.io/documentation/elements/tag/#list-of-tags) maybe you can work with that example

**Comment by chidexebere** [comment]
Using Bulma's tag list will require a lot of overides to achieve what is specified in the design doc. 
I used cc's font with little css. 
Will make a PR shortly.

**Comment by krysal** [comment]
@chidexebere great! Thank you so much for you help. I will unassign me to let you take this :)
