### ISSUE TITLE
Improper padding between tech stack labels - Project Index card.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#499]
## Description

When the number of labels increases, there is a need for vertical padding between the labels in project index card.
![image](https://user-images.githubusercontent.com/34674462/86244209-3deb3e80-bbc5-11ea-81de-2e5c11f71014.png)

## Reproduction

1. Go to [storybook](https://cc-vocabulary.netlify.app/?path=/story/layouts-cards--project-index)
2. See error.

## Expectation

There should be vertical padding.

## Environment

 - Device: laptop
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 75

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by chintu-stacks** [comment]
HY @Dhruvi16  , i am meet the all environment ,
,now going  through the .SCSS file if  any builded class  there to resolve or not 
, or write new class,

please assigned me this issue
