### ISSUE TITLE
Convert the colors to an HSL-based implementation

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#5]
Currently all our of [color tokens](https://opensource.creativecommons.org/cc-vocabulary/styleguide/#/Tokens/Colors) are defined as fixed [hexadecimal values](https://github.com/creativecommons/cc-vocabulary/blob/master/src/tokens/color.yml) taken from a [Wiki entry](https://wiki.creativecommons.org/wiki/Colors) written all the way back in 2014.

Hex values are notoriously human unreadable and are difficult to manipulate via preprocessor tricks. Making a color lighter or darker is only a matter of adjusting lightness in HSL whereas accomplishing the same with hex codes or RGB is near impossible. This [StackOverflow answer](https://stackoverflow.com/a/43795837/2601645) makes an excellent case for HSL colors and many other design systems are already on an HSL scale.

This is for now a design issue but once an agreeable collection of colors is arrived at, this will require a major rewrite of tokens and associated styles. The goal is to develop a new color palette using a consistent HSL logic. Keeping it as close to the current one as possible or not is again a deep design question.

**Comment by kgodey** [comment]
Will this issue be updated with the new colors we decided on?

**Comment by dhruvkb** [comment]
We haven't decided on new functional hues as far as I'm aware. Removing the shades of the brand colours, leaving only the _default_, is on the roadmap. Tagging @panchovm to initiate a discussion on a new _shaded_ functional colour palette.

**Comment by fcoveram** [comment]
For now, we only need to update the brand colors. The possible shades of brand colors and grayscale are still in discussion and will be defined after testing CC Search with users.

**Comment by kgodey** [comment]
I think we're going to need some functional colors sooner for @hugosolar's work on the various website redesigns.

**Comment by fcoveram** [comment]
I understand. We can start trying new variations for the websites and then arrange a session to make definitions about which ones include or eliminate. It is essential to start from the look and feel based on the style guide document instead of a technical definition. In that form, we will achieve the design consistency desired.

**Comment by kgodey** [comment]
Sounds good. @hugosolar, please go ahead and use whatever colors you think make sense for now and we can discuss and add to Vocabulary once you have a first version done.

**Comment by dhruvkb** [comment]
Can we use the old colours as our interim functional palette? There were [some really nice ones](https://github.com/creativecommons/vocabulary/issues/4#issuecomment-548341902) in that set.

**Comment by kgodey** [comment]
What would the utility of an _interim_ functional palette be?

**Comment by dhruvkb** [comment]
I am under the impression that having a clearly separate palette would allow @chidexebere to begin working on Outreachy (starting with creativecommons/vue-vocabulary#6) without the constant threat of his efforts getting overwritten, or worse invalided, by another round of breaking changes in the way we organise our colours.

Having an interim palette with placeholder colours allows us, specifically him, to build stories for components with a future-ready approach. Replacing colours as they are confirmed would be much easier than redoing a lot of the work while having to coming up with an infrastructure afterwards.

**Comment by kgodey** [comment]
That makes sense. Feel free to use an interim palette of your choice, but please mark it clearly as interim.

**Comment by dhruvkb** [comment]
Issue #7 more accurately represents the end goal, plus a lot of the concepts in this issue statement here are misguided.
