### ISSUE TITLE
Add Form elements to Vocabulary

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#50]
**Description**
We want to create a Form element in Vocabulary that includes styles for Checkbox, Text Input, and Select per the Figma DL.

We should use Bulma styles if we can.

Figma DL:
https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A250

**Comment by fcoveram** [comment]
The form page in Design Library has been updated with the above changes

**Comment by Siyubu** [comment]
I am Solange, an Outreach applicant. I would want to work on this

**Comment by dhruvkb** [comment]
@brenoferreira I believe you are working on this with PR #169. If possible could you help @Siyubu find some way to contribute?

**Comment by krysal** [comment]
Hi! I can work on add styles for checkbox, could I take this?

**Comment by annkawira** [comment]
l am Ann, am an outreach applicant.l would love to work on this

**Comment by dhruvkb** [comment]
@krysal @annkawira I'm sorry this issue doesn't have any work to be done. We've decided to keep the checkbox to the OS default and input and select fields have already been implemented.
