### ISSUE TITLE
Add Content component.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#504]
## Problem

There is a need to add [.content](https://bulma.io/documentation/elements/content/) class (present in Bulma) for styling the markdown as per new mock-ups for CCOS.

## Description

This is the easiest way to handle markdown padding and spacing. So I guess we need to add it.

## Additional context

Scope of the component to be discussed.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Dhruvi16** [comment]
@panchovm, @hugosolar tagging you both for discussion.

**Comment by Dhruvi16** [comment]
For reference, you can see the chat here @panchovm - [link](https://github.com/creativecommons/creativecommons.github.io-source/pull/317)

**Comment by hugosolar** [comment]
I don't see any problems with adding this. I think it would be better to use the Bulma's support for content.

**Comment by fcoveram** [comment]
Regarding design, I either don't see any problem.

**Comment by Dhruvi16** [comment]
So we would need a component right? or should I only add the sass file?

**Comment by hugosolar** [comment]
> So we would need a component right? or should I only add the sass file?

I would say just go ahead and add it, it shouldn't be that different because we're rewriting bulma's variables. Let's try by adding the file and check if there are significant changes
