### ISSUE TITLE
Add DarkInfo and LightInfo to Colors

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#505]
We're missing DarkInfo and LightInfo (two shades of blue) from the Design Library in Vocabulary. LightInfo is being used in the License Redesigns, and this should therefore be prioritized.

[Feedback colors in Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=437%3A55)

**Comment by Dhruvi16** [comment]
Hey @annatuma! There is already an open issue and an approved PR on this - #491.

**Comment by Dhruvi16** [comment]
It needs to be merged though. @hugosolar @dhruvkb

**Comment by annatuma** [comment]
My bad! Closing this duplicate ticket.
