### ISSUE TITLE
Document Vocabulary project, sprint planning workflow etc.

### ISSUE THREAD

**Issue by kgodey** [cc-archive/vocabulary-legacy#510]
## Problem
We should add information about the Vocabulary project (https://github.com/orgs/creativecommons/projects/13), our sprint planning workflow, etc. in the public documentation for this project.

**Comment by nimishbongale** [comment]
@dhruvkb @zackkrida 

I think I'd need some more clarification on this issue. 🤔 

Vocabulary now has the landing site. I'm in the process of raising PR's for the docs revamp in our storybooks. Should the sprint planning workflows be a part our storybook as well?

**Comment by zackkrida** [comment]
Hi @nimishbongale this is an older issue so don't worry about it yet. I'll talk with @kgodey to review her thoughts on this.
