### ISSUE TITLE
Add "Info" Color to Vocabulary Library 

### ISSUE THREAD

**Issue by Audiosutras** [cc-archive/vocabulary-legacy#511]
## Problem

Info color currently is not supported on `cc-vocabulary`. 
### Actual 
![Screen Shot 2020-07-16 at 5 36 52 AM](https://user-images.githubusercontent.com/37882933/87656099-0c2ab980-c727-11ea-9cd9-381e592f9946.png)

### Figma ScreenShot
![Screen Shot 2020-07-16 at 5 39 34 AM](https://user-images.githubusercontent.com/37882933/87656113-1056d700-c727-11ea-9e63-f3611a7775cf.png)

**Comment by kgodey** [comment]
@Audiosutras I think this may have been fixed by https://github.com/creativecommons/vocabulary/issues/491 and published in yesterday's release, could you check?

**Comment by Audiosutras** [comment]
Great I see that this has been added to the library. Thanks everyone.
