### ISSUE TITLE
Add "Reverse" Buttons to Vocabulary Library 

### ISSUE THREAD

**Issue by Audiosutras** [cc-archive/vocabulary-legacy#512]
## Problem

"Reverse" Buttons should have the opposite background-color/color scheme (and hover functionality) as the buttons currently being supported.

### Actual
![Screen Shot 2020-07-16 at 5 45 01 AM](https://user-images.githubusercontent.com/37882933/87656785-ef42b600-c727-11ea-80c2-2021a86afc01.png)

### Figma Screenshot
![Screen Shot 2020-07-16 at 5 45 15 AM](https://user-images.githubusercontent.com/37882933/87656821-f8338780-c727-11ea-9a10-ac8620d5b240.png)

**Comment by zackkrida** [comment]
@Audiosutras thank you for sharing this! We will try to get this in the next vocabulary release. I am curious, ~could you tell me which figma mockup is using these button styles~? **Edit: I found it, the licenses** I'd like to take a look. Thank you 😸 !

**Comment by zackkrida** [comment]
@panchovm, this "see the legal code" button style: https://www.figma.com/file/k2XxlRS0JpII6NXDd3K1zc/Mockup?node-id=395%3A128

Is this in the design language yet?

To me, it also looks very similar to the disabled style here: https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A222

I just want to clarify before I have someone build this—thank you for your insight!

**Comment by fcoveram** [comment]
It is pretty similar @zackkrida and the decision was because stakeholders did not want to highlight much that area. But it might be confusing if it looks similar to the disabled state. I will ask and back to this issue with a clear response.

**Comment by fcoveram** [comment]
Problem solved. Let's use the `SmallBorder` style indicated in the Design Library.

**Comment by zackkrida** [comment]
Okay @Audiosutras you can use the `SmallBorder` style button in your project, and I will close this issue. Thanks @panchovm!
