### ISSUE TITLE
Add "exclamation icon" to Vocabulary icons

### ISSUE THREAD

**Issue by Audiosutras** [cc-archive/vocabulary-legacy#514]
## Problem

Suggested class: `exclamation icon`

### Figma
![Screen Shot 2020-07-16 at 6 00 17 AM](https://user-images.githubusercontent.com/37882933/87658172-d0ddba00-c729-11ea-89ac-9ea2dbcc947a.png)
![Screen Shot 2020-07-16 at 6 00 05 AM](https://user-images.githubusercontent.com/37882933/87658177-d3401400-c729-11ea-9511-3ebf1e65a224.png)

**Comment by kgodey** [comment]
Thanks for reporting this, @Audiosutras! I'm going to close in favor of https://github.com/creativecommons/fonts/issues/106

**Comment by Audiosutras** [comment]
Thanks @kgodey
