### ISSUE TITLE
Better documentation for colors built atop Bulma

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#516]
## Problem
As #412 and #515 indicate, the documentation for the use of colors is lacking and doesn't clearly indicate that the helpers provided by Vocabulary are intentionally limited to the brand colors because the same for other colors are already provided by Bulma. They might not work as intended as we have not comprehensively overridden Bulma's colors but that is a different issue altogether #425.

## Description
The solution must
- highlight the non-exclusive nature of these helpers
- point to Bulma's variable system and hint how our colors override theirs
- point how Bulma's helper classes can be used in a fashion complementary to ours

## References
Looping in @makkconcept, @kgodey, @zackkrida and @Audiosutras for reviews on potential PRs.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by kgodey** [comment]
tagging @makkoncept
