### ISSUE TITLE
Buttons should have `text-decoration: none` when interacted with

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#517]
## Description
Currently if button styles are applied to an `a` tag (a common practice), they may have an underline on hover that violates the Design Language.

## Reproduction

1. Create an anchor link button: `<a href="/" class="button">Button</a>`
2. Hover the button and observe underline

## Expectation
There is no underline

## Screenshots
<img width="177" alt="Screen Shot 2020-07-17 at 11 18 47 AM" src="https://user-images.githubusercontent.com/6351754/87802564-673fd780-c81f-11ea-80c5-e48fda38f9d4.png">

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by rochisha0** [comment]
Hey! I would be interested in resolving this bug? I am new to CreativeCommons.

**Comment by zackkrida** [comment]
Go for it @rochisha0, let me know if you have any questions.

**Comment by rochisha0** [comment]
Yeah sure! Thanks, @zackkrida
