### ISSUE TITLE
[META] Contrast Issues

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#519]
This is a parent issue to discuss color contrast issues regarding accessibility (a11y). Orange in particular is a very difficult color to reach proper AA contrast guidelines (in fact, a previous client of mine was sued under the ADA for issues with orange text on a white background).

Related issues are here:

- [ ] #454 
- [x] #474 
- [x] #472
- [ ] #473
- [x] #475
- [ ] #476

**Comment by Aakash2408** [comment]
Hey @kgodey @zackkrida are these issues still open for changes?
