### ISSUE TITLE
Implement Input variations from Design Language

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#520]
The Design Language specifies a number of input variations that we are missing:

- [x] Inputs with labels: https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=923%3A0 (fixed via: #532)
- [x] Inputs with names and descriptions: https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=7177%3A29 (fixed via: #522)
- [ ] Inputs with icons: https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=924%3A1626
  - This issue has a [related bug](https://github.com/creativecommons/fonts/issues/110)

These should be implemented in individual PRs referencing this issue.

**Comment by rochisha0** [comment]
Can I take up this issue @zackkrida?
