### ISSUE TITLE
Update responsive nature of Table Component.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#525]
## Problem

There is a need for an update in the responsive nature of the table component to make it more visible in smaller screens. As `table-container ` class from Bulma is not much of our use.
Referencing conversation - [Intern guide issue](https://github.com/creativecommons/creativecommons.github.io-source/pull/339#issuecomment-658979570) 
## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Dhruvi16** [comment]
Hey @hugosolar. I saw the code used here - https://codepen.io/team/css-tricks/pen/wXgJww?editors=1100 and checked out other such code too. And the idea here is they are adding a column(that consists of header) in every row through CSS and I don't think we can do that because the header will be different for every table.

**Comment by Dhruvi16** [comment]
I found this as a more usable solution - https://codepen.io/brunodplima/pen/rzpaLO

**Comment by Dhruvi16** [comment]
Tagging @dhruvkb @panchovm for their views

**Comment by zackkrida** [comment]
just chiming in, i tend to like tables on mobile that allow for horizontal scrolling and maybe have a 'fixed' header (it stays at the top even when there's more rows than the height of the screen).

this is a decent example functionality-wise: https://codesandbox.io/s/f71wj

**Comment by fcoveram** [comment]
I think the horizontal scroll adds complexity to the natural behavior of touch devices (vertical scroll). Besides, depending on device size, the visible area of the table might change too much.

**Comment by Dhruvi16** [comment]
> just chiming in, i tend to like tables on mobile that allow for horizontal scrolling and maybe have a 'fixed' header (it stays at the top even when there's more rows than the height of the screen).
> 
> this is a decent example functionality-wise: https://codesandbox.io/s/f71wj

Yes! more rows can be an issue if we agree to not have a `fixed` header. But the horizontal scroll is not working for the markdown table. So I am not sure how we solve this. And as @panchovm said horizontal scroll also adds complexity.

**Comment by Dhruvi16** [comment]
For more clarity, the problem was this - 
Bulma already provides us with the horizontal scroll but before the scroll comes into picture content is squeezed too much like this - 
![image](https://user-images.githubusercontent.com/34674462/87948849-dd179d80-cac2-11ea-95d2-3c6bea4cf272.png)

**Comment by hugosolar** [comment]
I think what @zackkrida says it makes sense for big tables but this is a small table with overflow text.
@Dhruvi16 you're right, I didn't check the code @panchovm sent, but it's not applicable to the tables built in Lektor.

I can think in something like this: https://get.foundation/sites/docs/table.html#stacked-table

see how the table transform on small screens, they just hide the table header and show the info as a stack, and the row is determined with the background color

**Comment by fcoveram** [comment]
I like that it is clean, but hiding the header might be confusing when having big amounts of data or multiple pages.

**Comment by Dhruvi16** [comment]
I agree with @panchovm on this. More rows can make it difficult for the user to access the desired data.

**Comment by kgodey** [comment]
We discussed during sprint planning. @panchovm is working on updating the design library.

**Comment by dhruvkb** [comment]
[Here](https://css-tricks.com/responsive-data-tables/) is a reasonable way to present tables on mobile devices using media queries.

**Comment by fcoveram** [comment]
I was **exactly** thinking on that @dhruvkb. Thanks. I will update the Design Library

**Comment by fcoveram** [comment]
[Here is](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=904%3A0&viewport=-851%2C93%2C0.5673556327819824) the responsive version of the table.
