### ISSUE TITLE
Migrate to Sass

### ISSUE THREAD

**Issue by brenoferreira** [cc-archive/vocabulary-legacy#53]
Stylus and its CSS3 extension compiler [Nib](http://stylus.github.io/nib/) don't seem to be so actively maintained. Moreover, many CC websites use Sass as their CSS preprocessor. To standardize, we decided to migrate away from Stylus and adopt Sass SCSS syntax for Vocabulary.

**Comment by chidexebere** [comment]
Can I take this up?

**Comment by dhruvkb** [comment]
@brenoferreira and @hugosolar can we start working on this making PRs component by component? We could start with `Button` since you've redesigned it according to @panchovm's specifications.

**Comment by kgodey** [comment]
No longer relevant with new repo changes, we've moved to Sass.
