### ISSUE TITLE
Add color tokens to Vocabulary

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#54]
**Reference**: "Color" page in our Figma Design Library: https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A72

We need to:
- Add all the color tokens under "Palettes" from the Design Library to Vocabulary so that they can be easily used in various components. We probably want Sass variables for these.
     - The token set names should match those in Figma (Brand, Neutral, Binary, Interaction, Feedback, etc.)
- Add the color usage guidelines as documentation to Vocabulary. This can take the form of embedding the Figma pages to avoid duplication.

**Comment by jahnvigupta** [comment]
I would like to take this issue.

**Comment by dhruvkb** [comment]
@jahnvigupta PR #161 already addresses this issue, so, I'm afraid you'll need to find another issue.
