### ISSUE TITLE
Unability to extend spacing tokens in the new version.

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#541]
## Description

Spacing tokens cannot be extended by only importing spacing sass files. To import spacing tokens, users will need to import `vocabulary.scss` and to make that work installation of Bulma is necessary which is not ideal. 

## Reproduction

1. Import spacing.scss and spacing_overrides.scss in the style files.
2. Extend any spacing taken
3. See error.

## Expectation

Spacing tokens should be available to extend without importing vocabulary.scss and installing Bulma.

## Environment

 - Device:  laptop
 - OS: Ubuntu
 - Browser:  Firefox
 - Version: 75

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by Dhruvi16** [comment]
Tagging @hugosolar @dhruvkb @zackkrida for discussion.

**Comment by zackkrida** [comment]
Hi @Dhruvi16, are you trying to do something like this in a `.scss` file?

```scss
@import "~@creativecommons/vocabulary/scss/spacing.scss";
@import "~@creativecommons/vocabulary/scss/spacing_overrides.scss";

$space-bigger: 200px; // silly example haha
```

What is the error you are seeing?

**Comment by Dhruvi16** [comment]
Hey @zackkrida! The problem I faced specifically was that after importing the spacing files, I was not able to extend spacing classes which I was able to do in the earlier versions. For example -
```
@import "~@creativecommons/vocabulary/scss/spacing.scss";
@import "~@creativecommons/vocabulary/scss/spacing_overrides.scss";

@extend .padding-big;`
```
This would throw an error.

**Comment by Dhruvi16** [comment]
For now, I have imported the vocabulary.scss file and installed Bulma to make the code run. But I think this is not the ideal way to do it, do you?

**Comment by zackkrida** [comment]
Hm, in a little test project I put together, this is working:

```scss
@import "~@creativecommons/vocabulary/scss/spacing.scss";
@import "~@creativecommons/vocabulary/scss/spacing_overrides.scss";

.purple-padded-big {
  @extend .padding-big;
  background-color: purple;
}
```

Are you working in an `.scss` file? Can I see your code online anywhere?

**Comment by Dhruvi16** [comment]
Yes! I am working on an .scss file in the CCOS project itself. But as I had to change the code last time it is not online. I will try this now on my local and get back to you. It was not working for 2020.7.2 lemme check with the new version.

**Comment by zackkrida** [comment]
Hi @Dhruvi16 let me know if you run into this again! Could you send a screenshot of the exact error if you do? Thanks!

**Comment by Dhruvi16** [comment]
Okay, this works in the latest version. So, I am closing this issue.
