### ISSUE TITLE
The homepage link is dead

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#545]
https://github.com/creativecommons/vocabulary/blob/96161ecca90bb71f72bf1cf0ca594b64531c756e/package.json#L55

This needs to be corrected in all three repos.

**Comment by zackkrida** [comment]
@dhruvkb fixed for this repo in #546 
FYI the redirect we added was from `opensource.creativecommons.org/vocabulary => https://cc-vocabulary.netlify.app`
