### ISSUE TITLE
Color of button during hover interaction

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#555]
## Description
When buttons use `Forest Green` as background color, the background color during hover interaction must be `Brighter Forest Green`. The Design Library has that color in the **Interaction** section.

<img width="153" alt="Screen Shot 2020-08-03 at 10 29 32" src="https://user-images.githubusercontent.com/895819/89193735-6ecbe400-d574-11ea-8187-bfd5d099ff08.png">

**Comment by kgodey** [comment]
@Dhruvi16 I transferred it to the Vocabulary repo.
