### ISSUE TITLE
Wrong spacing and text color in blog post

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#559]
## Description
Two problems were detected:
1. Wrong spacing between post title and the section where the author and date are displayed.
2. Wrong text color for the excerpt paragraph.

## Expectation
For each description
1. The space between sections indicated should be `8px`.
2. The text color for excerpt must be `Dark Slate Gray`.

## Screenshots
<img width="397" alt="Screen Shot 2020-08-03 at 11 02 15" src="https://user-images.githubusercontent.com/895819/89197064-28c54f00-d579-11ea-8e6d-89f903db5a49.png">

**Comment by fcoveram** [comment]
I reviewed it using the inspect tool and I found this:

## Implementation
<img width="475" alt="Screen Shot 2020-08-05 at 09 48 17" src="https://user-images.githubusercontent.com/895819/89420570-e4fd5180-d700-11ea-9075-d39329e85cbf.png">

## Mockup
As you can see in the image below, the **Auto Layout** has 8px distance.

<img width="1026" alt="Screen Shot 2020-08-05 at 09 48 06" src="https://user-images.githubusercontent.com/895819/89420605-f0507d00-d700-11ea-8d90-6457d4873c19.png">

**Comment by Dhruvi16** [comment]
Yes, but for space, I have given upper margin to the author text and not the heading.

![image](https://user-images.githubusercontent.com/34674462/89777146-cb0ca600-db28-11ea-8ea2-e4220961bca4.png)
