### ISSUE TITLE
The styles of a table doesn't follow the Design Library

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#561]
### Page: Projects (Project list)
The table has problems with the following styles:
1. Color of the line that divides columns
2. Font size in content

## Expectation
The style should be, based on prior points:
1. The color line should be `Light Gray`.
2. The font size of content should follow the `body normal` style.

## Screenshots
<img width="1285" alt="Screen Shot 2020-08-03 at 15 16 39" src="https://user-images.githubusercontent.com/895819/89218972-f3caf380-d59c-11ea-93f1-4461d7e43e6e.png">

**Comment by Dhruvi16** [comment]
I checked the DL and I saw the background color of even rows is `Lighter gray`

**Comment by fcoveram** [comment]
You are right. My mistake. Sorry about that. I will update the ticket by deleting that point.
