### ISSUE TITLE
Update the donate button

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#589]
## Description
We need to update the donate button in all its versions by replacing the current `CC heart` icon with `CC heart filled icon`. The [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A222&viewport=-799%2C40%2C0.7119097113609314) has been updated with this change.

### Mockup
<img width="467" alt="Screen Shot 2020-08-14 at 09 26 27" src="https://user-images.githubusercontent.com/895819/90254148-4cf21d00-de10-11ea-83fe-98a1e2b729d9.png">

**Comment by rochisha0** [comment]
Can I work on this @panchovm ?

**Comment by zackkrida** [comment]
You can do it @rochisha0!

**Comment by rochisha0** [comment]
@zackkrida I think [this](https://github.com/creativecommons/fonts/issues/124) has to be fixed first?

**Comment by zackkrida** [comment]
@rochisha0 Yes. I'll mark this as blocked until [#124](https://github.com/creativecommons/fonts/issues/124) is resolved.

**Comment by dhruvkb** [comment]
@zackkrida this is ready for development. Please feel free to take this up or assign to @rochisha0 as you see fit.

**Comment by Aakash2408** [comment]
@dhruvkb  can i do this :) ?

**Comment by dhruvkb** [comment]
@Aakash2408 please wait for @zackkrida to re-triage this.

**Comment by zackkrida** [comment]
Hi @rochisha0 you and/or @Aakash2408 can both start working on this if you like. I'll assign it to you both; thanks!
