### ISSUE TITLE
Add Hoverable and Circleable styles to Figma DL

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#59]
**Description**
We have this in Vocabulary, and it needs to match in Figma:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/elements-imageview--scaled

**Comment by fcoveram** [comment]
The hoverable image has been created on a new page, called **Images**, in Design Library. The circleable image is a Figma's feature that can not be blocked
