### ISSUE TITLE
Automate style compilation and script minification

### ISSUE THREAD

**Issue by hugosolar** [cc-archive/vocabulary-legacy#6]
**Description**
Use gulp or another automation tool to :

- Compile stylus global file
- Watch stylus files when style changes were made
- Minify and concatenate JS files

**Comment by dhruvkb** [comment]
The 'build' part of the task been accomplished with e3fb559. Setting up Stylus to run with watch and auto-rebuild is already a part of the [Stylus CLI](http://stylus-lang.com/docs/executable.html) using the `-w` flag so no Gulp pipeline is required for this.
