### ISSUE TITLE
Better docs for release process

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#602]
[will add info here]

**Comment by dhruvkb** [comment]
I may be wrong but I don't think this is something that should be a part of the repository, least of all in the public documentation for the project. When just a couple of people have deployment access, I believe that it's just a matter of understanding the automation, and maybe one or two deployments to internalise the process.

In my (limited) experience, no repo I've seen does this. A wiki page, perhaps, would be a better solution to this?

**Comment by zackkrida** [comment]
@dhruvkb I completely agree, I just put the issue here so i would remember. A wiki page seems the most appropriate to me.

**Comment by nimishbongale** [comment]
@zackkrida 

Maybe I can take this up? 🤔 

Not sure if it lies within the scope of my GSoD internship or not, but yeah!

**Comment by zackkrida** [comment]
@nimishbongale thank you, but I don't think you'l be needed for this. I'm going to write some small instructions in the CC internal wiki regarding releases 👍

**Comment by nimishbongale** [comment]
> @nimishbongale thank you, but I don't think you'l be needed for this. I'm going to write some small instructions in the CC internal wiki regarding releases 👍

Alright, sounds good! 👍

**Comment by brylie** [comment]
@dhruvkb, did you end up creating the wiki document? Would you mind outlining here the steps to publish new versions of the Vocabulary packages?

**Comment by possumbilities** [comment]
This project is moving towards being archived, and this item is no longer on the roadmap. Closing
