### ISSUE TITLE
Eliminate the "current" label of language in locale component

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#603]
## Description
We need to eliminate the `current` label when indicating the language in the locale component. We only need to show the `native` label of the language as the following mockup shows

<img width="497" alt="Screen Shot 2020-08-21 at 12 52 54" src="https://user-images.githubusercontent.com/895819/90915260-3e29de00-e3ad-11ea-97e7-1945a599f301.png">

The [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=753%3A0&viewport=250%2C45%2C0.6832239627838135) has been updated with this change.

**Comment by dhruvkb** [comment]
@panchovm what do you mean by "eliminate the `current` label"? @rochisha0, your PR removes the Anglicised name of the languages but I'm not sure if it addresses this part of the issue.

**Comment by zackkrida** [comment]
@dhruvkb "current" means "Anglicised" in this case. The original idea of showing the "Anglicised" version was to show whatever language was _currently active_ next to the native language name. Given this info @rochisha0's PR looks correct.
