### ISSUE TITLE
Changes to Form Elements

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#61]
**Description**
1.  Create Disabled Text Input:
We are missing the Disabled state from here:
https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A250
It needs to be added.

2. Create Hover version of Text Input.

**Comment by annatuma** [comment]
Leave comments on these tickets indicating unblocked, when this ticket is complete:
https://github.com/creativecommons/vocabulary/issues/50
https://github.com/creativecommons/vue-vocabulary/issues/117

**Comment by fcoveram** [comment]
Done. The new form page is available on Design Library
