### ISSUE TITLE
Hover color for `info` buttons

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#616]
The blue info buttons do not have a hover color. We need to add a new color.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by iamabhi222** [comment]
i think this issue has been resolved plz mark it closed.

**Comment by zackkrida** [comment]
Hi @iamabhi222 (and cc-ing: @panchovm), see how the hover color is green in this button?

https://cc-vocabulary.netlify.app/?path=/story/elements-buttons--button-info

We're going to replace this soon with new, updated colors (blue, not green). That's what this issue is for!

**Comment by iamabhi222** [comment]
can i get the on hover hex-code for the color?

**Comment by Cronus1007** [comment]
@zackkrida  Since the color transition has been made. So I will like to implement this issue.

**Comment by Cronus1007** [comment]
@nimishbongale I think that this link https://cc-vocabulary.netlify.app/?path=/story/elements-buttons--button-info reflects that stories are missing for the `info-button`.

**Comment by nimishbongale** [comment]
> @nimishbongale I think that this link https://cc-vocabulary.netlify.app/?path=/story/elements-buttons--button-info reflects that stories are missing for the `info-button`.

The info button existed as a separate story then @Cronus1007. Now the info button is a part of this story [https://cc-vocabulary.netlify.app/?path=/story/elements-buttons--button-feedback-types](https://cc-vocabulary.netlify.app/?path=/story/elements-buttons--button-feedback-types).

**Comment by Cronus1007** [comment]
@nimishbongale I think that this issue has been fixed since button with the class `.is-info` button already have a hover-color. So we can close this issue.
