### ISSUE TITLE
[Fonts] Add RSS icon 

### ISSUE THREAD

**Issue by Dhruvi16** [cc-archive/vocabulary-legacy#617]
## Description

We need to add an RSS icon to the library. Reference [Conversation](https://github.com/creativecommons/creativecommons.github.io-source/issues/475#issuecomment-679148676)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Dhruvi16** [comment]
@panchovm tagging you for an update in Figma.

**Comment by zackkrida** [comment]
Thank you for remembering this @Dhruvi16 😃

**Comment by Dhruvi16** [comment]
Yeah! I completely forgot about this during the call.

**Comment by fcoveram** [comment]
Perfect. I just updated [the Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A135&viewport=173%2C181%2C0.5804159641265869). The icon is `RSS square` in [Fontawesome](https://fontawesome.com/icons/rss-square?style=solid).

**Comment by Dhruvi16** [comment]
Thanks! @panchovm
