### ISSUE TITLE
Grid/Page Layout Documentation

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#619]
We should add documentation on the [grid pages](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=4325%3A1) of the design library.

This will help users lay out sites and pages in accordance with our grid. We can also mention the responsive breakpoints we use in Voabulary.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by fcoveram** [comment]
On each breakpoint mockup, I put some basic indication about the grid. What else do you think we need there?

**Comment by zackkrida** [comment]
@panchovm the design library is excellent and doesn't need anything; I'm talking about adding a section to the web site https://cc-vocabulary.netlify.app/ with some examples on the grid css classes, how to lay out a page, and things like that.

**Comment by nimishbongale** [comment]
@zackkrida I thought of adding this as a `GRIDS` component itself to the `LAYOUT` elements.

Would love to hear your inputs!

**Comment by zackkrida** [comment]
@nimishbongale I'd be open to some grid components too! That would be great.
