### ISSUE TITLE
Add GitHub Corners to Figma DL

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#62]
**Description**
We want to:
Add GitHub Corners into Figma DL, based on what is in Vue Vocabulary, with the following exceptions:

-  Remove the Branded and Colored options.
- Maintain Black on White, or White on Black
- Maintain Corners (they can be left or right).
-  Remove Positions.

See: https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/elements-githubcorner--branded

Related ticket: creativecommons/vue-vocabulary#118

**Comment by fcoveram** [comment]
Done. The components are available in Design Library
