### ISSUE TITLE
Update the shared image to show CC logo

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#621]
## Problem
CC sites are not consistent when showing the shared image on social media posts.

## Description
For this first version, we decided to show one single image with the CC logo for all CC sites. Here is attached the JPG file following the [Linkedin recommendations](https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin?lang=en).

[cclogo-shared-image.jpg.zip](https://github.com/creativecommons/vocabulary/files/5143208/cclogo-shared-image.jpg.zip)

Thanks @zackkrida for bringing this

**Comment by ooyeraju** [comment]
can I take this?

**Comment by dhruvkb** [comment]
@zackkrida can your card-image generator be incorporated into this task?

**Comment by zackkrida** [comment]
@dhruvkb, Francisco's image is a temporary measure until that tool is complete. I asked him to make it

**Comment by ooyeraju** [comment]
I couldn't find the file where I need to make these changes. Can someone please guide me?

**Comment by zackkrida** [comment]
@ooyeraju We need a meta tag for `og:image` set in [_this file_](packages/vocabulary/.storybook/manager-head.html).
