### ISSUE TITLE
[Fonts] New icon needed: Plain heart

### ISSUE THREAD

**Issue by chidexebere** [cc-archive/vocabulary-legacy#628]
## Description

We need a `plain heart icon` to use in the donate button of the new vocabulary header component.  [See Design library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=8439%3A299)

![donate1](https://user-images.githubusercontent.com/25040059/91962170-12d7b500-ed04-11ea-9afa-8d1875d9d83f.png)

hover state
![donnate2](https://user-images.githubusercontent.com/25040059/91962186-179c6900-ed04-11ea-89d4-e3b9669a029d.png)

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by sujal111** [comment]
I am willing to work on this issue

**Comment by kgodey** [comment]
go ahead @sujal111

**Comment by kgodey** [comment]
This is blocking the new header.
