### ISSUE TITLE
Add LicenseIconography to Vocabulary

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#63]
**Description**
We want to add the LicenseIconography element, currently in Vue Vocabulary, to Vocabulary.
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/elements-licenseiconography--creative-commons

Once we have added this element and associated styles into Vocabulary, we'd like to do the following:

1. Break each icon into individual Styles, to match the Downloads page:
https://creativecommons.org/about/downloads
2. Add the LicenseBadge (within Patterns) from Vue Vocabulary as a page in License Iconography in Vocabulary.

That is, the new License Iconography page in Vocabulary should contain the elements from License Iconography in Vue Vocabulary, as well as the License Badge patterns from Vue Vocabulary.

**Comment by dhruvkb** [comment]
`LicenseIconography` was actually just a wrapper on `FontAwesomeIcon`, so it cannot have a counterpart in Vocabulary. `LicenseBadge` assets can definitely be added to Vocabulary though, in a manner similar to the product logos.

**Comment by Dhruvi16** [comment]
Hey! Can I take this up?
Thank you

**Comment by dhruvkb** [comment]
@Dhruvi16 the `LicenseIconography` part is still under discussion so it's not ready for work. Feel free to take up `LicenseBadge` though.

**Comment by Dhruvi16** [comment]
Cool! Will start working on `LicenseBadge`. But I guess this link - https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/elements-licenseiconography--creative-commons isn't working. And seeing cc-vue-vocabulary storybook there is only one Github link story. Could you help me with that? @dhruvkb 
Thank you!

**Comment by dhruvkb** [comment]
The stories in Vue Vocabulary have been taken down so as to avoid confusing caused from seeing two versions of a component (Vocabulary showing the new version and Vue Vocabulary showing the old ones). The stories are still present in the code though.

@Dhruvi16 please see #131 for an example on adding assets and using them in stories.

**Comment by guArroyo** [comment]
Hello! Outreachy applicant here. Can I also work on this as a contribution? Thanks

**Comment by dhruvkb** [comment]
Sure @guArroyo we use the [brand icons from Font Awesome](https://fontawesome.com/icons?s=brands) for the license icons. The output of this issue will be similar to that of #95.

**Comment by Emuohwo** [comment]
@dhruvkb I am seeing multiple contributors badge.  can I join the existing contributor on this issue?

**Comment by dhruvkb** [comment]
Yes @Emuohwo. Can you split the work between yourself and @guArroyo?

**Comment by jahnvigupta** [comment]
@annatuma as per my understanding, The issue requires to put images of icons given onhttps://creativecommons.org/about/downloads   and make a section for patterns in which all the  components images given in pattern section https://cc-vocabulary.netlify.com/?path=/docs/assets-logos--cc-logomark have to be put.  Correct me if I am wrong and guide me to the source of svg images.

**Comment by dhruvkb** [comment]
@jahnvigupta the icons for the licenses were added as an icon font in creativecommons/fonts#8. To resolve this issue, one needs to showcase the license icons here. But since this issue hasn't seen a week of inactivity, I would urge you to wait a couple of days before attempting to solve it.

**Comment by jahnvigupta** [comment]
@dhruvkb Please assign me this issue.

**Comment by jahnvigupta** [comment]
> @jahnvigupta the icons for the licenses were added as an icon font in [creativecommons/fonts#8](https://github.com/creativecommons/fonts/pull/8). To resolve this issue, one needs to showcase the license icons here. But since this issue hasn't seen a week of inactivity, I would urge you to wait a couple of days before attempting to solve it.

I thought to solve it copying and pasting following files from fonts to vocabulary
vocabulary_icons.scss
vocabulary_icons.stories.mdx

but that is not working, am I heading in the right direction?

**Comment by dhruvkb** [comment]
@jahnvigupta along the lines of creativecommons/fonts#14, you need to make an MDX document with the `IconGallery` except this time only with the CC license icons.

**Comment by dhruvkb** [comment]
This task is covered under #95.
