### ISSUE TITLE
Consistency of information in all package.json files

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#635]
The author information in the root `package.json` file
https://github.com/creativecommons/vocabulary/blob/b1a0ca701b02beedd9f556ccc6f250f4b1ac02fd/package.json#L5
is different from the same in the `package.json` files of all packages
https://github.com/creativecommons/vocabulary/blob/b1a0ca701b02beedd9f556ccc6f250f4b1ac02fd/packages/vocabulary/package.json#L5

Should change either one to the other for consistency.

**Comment by zackkrida** [comment]
I think the author being 'Creative Commons' is most appropriate. Will fix.
