### ISSUE TITLE
[Fonts] New icon: bars

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#640]
## Description
We need to add a new icon for burger menu in the mobile header. The icon is called `bars` and is available on Fontawesome. [The Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A135&viewport=348%2C-52%2C1) has been updated with this change.

<img width="166" alt="Screen Shot 2020-09-07 at 10 48 03" src="https://user-images.githubusercontent.com/895819/92394272-a12eab00-f0f7-11ea-9cea-0d07b69154c0.png">

https://github.com/creativecommons/vocabulary/blob/8973dac8c635b018cab568d6d390c2fb9ab0195b/package.json#L1

**Comment by kgodey** [comment]
This is related to the new header.
