### ISSUE TITLE
[Fonts] New icon: Envelope

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#643]
## Description
We need to add an icon for OpenGLAM project. The icon is called **envelope**, available in Fontawesome and the [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A135&viewport=45%2C129%2C0.8880000114440918).

<img width="197" alt="Screen Shot 2020-09-09 at 12 15 08" src="https://user-images.githubusercontent.com/895819/92617838-1e902200-f296-11ea-86df-57812beeaa65.png">

**Comment by rahulkiller104** [comment]
i can do this

**Comment by rahulkiller104** [comment]
assign me this task

**Comment by rahulkiller104** [comment]
Hi  @kgodey , I want to work on this issue. Please assign me this task. And also tell me where to add this envelope icon. Thank you

**Comment by hugosolar** [comment]
Hey @rahulkiller104 
Go ahead and take the issue. You mus follow this [instructions](https://cc-fonts.netlify.app/?path=/docs/fonts-contribution--page) but now we're moving all the vocabulary repos to a monorepo so you need to work on this repo now because the font repo will be deprecated soon

**Comment by rahulkiller104** [comment]
@hugosolar thanks

**Comment by rahulkiller104** [comment]
@hugosolar  ok

**Comment by rahulkiller104** [comment]
can you tell me in which file this issue is present now

**Comment by rahulkiller104** [comment]
@hugosolar  can you explain to me a little bit more.Actually I am a beginner.

**Comment by hugosolar** [comment]
@rahulkiller104 besides the documentation link I sent you what else do you need to know?
You can check the fonts files here: https://github.com/creativecommons/vocabulary/tree/master/packages/fonts

**Comment by rahulkiller104** [comment]
@hugosolar  can you tell me where to add this envelope icon?
