### ISSUE TITLE
Update logos in individual package READMEs

### ISSUE THREAD

**Issue by nimishbongale** [cc-archive/vocabulary-legacy#646]
## Description
The logo appears to be broken in `packages/vocabulary/README.md`. Maybe the individual packages need their own logos? (just like fonts, sort of). Currently, the Vue-Vocabulary logo seems indistinguishable from Vocabulary's to me.

## Screenshots
![attachissue](https://user-images.githubusercontent.com/43414361/92642652-284d7000-f2fe-11ea-8ca0-8fbff82bab30.PNG)

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
@nimishbongale the file paths are probably incorrect. we should be able to keep the same logos we had but fix the paths.

**Comment by dhruvkb** [comment]
@nimishbongale it's safe to say that we are converging Vocabulary, Vue Vocabulary and Fonts into just "Vocabulary" so it makes sense for all three to share the same visual identity. In fact, we could, with some tweaks, just use the same `README.md` for all three, placed in the root directory.

**Comment by nimishbongale** [comment]
Yes. One main `README.md` also makes perfect sense. Will sort this out.

**Comment by zackkrida** [comment]
We'll want multiple readmes still, for the sake of npm.

**Comment by dhruvkb** [comment]
@zackkrida our build process actually copies the `README.md` file into the `dist/` directory. 
https://github.com/creativecommons/vocabulary/blob/d8ddde443e5dea7161259a5c68436e238151af50/packages/fonts/deploy.sh#L15
So a small tweak to the build script should allow us to unify them.

**Comment by zackkrida** [comment]
@dhruvkb that is quite cool! I was referring to the fact that they're still different mom packages and therefore have their own install scripts, which I suppose we could also do dynamically with a unified readme

**Comment by dhruvkb** [comment]
> they're still different mom packages and therefore have their own install scripts

I'm a little unclear on what this means.

**Comment by rahulkiller104** [comment]
can you tell me how to run this in local

**Comment by nimishbongale** [comment]
> can you tell me how to run this in local

@rahulkiller104

If I understand you correctly, you're looking to run the monorepo locally? You'd need to have node+npm installed. Then just run the following commands:

```js
npm install
npm run setup
npm run build
npm run storybook
```

This will soon be updated in the documentation.

**Comment by zackkrida** [comment]
> > they're still different npm packages and therefore have their own install scripts
> 
> 
> 
> I'm a little unclear on what this means.

**Comment by zackkrida** [comment]
@dhruvkb *npm packages. Weird typo!

**Comment by dhruvkb** [comment]
😂 I understood 'npm'. Didn't understand 'install scripts'.

**Comment by zackkrida** [comment]
I'm a mess today haha, ignore everything I've said. For some reason I was assuming we had like 'npm install package-name' in each readme 🤦‍♂️

**Comment by nimishbongale** [comment]
So to conclude, I think we just need one main `README.md` file in the root directory, and then make changes to our build process to just copy this main `README.md` into the `/dist` folder. 

@dhruvkb @zackkrida please confirm!

**Comment by rahulkiller104** [comment]
> > can you tell me how to run this in local
> 
> @rahulkiller104
> 
> If I understand you correctly, you're looking to run the monorepo locally? You'd need to have node+npm installed. Then just run the following commands:
> 
> ```js
> npm install
> npm run setup
> npm run build
> npm run storybook
> ```
> 
> This will soon be updated in the documentation.

@nimishbongale can I add these steps in README.md ??

**Comment by nimishbongale** [comment]
> @nimishbongale can I add these steps in README.md ??

This might've been done in [this PR](https://github.com/creativecommons/vocabulary/pull/649).
