### ISSUE TITLE
Switch dependabot PRs to monthly cycle

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#653]
We should change the interval of our dependabot PRs to `monthly`, to reduce the frequency with which we need to merge them.

---

> Original discussion below:

## Problem

We should automatically merge our dependabot PRs with passing checks, using the [merge me](https://github.com/ridedott/merge-me-action) GitHub Action.

This will cut down considerably on developer time each sprint.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by nimishbongale** [comment]
@zackkrida 

Sometimes, it so happens with dependabot that it says `code coverage - unknown` in its PR. I'm not sure if this affects anything at all, but this deters me from auto-merging a dependabot PR (in my other personal repo's). 

Although this may not be the orthodox way of solving this problem, I would suggest:

- **Changing the frequency of dependabot PR's** : Although it seems counter-intuitive, we could change the `interval: "weekly"` attribute in the `.github/dependabot.yml` to `monthly`. Most OSS organisations prefer having it monthly (afaik).
- **Limiting the PR's raised** : Dependabot raises 5 PR's per package manager atm. We could limit that as well, so it would raise 5 or less than 5 PR's in the specified package manager only.

**Comment by zackkrida** [comment]
@nimishbongale I'm a little skeptical of auto-merging too. The fact that our deployment process is manual makes me less skeptical, but I'll think about it more. I think your suggestions are good compromises.

**Comment by dhruvkb** [comment]
If we had automated visual testing, merging automatically would not be much of a question. But even in manual deployment, it isn't feasible to individually verify that everything is working as before (and this infeasibility only increases with more components being added to the package).

**Comment by zackkrida** [comment]
@dhruvkb Agreed. Like I said on the vocab call I think switching the interval to `monthly` like @nimishbongale is the best path forward.

**Comment by akmadian** [comment]
I can take this on. Is this change's scope only PRs in vocabulary or all CC repos?

**Comment by nimishbongale** [comment]
@akmadian

I think it was discussed particularly to do with vocabulary, as I'm not sure about the others (if they want the frequency to be changed ie.)
