### ISSUE TITLE
Implement prettier in the root for all packages

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#655]
## Problem

We would like to format all `.js`, `.vue`, `.css`, and `.md` files with [prettier](https://prettier.io), using the same config as CC Search. Note that this config will be part of CC's future [JS language guide](https://github.com/creativecommons/tech-support/issues/671)

```js
module.exports = {
  trailingComma: 'es5',
  tabWidth: 2,
  semi: false,
  singleQuote: true,
  vueIndentScriptAndStyle: false,
}
```

Now that there are very few active PRs, we should create one that implements prettier and formats all files.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by Mansibisen** [comment]
@zackkrida  I will like to take over this issue.

**Comment by nimishbongale** [comment]
> @zackkrida I will like to take over this issue.

I suggest we wait until zack's return before proceeding. I'm sure he has something in his mind to do with this issue!

You can however go ahead and raise a relevant PR if you wish.

**Comment by Mansibisen** [comment]
@nimishbongale Okay , then I will wait for  Zack . So that things are cleared and then I will start my work .

**Comment by Mansibisen** [comment]
@zackkrida  What is your status sir , How should I proceed with the PR ? Or I can go ahead with my Ideas?

**Comment by dhruvkb** [comment]
@Mansibisen it might be a while until Zack is back from vacation. Please feel free to work on a different issue in the meantime.

**Comment by Mansibisen** [comment]
@dhruvkb  Okay , Thanks a lot .
