### ISSUE TITLE
[Vue] `vue-vocabulary` 1.0 Release

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#667]
Our usage of CalVer aside, I'd like us to reach a metaphorical `1.0` with `vue-vocabulary`. To that aim, here is an outline of everything I'd like to accomplish _before_ that release:

## Housekeeping

- [x] Switch from storybook knobs to controls, implement for current components
- [ ] Compose with the main vocabulary storybook
- [x] Fix the netlify builds for the `vue-vocabulary` site (using netlify's built in monorepo support)
- [x] Add dark mode (because why not?)
- [ ] Improve existing 'mixins' to reflect current vocabulary tokens (may require some `vocabulary` cleanup)
- [x] Dynamically populate package `README.md`s with specific instructions for installation

## Components (will have their own tickets created and updated below)

[ticket work required]

**Comment by nimishbongale** [comment]
@zackkrida 

I think the `sed` operation that @dhruvkb talked about [here](https://github.com/creativecommons/vocabulary/pull/649#discussion_r486772565) can be a part of this issue as well! I guess it needs to be done before we publish any of the packages to `npm`.

**Comment by dhruvkb** [comment]
Yeah, it's a small change but will make the `npm` package `README.md` much better.

**Comment by Cronus1007** [comment]
@zackkrida For dark mode we can make a toggle switch type thing and I will like to implement this issue as well .

**Comment by zackkrida** [comment]
Hi @Cronus1007  the dark mode issue in the PR was about adding dark mode to our storybooks for vocabulary, not to vocabulary itself. That would need to be styled and designed by our designer before you could code it.

**Comment by Cronus1007** [comment]
@zackkrida  Okk.
