### ISSUE TITLE
Add Steps / Progress Bar to Figma DL

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#67]
**Description**
We're redesigning the Progress Bar style for Vocabulary. Currently the only use case is the License Chooser, where the progress bar looks completely different from the existing styles in Vue Vocabulary.

We want to:
1. Add new design of progress bar to Figma DL
2. Create tickets in Vocabulary & Vue Vocabulary to add this new style. (Francisco to do this once design work complete).

**Comment by fcoveram** [comment]
The progress section, and its components, are in the Design Library file.
