### ISSUE TITLE
Add a CHANGELOG.md file

### ISSUE THREAD

**Issue by nimishbongale** [cc-archive/vocabulary-legacy#670]
## Problem

> When a contributor or end-user wants to see if any changes have been made to a software program, they can do that easily and precisely by reading the changelog. All they need to do is go to the changelog and it will show what, and when, any changes were made between the different versions or releases of the particular software.

## Description

> For every type of software project, there will be the initial release (version) and, subsequently, newer and better releases that work smoother because they have been de-bugged. Changelogs keep track of these changes. They also help to control errors because they document if, and when, those errors were corrected.

## Additional context

- https://changelog.md/
- https://keepachangelog.com/en/1.0.0/

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
@nimishbongale since we use [GitHub Releases](https://github.com/creativecommons/vocabulary/releases), we already have the changelog generated for us in a much more convenient form than a Markdown file. I really believe this is a non-issue.

**Comment by nimishbongale** [comment]
@dhruvkb

Ahh alright. Although, can we also have it as a part of the repo somehow? It would really help imo, for someone who's new and wants to keep up with how the repo is progressing. I get that the github releases makes it very convenient, but I guess that's only when we have a release and not otherwise?

**Comment by dhruvkb** [comment]
- Having a file means having to remember to update it, which adds a human dependency to the deployment. 
- Since we have a very regular release schedule, the 'Releases' page will never be too far behind the present state of the repo so it's not a question of missing out on updates. 
- As for updating outside of releases, many repos that do keep a `CHANGELOG.md` file (like [Vue.js](https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md)) also update it only when there is a new release.

**Comment by nimishbongale** [comment]
Right. All your points do make sense. 
Maybe I can link to the "new releases" part of the github releases in our README? That should basically serve the purpose of a `CHANGELOG.md` without actually having it as a file.

**Comment by dhruvkb** [comment]
Yes, we could do that. Let's wait and see some other opinions before deriving conclusions and starting work on this.

**Comment by zackkrida** [comment]
> Maybe I can link to the "new releases" part of the github releases in our README? 

I was going to suggest this, glad to see it here.

Additionally, if you want to follow the `CHANGELOG.md` convention for developers who are looking for it, we _could_ have `CHANGELOG.md` in the root with contents like:


```markdown
This repo uses GitHub releases to manage versions. You can view a list of our releases [here](https://github.com/creativecommons/vocabulary/releases).
```

**Comment by nimishbongale** [comment]
I'm open to either of those options!
