### ISSUE TITLE
Discussion: Conditional required status checks

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#672]
## Prior art

_Some existing discussions in this problem space:_

- https://github.community/t/feature-request-conditional-required-checks/16761
- https://github.community/t/github-actions-and-required-checks-in-a-monorepo-using-paths-to-limit-execution/16586/7

## The problem 

Within GitHub actions there is the concept of `paths`. Actions can be triggered to run _only_ when specific files match the specified paths. Unit tests and linting only run when changes have been made to a specific package (with paths like `packages/[package-name])`. This is much faster and efficient than running _all_ CI code even if that particular package hasn't had any edits.

What this means is that different PRs have different required status checks, and we _can't_ set blanket requirements for every PR.

## Possible solutions

1. Run all CI actions all the time, regardless of edited package, and use [get-diff-action](https://github.com/technote-space/get-diff-action) to skip the steps in a job when that package has not been edited. This is probably the best approach, but makes it _look_ like some jobs passed, when in reality they were skipped.
2. Disable required status checks for vocabulary. PRs and deployment workflow are manual _anyway_, so this isn't the worst idea.

**Comment by kgodey** [comment]
I vote for (1). Required status checks are a good check for maintainers to have and reduces human error.

**Comment by TomasVotruba** [comment]
Hi everyone, I have the same problem. 
Is there a way to skip required checks if the `paths` was not met for those?

**Comment by zackkrida** [comment]
Hi @TomasVotruba there is still no great solution for this problem. Only hacks or compromises.

**Comment by vuil** [comment]
Just want to add, for repos that leverages paths to limit the set of checks that need to run, this issue makes the automerge feature impossible to use without some hacks like (1).

**Comment by brylie** [comment]
Closing this since it is less relevant now that we have fewer tests and a single source directory. We can revisit the issue if it becomes relevant again later.
