### ISSUE TITLE
Dropdown in Header pattern can’t be accessed with a keyboard

### ISSUE THREAD

**Issue by siggrid** [cc-archive/vocabulary-legacy#687]
## Description
Keyboard users are not able to reach a list of links, hidden within dropdown, when tabbing through the page. 
In code examples, provided for header in Docs, navbar-link(DROPDOWN), that is used as a title for dropdown and controls its visibility, doesn’t have an href or tabindex=”0” attributes. Therefore it is not inserted into the list of focusable elements. If navbar-link is not focused, the dropdown stays hidden. This behaviour is set in styles of “is-hoverable” class. 

## Reproduction
1. use Tab key to navigate through the header.
2. navbar-link(DROPDOWN) doesn’t receive focus.
3. dropdown is not expanding.
4. See error.

## Expectation
navbar-link(DROPDOWN) must be focusable in order to show/hide dropdown content

## Screenshots
![current-nav](https://user-images.githubusercontent.com/52042098/94199499-93cc3b80-fec1-11ea-88ad-fa3413a4164b.gif)

## Environment
Device: laptop
OS: macOS Catalina
Browser: Chrome, Safari, Firefox
Version: 85, 13.1, 81
Other info: used Voiceover screen reader

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by siggrid** [comment]
I’ve come up with suggestions that could solve this issue.

1.  Use tabindex=”0” or href=”#” to insert navbar-link(DROPDOWN) into the tab order.

Pros:
- easy to implement;
- minor changes in code

Cons:
- since dropdown is shown, when navbar-link is focused, keyboard users must tab through all the links before they reach an actual target. It might be an ux issue, if the header contains several dropdowns;
- with tabindex=”0” navbar-link won’t be presented in list of links or form controls; adding href=”#” will make it a link that goes nowhere (mostly related to using a screen reader)

![hoverable-nav](https://user-images.githubusercontent.com/52042098/94200631-61bbd900-fec3-11ea-86e6-7a09c9a8434e.gif)

2.  Set tabindex=”0”, add role=”button” and aria-expanded=”false” to navbar-link(DROPDOWN). Use  unordered list html-element for dropdown list of items.

Pros:
- makes dropdown accessible to both keyboard and screen reader users

Cons:
- markup and styles need to be reconsidered or modified;
- requires javascript to perform well

Show/hide state of a dropdown is triggered by activating the navbar-link(DROPDOWN). Keyboard users are able to navigate through top-level elements. Moving focus out of the list of items, as well as clicking outside the dropdown region or pressing Esc key, closes an open dropdown. Value of an “aria-expanded” attribute of navbar-link is toggled from “true”(dropdown open) to “false”(dropdown closed). A screen reader announces it as “expanded button” or “collapsed button” depending on state. 

![nav-keyboard](https://user-images.githubusercontent.com/52042098/94200762-9c257600-fec3-11ea-8a95-6940c351c742.gif)

**Comment by Dhruvi16** [comment]
I would like to take this up.
Thank you!
