### ISSUE TITLE
[Vue] Card Component

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#695]
The Card component(s) is one of the more complicated `vocabulary` components. It has been overloaded to do many different things, in many different styles. That said, I think we can make a flexible card component with reasonable options and lots of sub-components to determine the layout. 

One problem with the current card components is that variations require different top-level classes. For example, a card with an image doesn't _just_ have this added inside:

```html
<header class="card-image">
  <a href="#">
    <figure class="image is-4by3">
      <img src="https://picsum.photos/id/433/700/392" alt="Header image">
    </figure>
  </a>
</header>
```

it _also_ requires a top level `.entry-video` class be added to the card itself. This means we can't easily write an API that uses child components—the parent component would need to _know_ what kind of children it contains, and apply different styles as a result. Doable, but maybe not the cleanest for users.

[some ticket work required; i'm still thinking about the best path for this]

## Information

- [Page in Vocabulary](https://cc-vocabulary.netlify.app/?path=/docs/layouts-cards--post-vertical)
- [Relevant .scss File](https://github.com/creativecommons/vocabulary/blob/master/packages/vocabulary/src/styles/card.scss)

## Suggested component props

- **Border**: type: `Boolean` | default: `true` | required
- **Direction**: type `string` (horizontal|vertical) | default: `vertical` | required
- **Theme**: type `string` (theme colors) | default: null | optional

## Examples using proposed component design

```vue
<Card direction="horizontal" border>
	<CardImage src="https://placekitten.com/300/400" />
    <CardTitle is="a" href="#">This is a title</CardTitle>
    <CardSubtitle is="a" href="#">12 Octobre 2019</CardSubtitle>
	<CardContent>
        Description metus ligula pharetra litora class massa viverra, facilisis cum aenean hendrerit eget magnis convallis.
    </CardContent>
	<Button href="#" theme="primary">Read more</Button>
</Card>
```

[ticket work required: more examples]

**Comment by ricknjacky** [comment]
hey, @zackkrida i would like to take this issue up. Can I do it?

**Comment by dhruvkb** [comment]
Hi @ricknjacky. This issue has the label `status: blocked` indicating that it is not ready for work. Please go through the [guidelines for contributing code](https://opensource.creativecommons.org/contributing-code/).
