### ISSUE TITLE
`npm run fund` and `package.json` `funding:` key support

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#696]
NPM has added an `npm fund` command which will list a project's dependencies that can be supported financially. Here's an example of the command's output:

```shell
❯ npm fund
cccatalog-frontend@2020.9.3
├─┬ https://github.com/sponsors/mysticatea
│ └── eslint-utils@2.1.0, regexpp@3.1.0
├─┬ https://tidelift.com/funding/github/npm/browserslist
│ └── browserslist@4.14.5, browserslist@4.11.1
├─┬ https://tidelift.com/funding/github/npm/postcss
│ └── postcss@7.0.27
├─┬ https://github.com/sponsors/wooorm
│ └── vendors@1.0.4
├─┬ https://github.com/sindresorhus/mem?sponsor=1
│ └── mem@6.1.1
└─┬ https://tidelift.com/funding/github/npm/autoprefixer
  └── autoprefixer@9.8.6
```

We can add a `funding` key to our `package.json` package files to be included in this command's output. Here's the code:

```json
{
  "funding": [
    {
      "type": "github",
      "url": "https://github.com/sponsors/creativecommons"
    }, 
    {
      "type": "donations",
      "url": "https://us.netdonor.net/page/6650/donate/1?ea.tracking.id=top-of-page-banner"
    }
  ]
}
```

*Edit: This is blocked until we confirm a new Classy campaign url, which will replace the url parameter in the second object above.*

**Comment by dhruvkb** [comment]
That's great! The more places where we list sponsorship links, the better! 

Why is the issue locked to staff only? If you could list the types and links, anyone could work on it.

**Comment by zackkrida** [comment]
@dhruvkb I want to discuss internally first just to make sure there's no reason we can't/shouldn't/don't want to do this. I doubt it, but anytime funding is involved I think it warrants a discussion.

**Comment by kgodey** [comment]
This is a great idea. We should set up a separate campaign in Classy for this cc @annatuma

**Comment by annatuma** [comment]
Sorry for the delay. Here's the link: https://www.classy.org/give/308451/#!/donation/checkout
