### ISSUE TITLE
Customize Theo output format to use HSL instead of RGB

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#7]
[Theo](https://github.com/salesforce-ux/theo) is currently configured to use the `web` transform, which causes all colors to be transformed to RGB, regardless of the format used in the `.yml` files. Going forward, as we migrate to the HSL scheme with creativecommons/vocabulary#5, Theo will need to be configured differently to preseve hue and saturation information in the final transformed tokens.

If limitations prevent us from effecting this, we may even move to [Style Dictionary](https://amzn.github.io/style-dictionary/#/).

**Comment by kgodey** [comment]
We're no longer using Theo.
