### ISSUE TITLE
Add the responsive versions of footer

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#725]
## Description
We need to add the responsive versions of footer. The four breakpoints are in the [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=639%3A24&viewport=25%2C233%2C0.23559321463108063). Something important to notice: some text styles have changed. Please check all styles to ensure a correct implementation

### Screenshot
<img width="1239" alt="Screen Shot 2020-10-14 at 11 54 45" src="https://user-images.githubusercontent.com/895819/96006626-1175ce00-0e14-11eb-887c-6c7df763e1b1.png">

## Hover states
The `hover` state per element should follow these definitions:
* Navigation item (item 1 to item 6): No color change, but underline style.
* Creative Commons logo: No change
* Social media links: No change
* Subscribe action in newsletter bar: No change
* Donate now button: `DarkGold` color (as the default interaction for `Gold` color buttons)
* Link as text: No color change, but underline style.

## Ticket related
#710

**Comment by chidexebere** [comment]
will be glad to take this up

**Comment by nimishbongale** [comment]
Go ahead @chidexebere! 😄

**Comment by chidexebere** [comment]
Hello @panchovm , you did not add a hover state for the footer. An important hover state will be that of the `item1 - item6` since they now have a caret-down attached to them.

**Comment by fcoveram** [comment]
True @chidexebere! That's my mistake. I need to delete the dropdown arrows, for this component there will not be that interaction. Regarding the `hover` state of remained elements, I updated the initial ticket with indications per element.
