### ISSUE TITLE
[RFC] npm 7 considerations

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#726]
## Details

This week _npm_ published [v.7.0.0](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/?utm_content=buffer68eee&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer), which contains some exciting new features relevant to vocabulary, namely...*workspaces!* 🎉 

The entire [RFC for workspaces](https://github.com/npm/rfcs/blob/latest/implemented/0026-workspaces.md) is worth a read, but the main takeaway for vocabulary is that we can add a `workspaces` key to our `package.json` (following the precedent set by `yarn`), and with a root `npm install` all of our package dependencies will be installed automatically. This eliminates our secondary `npm run setup` step. Here's the new `package.json` config we'll need:

```json
{
  "workspaces": {
    "packages": ["packages/*"]
  }
}
```

As stated, this means that npm > 7 users no longer need `npm run setup`. This should significantly reduce friction for new vocabulary users and cut down on the amount of slack support we need to provide.

## Plan

There's one gotcha here. npm@7 is not yet available at the `latest` tag for npm, so it will _not_ be installed automatically for users. npm@7 will be the default when node@15 lands. So, we should update the repo to _prepare_ for npm@7 in a few ways:

- Test npm@7 to make sure it works in the monorepo
- Add the `workspaces` config to the `package.json` file
- Make default installation instructions target npm > 7
	- Add secondary language for (if you are using npm < 7, use `npm run setup`, etc.)

**Comment by neeraj-2** [comment]
Can I take it @zackkrida ?
