### ISSUE TITLE
Color update and adding new ones

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#729]
## Description
Based on previous discussions about brand colors, today we updated the [Design Library with the new palette](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A72&viewport=-819%2C-1377%2C1.0137752294540405). This change includes:
1. Update of brand colors.
2. New color set: Soft Brand.
3. Update of interaction colors.

### Brand colors
The following colors have been updated with a new hex code to match the AA level of accessibility:
1. **Tomato:** new hex code 
2. **Gold:** new hex code
3. **Forest Green:** new hex code
4. **Dark Slate Blue:** new hex code
5. **BrighterDarkSlateBlue:** eliminated

<img width="641" alt="Screen Shot 2020-10-14 at 18 06 43" src="https://user-images.githubusercontent.com/895819/96045238-118fc100-0e48-11eb-9085-29dde80d9a89.png">

### Soft Brand set
This set of colors is a new palette as soft versions of brand colors to be used in backgrounds.

<img width="624" alt="Screen Shot 2020-10-14 at 18 08 07" src="https://user-images.githubusercontent.com/895819/96045366-3b48e800-0e48-11eb-8507-b454d19203b9.png">

### Interaction colors
Since the interaction colors are based on the brand ones, this adjustment follows the same lightness and saturation rule of the existing ones, and therefore, they were updated.

<img width="605" alt="Screen Shot 2020-10-14 at 18 10 56" src="https://user-images.githubusercontent.com/895819/96045654-a2669c80-0e48-11eb-949f-6810deec4a61.png">

**Comment by rochisha0** [comment]
I'd like to take this issue!

**Comment by fcoveram** [comment]
Hey @rochisha0, there is a new color updated in this ticket (#737). The changed indicated there is something that I discussed with @zackkrida
