### ISSUE TITLE
Use sed to customise npm README's for packages

### ISSUE THREAD

**Issue by nimishbongale** [cc-archive/vocabulary-legacy#736]
## Problem
The README for npmjs is not customised for all the packages. They all copy the same README from the root. 

## Description
The installation guidelines needs a bit of changing. This can be done using the `sed` command to change the relevant lines of code after copying the README from the root. 

## Alternatives
Since the packages are separate on npmjs, they perhaps need their own slightly customised README's.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by neeraj-2** [comment]
I would like to work on it.Can I?

**Comment by nimishbongale** [comment]
Sure, go ahead @neeraj-2.

Just fyi, this is the part that needs changing:

```bash
To run the storybook for an individual package (say, fonts):

cd packages/fonts
npm install
npm run build
npm run storybook
```

**Comment by neeraj-2** [comment]
> Sure, go ahead @neeraj-2.
> 
> Just fyi, this is the part that needs changing:
> 
> ```shell
> To run the storybook for an individual package (say, fonts):
> 
> cd packages/fonts
> npm install
> npm run build
> npm run storybook
> ```

Thanks, @nimishbongale , Can u elaborate that what changes we need to put here like do we need to add some other commands or set some command as optional.

**Comment by nimishbongale** [comment]
When we publish a package to npm, the main README gets copied everywhere. This code is the one that helps with the publishing to npm:

https://github.com/creativecommons/vocabulary/blob/bb9a1306b176283a253f4a9b9b0d35ec1170ee05/packages/vocabulary/deploy.sh#L15

After the copying is done, within each individual packages, we would need to modify the README accordingly. Currently the README states how to run the `fonts` package only. But this can be programatically modified to include all, depending on the package.  

After publishing to npm, the README gets shown here:
- https://www.npmjs.com/package/@creativecommons/vocabulary
