### ISSUE TITLE
Interaction colors update and feedback colors correction

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#737]
### Interaction colors
There was an error with the interaction colors after reviewing and updating the palettes (requested in ticket #729). Also, Vocabulary has a button using one of the blue versions but there was no interaction color.

In this update, all interaction colors have been updated:

1. BrighterTomato: `#E04D03`
2. DarkGold: `#F8CC2C`
3. BrighterForestGreen: `#008B00`
4. BrighterBlue: `#174EBC` (New color in the color set)

<img width="793" alt="Screen Shot 2020-10-19 at 17 20 17" src="https://user-images.githubusercontent.com/895819/96507327-627c2c80-122f-11eb-926b-9c0af96844ea.png">

### Feedback colors
In this set, two colors use the same hex code of interaction colors. And we need to update them. These colors are:
* `DarkSuccess` = `ForestGreen`.
* `DarkInfo` = `BrigtherBlue`.

All remained colors have their own hex code and no need to be updated

<img width="808" alt="Screen Shot 2020-10-19 at 17 20 09" src="https://user-images.githubusercontent.com/895819/96507348-69a33a80-122f-11eb-8970-7b230db76b86.png">

**Comment by rochisha0** [comment]
Thanks, @panchovm for elaborating on this. I will update the PR asap.

**Comment by rochisha0** [comment]
@panchovm , where should I accommodate [this](https://github.com/creativecommons/vocabulary/blob/master/packages/vocabulary/src/styles/button.scss#L105) color. I did it in Interaction earlier as @zackkrida said.

**Comment by fcoveram** [comment]
For now let's use the `BrighterBlue` for `default` and `hover` interaction. There's an inconsistency with buttons that's beyond this change. Thanks for bringing it @rochisha0
