### ISSUE TITLE
Create way to use Bulma Grid System in Vocabulary

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#75]
**Description**
We plan to make use of Bulma's Grid instead of building it ourselves. We should update the Vocabulary storybook to document how to use Bulma's grid.

**Comment by annatuma** [comment]
Note, currently evaluating Bulma separately: https://github.com/creativecommons/vocabulary/issues/56 so further research should not duplicate that effort.

**Comment by kgodey** [comment]
@brenoferreira did this in https://github.com/creativecommons/vocabulary/pull/115
