### ISSUE TITLE
Card layout breaks on a long word

### ISSUE THREAD

**Issue by obulat** [cc-archive/vocabulary-legacy#753]
## Description

When a card contains a string that is longer than card's width, the card will either hide the overflow, or break the layout

## Reproduction

1. Open cards in the vocabulary storybook.
2. Change the content: add a really long word or a URL without breaks.
4. See error.

## Expectation
The card content should wrap if it doesn't fit 

### From the storybook:
![Screenshot 2020-11-01 080449](https://user-images.githubusercontent.com/15233243/97795567-3d8ba000-1bc5-11eb-8f38-36237315ae7d.png)
### From the Vocabulary docs draft site:
![Screenshot 2020-11-01 080500](https://user-images.githubusercontent.com/15233243/97795568-3ebccd00-1bc5-11eb-824d-bf44b358ae23.png)

## Additional context
The fix for this is described on[ css-tricks](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/)

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by SaravgiYash** [comment]
Hi @obulat I would like to work on this issue.

**Comment by kgodey** [comment]
go ahead @Yashs911
