### ISSUE TITLE
Have our visual tests running on chromatic

### ISSUE THREAD

**Issue by nimishbongale** [cc-archive/vocabulary-legacy#757]
## Problem
We overshoot our netlfy build limits every month nearly. Maybe we can have another service to take care of the same?

## Description
[https://chromatic.com](https://chromatic.com) is a service built by the storybook maintainers themselves and is designed to be used for storybooks. They offer a free open source plan & I think we should go ahead and use chromatic for our builds instead.

The major pros is that the site makes snapshot testing easy along with unlimited deploy previews, & easier collaboration between designers & developers. You can even choose which component you'd like to show/hide with a single button click. They offer free packages for open source projects. I've gone ahead & asked them for what they actually offer under it. They should be getting back to me soon.

- https://5f5f9c542bda1300225c036d-ymzvvgjzcp.chromatic.com/

Here's a sample build I've deployed on chromatic. It's fairly easy!

If any maintainer here wants to have a look, here's the invite to the chromatic CC workspace:

- https://www.chromatic.com/builds?appId=5f5f9c542bda1300225c036d

(accessible only to maintainers of CC Vocabulary)

## Alternatives
Alternatives would include vercel etc but since chromatic is built by the storybook maintainers themselves, I think its a safe bet.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by kgodey** [comment]
@nimishbongale do you mean storybook maintainers instead of vocabulary maintainers? AFAIK, we are not affiliated with chromatic.com :)

**Comment by nimishbongale** [comment]
@kgodey 

Whops, my bad 😄 Thanks for pointing it out! 

Edited!
