### ISSUE TITLE
Add two new text styles

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#759]
## Description
We need to add two new text styles that are currently available in the [Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=445%3A1053&viewport=90%2C60%2C0.23130376636981964). These are:
1. Heading 6B
2. Small caption

These styles were created for the mobile resolution where some text styles needed new versions in this resolution. The specs can be found in the mockups.

**Comment by shobhi1310** [comment]
@panchovm Can I work on this issue ?

**Comment by fcoveram** [comment]
Wait for @dhruvkb or any other team member that is managing these tasks to assign you.

**Comment by dhruvkb** [comment]
Sure @shobhi1310, you can work on this.

**Comment by shobhi1310** [comment]
I have an issue, I have forked the repo and am setting it up locally, on running the `npm run watch` command, in the end I am being prompted this error and it exits the process.
![image](https://user-images.githubusercontent.com/42507632/99895088-4bf14700-2cad-11eb-90bb-f60066a0b782.png)

How to fix it?
I have already run `npm install`, so all dependencies should have been installed apart from that I have also run `npm run setup`

**Comment by shobhi1310** [comment]
I am new to open-source and I do not want to make mistakes and am learning constantly.
So, I just wanted to confirm. These need to be added right?
![image](https://user-images.githubusercontent.com/42507632/99895638-28c79700-2caf-11eb-90a7-2e9547e67203.png)
![image](https://user-images.githubusercontent.com/42507632/99895657-354bef80-2caf-11eb-82f4-6a4500854844.png)

**Comment by nimishbongale** [comment]
> I have an issue, I have forked the repo and am setting it up locally, on running the `npm run watch` command, in the end I am being prompted this error and it exits the process.

@obulat just tagging you here

I think it points to the earlier issue (#801) we had, although I'm not entirely sure. 

In the meantime, @shobhi1310, please try setting up only the `vocabulary` storybook this way:

```bash
cd packages/vocabulary
npm install --legacy-peer-deps
npm run build
npm run storybook
```

**Comment by obulat** [comment]
This error happens because of our new SVG icons, I will try to find a fix and a workaround later today.

**Comment by obulat** [comment]
> How to fix it?
> I have already run `npm install`, so all dependencies should have been installed apart from that I have also run `npm run setup`

I see that you have an older version of vocabulary: 2020.11.1, and the current one is 2020.11.3. Could you please update and try again. If you have any more errors, don't hesitate to ask again!

**Comment by shobhi1310** [comment]
I actually forked the repository and then further ran commands which were provided in setting up locally. For updating which command should I run?

**Comment by shobhi1310** [comment]
@panchovm 
sir, can you once again describe what needs to be done exactly? 

> I am new to open-source and I do not want to make mistakes and am learning constantly.
> So, I just wanted to confirm. These need to be added right?
> ![image](https://user-images.githubusercontent.com/42507632/99895638-28c79700-2caf-11eb-90a7-2e9547e67203.png)
> ![image](https://user-images.githubusercontent.com/42507632/99895657-354bef80-2caf-11eb-82f4-6a4500854844.png)

Do I have to change the vocabulary page in the Typography section as shown here:
![image](https://user-images.githubusercontent.com/42507632/99955024-a96abe00-2da9-11eb-8a03-f2f3aef0f9ea.png)

**Comment by fcoveram** [comment]
@shobhi1310 we need to add the Heading 6B and small caption styles. If you see the `Docs` tab, all styles are displayed there.

**Comment by tichnas** [comment]
@shobhi1310 Are you still working on this issue?

**Comment by akshayprabhu200** [comment]
Is this issue open to take? This would be my first commit, had a question if so - the way I understand this issue based on @dhruvkb's comment is that someone needs to update the `typography.scss` file to add the two tags based on specifications from Figma. Is this correct?

**Comment by dhruvkb** [comment]
@akshayprabhu200 you can take it up. And yes, the goal is to have `typography.scss` provide the all the font styles needed for the new types of headings and captions.

**Comment by akshayprabhu200** [comment]
I have added two styles `h6` and `small-caption` to the `typography,scss` file. Also updated the docs to reflect the changes, do I need to write any tests for these (and if so where) and run any linter before a PR?

**Comment by nimishbongale** [comment]
> do I need to write any tests for these (and if so where) and run any linter before a PR?

The linter we have configured is a husky pre-commit linter. It will run automatically when you start your commit. You can go ahead and raise a relevant PR linking to this issue for now (perhaps even a draft PR). The rest will be taken care of during a code review.

**Comment by mmkm10** [comment]
is this issue still open to take? If yes, then could I take it?

**Comment by akshayprabhu200** [comment]
@mmkm10 I've submitted a PR, waiting for review

**Comment by abhijeetk698** [comment]
is this issue open ?? I want to work on it.

**Comment by obulat** [comment]
> is this issue open ?? I want to work on it.

No, @abhijeetk698 , the PR that will close this issue has been submitted.
