### ISSUE TITLE
Add the mobile version of breadcrumb component

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#760]
## Description
We need to add the mobile version of breadcrumb component to be used in Certificate and Global Networks sites. The behavior showed in [the Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=7298%3A0&viewport=-1507%2C60%2C0.3642522096633911) is when the component extension is bigger than the display.

<img width="702" alt="Screen Shot 2020-11-04 at 16 53 29" src="https://user-images.githubusercontent.com/895819/98161316-4b3f6f00-1ebe-11eb-8f0e-d7596cc6d6f6.png">

### Features
* The functionality that I have in mind works as: If the breadcrumb extension is bigger than the display, then hide the breadcrumb. Otherwise, it shows the whole breadcrumb.
* `Background color` and `text color` will change depending on the site

**Comment by khushishikhu** [comment]
may i work on this issue?

**Comment by khushishikhu** [comment]
@panchovm @nimishbongale can you please define me a bit as what kind of work you want in modification of breadcrumb extension. It would be helpful for me to make that structure at figma
