### ISSUE TITLE
Consideration: Remove GitHub Packages builds 

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#762]
Our Github Package build for vue-vocabulary currently errors out, which prompts the question: should we even continue to support the GitHub Package registry? Especially considering their ownership of npm.

We haven't had any downloads of the GitHub Package registry packages in the past 30 days. I'm open to hearing everyone's thoughts.

**Comment by dhruvkb** [comment]
All code is tech debt so it makes sense to delete code that doesn't add value.

**Comment by zackkrida** [comment]
Fixed via #817.
