### ISSUE TITLE
[vocabulary] Add new SVG docs

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#764]
The SVG icons page on https://cc-fonts.netlify.app needs to be added to https://cc-vocabulary.netlify.app/

**Comment by patelaryan7751** [comment]
hello @zackkrida  I want to work on this issue. Can you give some more information on this?

**Comment by zackkrida** [comment]
Hi @patelaryan7751,

So, we have a story for the icon font in vocabulary:

url: https://cc-vocabulary.netlify.app/?path=/story/tokens-icons--figma
file: `packages/vocabulary/src/stories/icons.stories.mdx`

that story should be renamed to "Icon Font" instead of "Icons" and a new story should be added called "Icons", where the iframe uses this url: https://cc-fonts.netlify.app/?path=/docs/vocabulary-svg-icons--page

**Comment by patelaryan7751** [comment]
Thanks @zackkrida for the reply i am working on this issue.

**Comment by patelaryan7751** [comment]
@zackkrida please add me as an assignee for this issue
