### ISSUE TITLE
Add 'Tooltip' feature

### ISSUE THREAD

**Issue by Audiosutras** [cc-archive/vocabulary-legacy#769]
## Problem

The current site has this ![tooltip](https://user-images.githubusercontent.com/37882933/98284637-6c13cd00-1f6f-11eb-8e9a-bdd8bf9a1bac.png) functionality that is currently unsupported in vocabulary. 

## Description

A `tooltip` component should be added to the vocabulary style guide for use in the `cc-licenses` project.

**Comment by Dhruvi16** [comment]
I would like to take this up!

**Comment by zackkrida** [comment]
@Dhruvi16 I think we just need some styling input from @panchovm before this is implemented.

**Comment by fcoveram** [comment]
[Here is](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=9101%3A112&viewport=45%2C230%2C0.4611110985279083) the tooltip component. I added it a few weeks ago, but not sure if I created the ticket. Let me know @zackkrida @Dhruvi16 if that's sufficient.

**Comment by zackkrida** [comment]
Thanks @panchovm !

**Comment by zackkrida** [comment]
@Dhruvi16 this is a high-priority feature (it's needed for the `cc-licenses` project), so if you start work on it please let me know and make a draft PR whenever you have some code ready. Thank you!

**Comment by Dhruvi16** [comment]
@zackkrida I have made a draft PR. Still a lot of work to do but just letting you know.

**Comment by Cronus1007** [comment]
@Dhruvi16  Just a thought why we are not using any tooltip library like `react-tooltip` for having a tooltip. And if you are currently not working on this issue so shall I take over this issue.

**Comment by testMrinal** [comment]
Is this issue still open? I want to work on this issue.
