### ISSUE TITLE
Remove fontawesome packages from Vue-Vocabulary

### ISSUE THREAD

**Issue by obulat** [cc-archive/vocabulary-legacy#770]
## Problem

After the final integration of SVG icons and documentation about them is over, I believe we can remove the following packages from Vue Vocabulary: 

```
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/free-brands-svg-icons": "^5.14.0",
    "@fortawesome/free-regular-svg-icons": "^5.14.0",
    "@fortawesome/free-solid-svg-icons": "^5.14.0",
    "@fortawesome/vue-fontawesome": "^2.0.0",
```

Whenever we need an additional icon, we can always add its '.svg' source to the assets.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by SaravgiYash** [comment]
@obulat I would like to work on this issue.
Do I just need to remove 
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/free-brands-svg-icons": "^5.14.0",
    "@fortawesome/free-regular-svg-icons": "^5.14.0",
    "@fortawesome/free-solid-svg-icons": "^5.14.0",
    "@fortawesome/vue-fontawesome": "^2.0.0", from package.json

**Comment by khushishikhu** [comment]
may i work on this?

**Comment by SaravgiYash** [comment]
@obulat @zackkrida I was the first one to claim the issue

**Comment by obulat** [comment]
I think that we still need to polish SVG icon integration (i.e. path of `fonts` imports, icon styles) into Vocabulary before removing fontawesome packages, so this issue should be blocked for now.
