### ISSUE TITLE
Add a new "install size" badge for vocabulary, fonts & vue-vocabulary

### ISSUE THREAD

**Issue by nimishbongale** [cc-archive/vocabulary-legacy#776]
## Description
Since new badges are always welcome, we could have some new ones to do with the current size of the packages as a part of `README.md`. 

- https://packagephobia.com/result?p=@creativecommons/vocabulary
- https://packagephobia.com/result?p=@creativecommons/fonts
- https://packagephobia.com/result?p=@creativecommons/vue-vocabulary

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by neeraj-2** [comment]
can I take it?

**Comment by nimishbongale** [comment]
Go ahead @neeraj-2 👍

**Comment by neeraj-2** [comment]
As per my understanding, we want to add the three badges that u mentioned above here, in our Readme. So I think it would look great just above our `Included Packages` component that I highlighted here. What do u say @nimishbongale?


![image](https://user-images.githubusercontent.com/56186425/98586739-28162480-22ef-11eb-8c67-44403c05ec67.png)

**Comment by nimishbongale** [comment]
You could put them where you think they sit the best. I don't have a strong opinion about this either.
