### ISSUE TITLE
Add TabbedPane to Figma DL & Update Design

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#78]
**Description**
We need to:
1. Add TabbedPane to the Figma DL:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/layouts-tabbedpane--branded

2. Update the style of TabbedPane to be in line with our new overall look and feel.

3. Create tickets in Vocabulary and Vue Vocabulary to apply updates to TabbedPane, once the above steps are complete. (Francisco to create these tickets, assign them to Dhruv & Hugo).

**Comment by fcoveram** [comment]
Done. The Tab component is in Design Library now
