### ISSUE TITLE
Installation Guidelines for npm@7 in Readme

### ISSUE THREAD

**Issue by neeraj-2** [cc-archive/vocabulary-legacy#780]
## Problem

Right now our `Readme` does not provide proper guidelines for the **npm@7** version.So we need to update the Readme for npm@7.

## Description

We need to just add the `"--legacy-peer-deps"` tag with all the commands for the setup already we have.For eg. For the command "npm install", we need to run "npm install --legacy-peer-deps" for **npm@7.** So we can update our `Readme` accordingly.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by nimishbongale** [comment]
I think you can just edit the installation step to something like:

```bash
npm install --legacy-peer-deps
...
```

Running the step with the extra option should not affect versions <7 afaik.
