### ISSUE TITLE
Remove all use of `@extends` from Vocabulary

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#781]
## Description

Extends, particularly of bulma helper classes, can cause issues in scss projects using vocabulary. To build properly, these projects will need to import all bulma helpers themselves, which is concerning because it requires them to manage bulma on their own, which could result in them using a different version than vocabulary.

Here are all uses of `@extends` in Vocabulary: https://github.com/creativecommons/vocabulary/search?q=%22%40extend%22&type=code

They should be replaced like this:

```diff
- @extends .padding-top-normal
+ padding-top: $space-normal
```

and so on.

**Comment by neeraj-2** [comment]
I would like to work on it.Can I?

**Comment by neeraj-2** [comment]
Hey @zackkrida, can u tell me what would be the replacement of - `@extends .is-paddingless` ,`- @extends .body-normal`, - `@extends .caption`,- `@extends .b-header`,- `@extends .has-text-centered`.I implemented the rest changes but don't know about the replacement of these ones that I mentioned🤔.

**Comment by zackkrida** [comment]
If you go in the typography.scss file you'll see variables that match those font size classes. For the centering of text you can just use text-align: center

**Comment by RinkiyaKeDad** [comment]
Hey @neeraj-2 are you still working on this? If yes, do you need some help? Can we collaborate on it?

**Comment by neeraj-2** [comment]
thanks @RinkiyaKeDad ,yes i am on it.I am almost done.But if I need help i will definitely discuss it with u.
