### ISSUE TITLE
Remove Tabbed (from Layouts) and Associated Styles

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#79]
**Description**
We'd like to remove Tabbed (from Layouts) and all associate styles:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/layouts-tabbed--branded

Note that we are maintaining TabbedPane (in use by Extension), and will be making design updates to it, to reflect use cases in License Chooser and CC Search.

**Comment by kgodey** [comment]
No longer relevant with new repo changes.
