### ISSUE TITLE
[Vue] Icon component

### ISSUE THREAD

**Issue by obulat** [cc-archive/vocabulary-legacy#790]
## Problem

Vocabulary has moved away from icon fonts to using SVG icons. Now, to use a Vocabulary SVG icon in a Vue project, we need  an Icon component to apply the correct size and layout to it. 

## Description

This component can also take care of importing the icon:
`<VIcon name="cc-heart" size="small">`
 It could also be just a wrapper for the icon component:
`<VIcon size="smaller"><CCHeart /></VIcon>`.

Or, alternatively, it can be even more flexible by having both options: using the slot icon if it's provided, and importing the icon by its name otherwise. What do you think, @zackkrida , @dhruvkb ?

## Additional context

From a quick scan of DL, I can see that the icon sizes we need are: 10x10 (header locale and donate buttons), 20x20 (license texts), and 30x30. Any other size I missed, @panchovm ?
## Implementation

- [x] I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
> This component can also take care of importing the icon:
> <VIcon name="cc-heart" size="small">
> It could also be just a wrapper for the icon component:
> <VIcon size="smaller"><CCHeart /></VIcon>.

I think we _always_ want the icons wrapped in the `<VIcon>`, so I prefer the first approach. The sizes you listed seem like a good starting point too.

Lastly, might as well have a `color` prop too.

**Comment by fcoveram** [comment]
I checked all components that have icons and here are the sizes:
## Header
- Buttons: `10px`
- Main nav: `15px`

## Components
- Button and text link: `15px`
- Input: `20px` desktop; `15px` mobile
- (*) Select: `17px` 
- Donate: `30px`

(*) We can discuss this one since I picked this size because it looks better in Figma, but might not be the same once developed.

**Comment by rajat2502** [comment]
Hey @obulat, I can try adding this feature. 
Are color, size, and name are the only props that we need on the Icon component? 
Also, we will have to add one `JSON` file to store the objects for the SVGs so can you please guide me on where to add that?
