### ISSUE TITLE
[Vue] Input component

### ISSUE THREAD

**Issue by obulat** [cc-archive/vocabulary-legacy#791]
## Description

Input component is essential for any form. The designs for inputs are in [Figma Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=10244%3A140).

Here is my proposed input API:

### Big input with label and description
![image](https://user-images.githubusercontent.com/15233243/99355547-53ec5980-285d-11eb-8e94-52a3d8756c24.png)
`<VInput v-model="inputValue" label="input name" placeholder="placeholder text" description="description of the input" size="big" />`

### Input with an icon:
![image](https://user-images.githubusercontent.com/15233243/99355786-c5c4a300-285d-11eb-8d30-8844214a9a54.png)
`<VInput v-model="search" placeholder="placeholder text" icon="search" />`

### Disabled textarea:
![image](https://user-images.githubusercontent.com/15233243/99355955-10deb600-285e-11eb-967d-1bed5df55b91.png)
`<VInput v-model="text" :is-textarea="true" :disabled="true" />`

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by zackkrida** [comment]
I like the api design for each component, I think you're good to start on this.

**Comment by emmanuelhashy** [comment]
Hi, @zackkrida I'd like to work on this issue if it's still available.

**Comment by obulat** [comment]
@emmanuelhashy , I have started the work on this issue and am waiting for a review, so it's not available. You can look at other available issues in the [issue finder](https://opensource.creativecommons.org/contributing-code/issue-finder/)
