### ISSUE TITLE
New default button behavior breaks `.tag` buttons

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#799]
The new default tomato buttons break the `.tag` style buttons, which inherit the default coloring:

<img width="1116" alt="Screen Shot 2020-11-20 at 8 36 59 AM" src="https://user-images.githubusercontent.com/6351754/99837435-aa7ebf80-2b0b-11eb-8548-3f3d55e81577.png">

**Comment by neeraj-2** [comment]
Can I work on it?

**Comment by neeraj-2** [comment]
When I run it locally , the style is not broken, but when I opened the deployed application It seems it is broken, wondered why?

On localhost:

![image](https://user-images.githubusercontent.com/56186425/99906597-05780880-2cfe-11eb-8adb-f4580ebc0b85.png)



Deployed app:

![image](https://user-images.githubusercontent.com/56186425/99906579-ea0cfd80-2cfd-11eb-8df9-4273cb8e71b5.png)

**Comment by zackkrida** [comment]
The background isn't supposed to be orange, that's the 'broken' bit.
