### ISSUE TITLE
Sanitise license badges

### ISSUE THREAD

**Issue by dhruvkb** [cc-archive/vocabulary-legacy#8]
The license badges added in #146 have some issues that need to be addressed. See [below](https://github.com/creativecommons/vocabulary/issues/8#issuecomment-598049968).

<details>
<summary>Outdated issue description</summary>
<div>
A number of SVGs are embedded in the project.

- `icons/`
  - `license/`
    - `badges_full/`
      - by-nc-nd
      - by-nc-sa
      - by-nc
      - by-nd
      - by-sa
      - by
      - pd
      - zero
    - `badges_reduced/`
      - by-nc-nd
      - by-nc-sa
      - by-nc
      - by-nd
      - by-sa
      - by
      - pd
      - zero
- `logos/`
  - `cc/`
    - letterheart_black
    - letterheart_white
    - lettermark_black
    - lettermark_white
    - wordmark_black
    - wordmark_white
  - `vocabulary/`
    - wordmark_black
    - wordmark_white

These SVGs have been obtained from various sources and have varying amounts of excess metadata embedded in them. The goal is to sanitise the SVGs, remove all but the necessary metadata, use the `viewBox`/`height`/`width` attributes properly and reformat the file to be readable. In additions, logos should drop the black and white variants, instead switch to using font colour like Font Awesome icons using CSS on the `BrandImagery` component. The SVGs should also be renamed to use '_' instead of '-'.  Remember to update references to these SVGs in accordance with the new names.

I've previously had success minifying and cleaning SVGs with [SVGOMG](https://jakearchibald.github.io/svgomg/), although some tasks will have to be done by hand after the minification.
</div>
</details>

**Comment by dhruvkb** [comment]
Logos have been sanitised. Licesnse badges, both large and small will be sanitised and added in #146.

**Comment by kgodey** [comment]
@dhruvkb can this be closed?

**Comment by dhruvkb** [comment]
@kgodey no actually. The license badge assets added in #146 have some issues that, since not addressed in the original PR, should ideally be addressed in this issue.
- too much metadata: Metadata is not an issue in itself, but a lot of metadata in files being served over the internet can bloat the SVGs and increase the bundle sizes.
- incoherent sizes: the CC0 and PD license badges have the same aspect ratio but different `viewBox`, `height` and `width` attributes compared to the other assets.

**Comment by arushivii** [comment]
@dhruvkb  can i work on this?

**Comment by dhruvkb** [comment]
@av-00 please do!

**Comment by arushivii** [comment]
@dhruvkb  how do i start on this?

**Comment by jahnvigupta** [comment]
Can you guide on what metadata can be deleted.

**Comment by dhruvkb** [comment]
@jahnvigupta @av-00 the basic structure of an SVG is
```xml
<svg
  xmlns="http://www.w3.org/2000/svg"
  viewBox="" height="" width=""
  preserveAspectRatio="">
  <g id="" fill="">
    <path d=""/>
  </g>
</svg>
```
See the SVGs in `src/assets/logos/cc/` for examples of clean minimal SVGs. 

The license SVGs on the other hand contain tons of artefacts from their age, that is essentially bloat today, making them larger and more difficult to transmit over the Internet.
- RDF information
- Sodipodi attributes
- Inkscape attributes

![Screenshot 2020-03-26 at 2 00 29 PM](https://user-images.githubusercontent.com/16580576/77625751-29662d00-6f6a-11ea-83a7-c29d09c9b19f.png)

This bloat can be removed by SVG optimisation tools and some manual scrubbing.

**Comment by jahnvigupta** [comment]
@av-00 are you working on meta data part or should I start working on it?

**Comment by arushivii** [comment]
@jahnvigupta  Working on it already!

**Comment by dhruvkb** [comment]
@av-00 if you could remove the metadata from all files except the big CC0 and big PD licenses that would be awesome.

I'll review and merge @jahnvigupta's PRs for those licenses in the meantime and then you could optimise them as well.

**Comment by arushivii** [comment]
I am working on them @dhruvkb . Sorry got a little late but will finish by afternoon

**Comment by dhruvkb** [comment]
@av-00 I'm sorry if I gave you the wrong vibe, it was not a 'hurry up' message. I was just dividing the work up. Take all the time you need. I have way too many PRs to review anyways.

**Comment by arushivii** [comment]
Just completed the big licence badges! Please review them when free @dhruvkb

**Comment by arushivii** [comment]
Also completed the small licence badges @dhruvkb
