### ISSUE TITLE
Add Table to Figma DL, Redesign

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#80]
**Description**
We have Table (Layouts) in Vocabulary:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/layouts-table--bordered

We need to:
1. Add these to Figma DL
2. Redesign based on use cases (discuss, approve, etc.)
3. Create tickets in Vue Vocabulary and Vocabulary (assigned to Dhruv and Hugo) to update the existing Table (Layouts) to match what's in Figma DL.

**Comment by fcoveram** [comment]
I forgot what we meant with "discuss, approve, etc…"

**Comment by fcoveram** [comment]
The table styles are in the Design Library file
