### ISSUE TITLE
[vocabulary] Header width, padding, and sizing issues

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#805]
## Description

Currently, the new header has an arbitrary padding value of `0 5.75rem 1.5rem 3.75rem` on desktop. Instead, the header should have two options:

- A default state using a bulma `.container`, so header width always matches the width of the other containers on the page. This is the style most of the sites use.
- An `.is-full` state, that makes the header 100% wide (as seen on http://search.creativecommons.org/)

Additionally, the header has a few max-height and other 'magic' css values in the code. It would be ideal to refactor a little to remove these constraints. Arbitrary numbers in css are usually indicative of code that could be refactored. It's likely the layout mental model of the header of the component can be simplified. **This issue can be fixed here or in a separate PR.**

## Expectation

The new header width doesn't conform to bulma's container width, but instead uses an arbitrary padding value to enforce a quasi-max-width.

## Screenshots

<img width="1608" alt="Screen Shot 2020-11-22 at 9 44 37 PM" src="https://user-images.githubusercontent.com/6351754/99938485-f9934300-2d0b-11eb-91fc-9fe21f39d4df.png">
<img width="341" alt="Screen Shot 2020-11-22 at 9 44 50 PM" src="https://user-images.githubusercontent.com/6351754/99938491-fbf59d00-2d0b-11eb-955f-d2b8afe18083.png">

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by chidexebere** [comment]
Bulma's `.container` class has a `max-width of 960px` at @Desktop viewport. 
An example with one of cc websites showing this problem, will better help solve this.

**Comment by kshitij86** [comment]
@zackkrida @kgodey I've worked with Bulma before, so I think I can contribute here. Can I get assigned to work on this issue?

**Comment by dhruvkb** [comment]
Sure @kshitij86 feel free to take it up.

**Comment by kshitij86** [comment]
Sure, I'll look into this issue.

**Comment by kshitij86** [comment]
@dhruvkb I cam across the following error when trying to build `vocabulary`:

```
Module Error (from ./node_modules/sass-loader/dist/cjs.js):
@creativecommons/vocabulary:     Missing binding /home/.../vocabulary/packages/vocabulary/node_modules/node-sass/vendor/linux-x64-72/binding.node
@creativecommons/vocabulary:     Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x
@creativecommons/vocabulary:     
@creativecommons/vocabulary:     Found bindings for the following environments:
@creativecommons/vocabulary:       - Linux 64-bit with Node.js 10.x
@creativecommons/vocabulary:     
@creativecommons/vocabulary:     This usually happens because your environment has changed since running `npm install`.
@creativecommons/vocabulary:     Run `npm rebuild node-sass` to download the binding for your current environment.
@creativecommons/vocabulary:     
@creativecommons/vocabulary:     ERROR in ./src/styles/vocabulary.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--4-2!./src/styles/vocabulary.scss)
@creativecommons/vocabulary:     Module build failed (from ./node_modules/css-loader/dist/cjs.js):
@creativecommons/vocabulary:     Error: PostCSS received undefined instead of CSS string
```

How can I resolve this?

**Comment by obulat** [comment]
@kshitij86 , did you try running `npm rebuild node-sass` to download the node-sass binding for your current environment?
There seem to be two problems: one with Node Sass and the other with PostCSS. We have added a PostCSS config to `packages\vocabulary` yesterday, it might be the reason for this message. But do run the `npm rebuild node-sass` first.

**Comment by Manas502** [comment]
Can I take up the issue, if possible?

**Comment by nimishbongale** [comment]
You can @Manas502. 👍 

Just pinging @kshitij86; have you got to resolving this issue yet?

**Comment by kshitij86** [comment]
@nimishbongale Yes I have been working on it. @Manas502 do you want to work on this together?

**Comment by Manas502** [comment]
Sure I'd love to! How do we plan on proceeding?

**Comment by kshitij86** [comment]
@Manas502 Cool, do you wanna collaborate on Discord?

**Comment by nimishbongale** [comment]
@kshitij86

Anything that needs be to discussed can be done here itself. While we don't necessarily say no to discussing and coding the solution out, but we would certainly like to keep everyone in the loop! It would also be easier for anyone (who has a fair idea about the issue) to put in their comments/suggestions.

**Comment by kshitij86** [comment]
@nimishbongale Okay. I just thought this isn't the best place for real time communication. But I get your point.

**Comment by kshitij86** [comment]
@Manas502 Have you got the project running successfully locally? I have been surfing the source code, but the while setting up I still seem to have this error:
 
```
npm ERR! code ERESOLVE
npm ERR! Cannot destructure property `name` of 'undefined' or 'null'.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2021-01-02T05_24_04_109Z-debug.log

lerna ERR! npm install exited 1 in '@creativecommons/fonts'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code 1
npm ERR! path /Desktop/vocabulary
npm ERR! command failed
npm ERR! command sh -c lerna bootstrap

npm ERR! A complete log of this run can be found in:
npm ERR!   /.npm/_logs/2021-01-02T05_24_04_171Z-debug.log
```
@nimishbongale Any advice on how to fix this?

**Comment by nimishbongale** [comment]
> @nimishbongale Any advice on how to fix this?

Can you let me know your node & npm version?  This may be an issue to do with npm v7, but I'm not entirely certain.

**Comment by kshitij86** [comment]
@nimishbongale 
`node - v12.0.0`
`npm - 7.3.0`

**Comment by Manas502** [comment]
@kshitij86 Did it run for you locally?

**Comment by kshitij86** [comment]
@Manas502 No, did it for you?

**Comment by nimishbongale** [comment]
@kshitij86 @Manas502 

Can confirm the setup is broken for the npm+node versions you mention. I tried setting the repo up [on this repl](https://repl.it/@nimishbongale/vocabulary) using node `v12.0.0` and npm `v7.3.0`. It gave the same error that you pointed out earlier.

While I'm pondering over a potential fix, I would recommend stepping down your npm version to `6.x.x`. It's not exactly an _ideal_ solution per se, but you should be able to run the repository just fine after something like this:

```bash
$ sudo npm install -g npm@6.14.5
```

**Comment by kshitij86** [comment]
@nimishbongale Downgrading the `npm` version worked. Will get started on the issue now.

**Comment by Manas502** [comment]
@kshitij86 can you let me know your npm and node versions now? Need to confirm if I'm on the same.

**Comment by kshitij86** [comment]
@Manas502 The `npm` that ships with `node v10.23.0`

**Comment by kshitij86** [comment]
@nimishbongale The header styling needs to be fixed for the `global-header` component right?

**Comment by joshxyzhimself** [comment]
on: `PostCSS received undefined instead of CSS string`

in my experience if you are using webpack, and trying to use `sass-loader`, also add `sass`

```
yarn add sass sass-loader
```

```js
        {
          test: /\.(scss|css)$/,
          use: [
            { loader: 'style-loader' },
            { loader: 'css-loader', options: { importLoaders: 1 } },
            { loader: 'sass-loader' },
            { loader: 'postcss-loader' },
          ],
        },
```

**Comment by Cronus1007** [comment]
@zackkrida Let me take over this issue.

**Comment by zackkrida** [comment]
@Cronus1007 sure

**Comment by kshitij86** [comment]
@zackkrida Looks like the header has changed a bit and I can't find exactly where this occurs. Is this a component issue with `vocabulary`? I successfully built all the storybooks and it wasn't there. Also it doesn't seem to exist on the CC search either.

It'd be great if you could point out where to look for the header sizing issues.
