### ISSUE TITLE
Add a maintained with lerna badge to README.md

### ISSUE THREAD

**Issue by nimishbongale** [cc-archive/vocabulary-legacy#807]
## Description
We use [Lerna](https://lerna.js.org) to maintain our monorepo. Lerna being a wonderful tool that it is, we could probably have a badge saying `maintained with lerna` in our README.md. 

## Additional context
- https://github.com/lerna/lerna#readme-badge

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by RinkiyaKeDad** [comment]
Hey @nimishbongale! Can I work on this? Thanks.
