### ISSUE TITLE
[vocabulary] Content improvements to Overview page

### ISSUE THREAD

**Issue by zackkrida** [cc-archive/vocabulary-legacy#810]
The [Overview Vocabulary page](https://cc-vocabulary.netlify.app/?path=/story/vocabulary-overview--page) has some irrelevant and verbose information. Please remove the https://cc-vocabulary.netlify.app/?path=/story/vocabulary-overview--page#roles-and-responsibilities and https://cc-vocabulary.netlify.app/?path=/story/vocabulary-overview--page#workflows sections. 

Additional improvements are welcome.

CC @nimishbongale

**Comment by nimishbongale** [comment]
On it!

**Comment by nimishbongale** [comment]
@zackkrida 

Should I remove it completely or would a simplified version do? 

Issue #510 seems to point to the fact that it needs to be present?

**Comment by zackkrida** [comment]
I think you could just remove the sections I mentioned, we don't have to delete the entire page.
