### ISSUE TITLE
Add Logos (formerly BrandImagery) to Vocabulary

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#82]
Blocked by: https://github.com/creativecommons/vue-vocabulary/issues/135

**Description**
In Vue Vocabulary, we are going to change the name of the BrandImagery (in Patterns) to be "Logos", and we are going to move it from Patterns to Elements.

Once this is done, we'd like to add the updated section, Logos, to Elements, in Vocabulary.

**Comment by dhruvkb** [comment]
All product logos are SVGs, so they will have no corresponding element in Vocabulary. The assets however will be added by the PR #131.

**Comment by kgodey** [comment]
@dhruvkb we'd like to show the logos in the Storybook for Vocabulary, is that not possible?

**Comment by dhruvkb** [comment]
They're already shown in the Storybook. See for example, [this](https://cc-vocabulary.netlify.com/?path=/story/logos--cc-logomark) and [this](https://cc-vocabulary.netlify.com/?path=/story/logos--cc-vocabulary). This issue can be closed now.

**Comment by kgodey** [comment]
Closing per @dhruvkb's comment.
