### ISSUE TITLE
Bug: Dropdown and Items not visible in storybook

### ISSUE THREAD

**Issue by darkshredder** [cc-archive/vocabulary-legacy#828]
## Description
In Getting started page example and in Header Compact Dropdown and items are invisible and become visible only when hovered

## Expectation
Dropdown and items should be visible like in Header default

## Screenshots
Issue
![Screenshot from 2020-12-12 20-24-06](https://user-images.githubusercontent.com/52625656/101987118-2954bb80-3cb8-11eb-9f8c-14844321c97b.png)
![Screenshot from 2020-12-12 20-24-03](https://user-images.githubusercontent.com/52625656/101987121-2b1e7f00-3cb8-11eb-96da-2d30b58365ad.png)
![Screenshot from 2020-12-12 20-07-50](https://user-images.githubusercontent.com/52625656/101986860-949d8e00-3cb6-11eb-88c4-b216a2aa4301.png)
![Screenshot from 2020-12-12 20-09-22](https://user-images.githubusercontent.com/52625656/101986879-beef4b80-3cb6-11eb-8004-d7bb16dc467e.png)

## Environment
 - Device: (laptop)
 - OS: (ubuntu 20.0.14)
 - Browser: (Firefox, Chrome)

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by Cronus1007** [comment]
@dhruvkb Shall I implement this issue?

**Comment by nimishbongale** [comment]
@Cronus1007 

This issue already has a PR linked to it (#829) so you may want to head over there and give in your inputs,

Thank you!
