### ISSUE TITLE
Update of tomato color

### ISSUE THREAD

**Issue by fcoveram** [cc-archive/vocabulary-legacy#841]
## Problem
The current `$color-tomato` rgb(209, 69, 0) does not meet the AA level when is over a `$color-lighter-gray` background.

## Description
We need to adjust the `$color-tomato` by changing it to hex `#C74200` or rgb(199, 66, 0) to meet the AA level.

⚠️  This change is truly important since it is related to accessibility and affects all CC sites.

**Comment by fcoveram** [comment]
Thanks @obulat for bringing this.

**Comment by Mansibisen** [comment]
@obulat  can I work on this issue ?

**Comment by obulat** [comment]
Sure, go ahead,  @Mansibisen

**Comment by Mansibisen** [comment]
@obulat  I created the PR request , please check it , and guide me if something is wrong
