### ISSUE TITLE
Copy to clipboard button should copy links individually for UNPKG and JSDELIVR block

### ISSUE THREAD

**Issue by abhi14nexu** [cc-archive/vocabulary-legacy#849]
## Problem
Copy button in `UNPKG` and `JSDELIVR` block copies both the latest URL link and v2020.11.1 version link at the same time, so it would be really nice if we can copy each link individually.
## Description
![Screenshot from 2021-02-17 13-08-30](https://user-images.githubusercontent.com/56607134/108172086-63ac6000-7122-11eb-9967-e1ccb5db9ea2.png)

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by nimishbongale** [comment]
@abhi14nexu seems like a fair point, how do you aim to resolve it?

Oh and also, can you update the jsdeliver "specific version" link to something more recent? Say v2020.11.1? 

Thanks!

**Comment by abhi14nexu** [comment]
> Oh and also, can you update the jsdeliver "specific version" link to something more recent? Say v2020.11.1?
> Sure.



sure

**Comment by abhi14nexu** [comment]
> Oh and also, can you update the jsdeliver "specific version" link to something more recent? Say v2020.11.1?

Sure!

**Comment by abhi14nexu** [comment]
> @abhi14nexu seems like a fair point, how do you aim to resolve it?

 @nimishbongale I was thinking of putting the v2020.11.1 link and the latest version link in different blocks.
####  Something like in the picture below:-

![Screenshot from 2021-02-17 22-23-32](https://user-images.githubusercontent.com/56607134/108239401-e0196000-716f-11eb-8b08-1c3b5c1d3911.png)

Please let me know if this approach is correct and any suggestion/improvement is appreciated.
Thanks!

**Comment by nimishbongale** [comment]
It's a good start! 👍 

If you are splitting it into multiple blocks, then could you perhaps do away with the comments in each of them? Also is there a better way to title the blocks (and not repeat JSDELIVR & UNPKG in the heading everywhere)?

**Comment by abhi14nexu** [comment]
@nimishbongale We can put both the version links inside JSDELIVR & UNPKG block, like in the picture shown below.
This will avoid repetition.

![Screenshot from 2021-02-18 14-21-56](https://user-images.githubusercontent.com/56607134/108331821-282e9600-71f5-11eb-9303-66bb261f3a1b.png)

Do let me know if any other improvements are required? :)

**Comment by nimishbongale** [comment]
Thanks for this @abhi14nexu!

This looks good, please raise a relevant PR linking to this issue.

**Comment by abhi14nexu** [comment]
@nimishbongale I have raised the PR as #851 .Do let me know if it requires any changes or improvements.
