### ISSUE TITLE
Bug: Height of docs story in Patterns > Locale > Modal is small and Modal is getting hidden

### ISSUE THREAD

**Issue by darkshredder** [cc-archive/vocabulary-legacy#852]
## Description
Height of docs story in Patterns > Locale > Modal is small and the Modal is getting hidden

## Reproduction
1. Go to the following url [Modal](https://cc-vocabulary.netlify.app/?path=/docs/patterns-modal--modal)
2.You can see modal is not clearly shown in docs page

## Expectation
![Screenshot from 2021-02-21 20-38-09](https://user-images.githubusercontent.com/52625656/108629201-dc921b80-7484-11eb-80a9-8924a059bb5a.png)

## Screenshots
![Screenshot from 2021-02-21 20-38-52](https://user-images.githubusercontent.com/52625656/108629206-e3209300-7484-11eb-805c-8bd69a1bbb50.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by SaravgiYash** [comment]
@darkshredder On Chrome and Edge:
![image](https://user-images.githubusercontent.com/64412143/108629512-3c3cf680-7486-11eb-9e78-f69975a8959a.png)

**Comment by nimishbongale** [comment]
@darkshredder interesting observation! On firefox, it does seem to act funny. Any idea how you'd go about solving this?

**Comment by darkshredder** [comment]
@nimishbongale I tried on chrome its showing as in @Yashs911 image now without any changes and show code is also not working in chrome. With the changes done by me by adding height property to <story> element  now its showing as per expectation image posted by me on both chrome and firefox.
### Chrome after changes
![Screenshot from 2021-02-21 20-58-43](https://user-images.githubusercontent.com/52625656/108629808-aa35ed80-7487-11eb-88cc-1e1bf1f87230.png)
### Firefox after changes
![Screenshot from 2021-02-21 20-38-09](https://user-images.githubusercontent.com/52625656/108629816-b457ec00-7487-11eb-8eb2-413df8c9e69d.png)

**Comment by darkshredder** [comment]
@nimishbongale Can I raise PR for the same issue?

**Comment by nimishbongale** [comment]
> @nimishbongale Can I raise PR for the same issue?

Go ahead @darkshredder! 👍
