### ISSUE TITLE
Bug: Main logos story page is crashing

### ISSUE THREAD

**Issue by darkshredder** [cc-archive/vocabulary-legacy#853]
## Description
Main story page is crashing and not showing anything 

## Reproduction
1. Go to the following url  [Main logo](https://cc-vocabulary.netlify.app/?path=/docs/assets-logos-main--logomark-inverted)
2. See error.

## Expectation
![Screenshot from 2021-02-21 22-17-14](https://user-images.githubusercontent.com/52625656/108631978-9479f580-7492-11eb-86df-3d55d4206281.png)

## Screenshots
![Screenshot from 2021-02-21 22-17-39](https://user-images.githubusercontent.com/52625656/108631987-a196e480-7492-11eb-8987-603c0267c547.png)

## Environment
 - Device: Laptop
 - OS: Ubuntu 20.04.1 LTS
 - Browser: Chrome

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by nimishbongale** [comment]
@darkshredder 

Good observation. Here's the actual detailed error:

![error](https://user-images.githubusercontent.com/43414361/108634992-ae233900-74a2-11eb-9be4-1f036f62e5c0.png)

How do you plan on resolving it?

**Comment by darkshredder** [comment]
I have solved it. This is the change that needs to be made as per storybook documentation and then it will work like charm.
You can see it over here [Link](https://storybook.js.org/docs/vue/essentials/backgrounds)


![Screenshot from 2021-02-22 01-38-23](https://user-images.githubusercontent.com/52625656/108636997-c0a36f80-74ae-11eb-92d3-37f82122dcb7.png)
