### ISSUE TITLE
Changing Preview component to Canvas

### ISSUE THREAD

**Issue by darkshredder** [cc-archive/vocabulary-legacy#856]
## Description
After Storybook release v6.0 [Link](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#previewprops-renamed) .The preview component has been renamed to canvas.In the current codebase there is a lot of use of `<Preview>` component.

## Expectation
Though these changes are backward compatible but we should rename the component for future reference and as per current documentation there is no use of <Preview> component thus future developers may have a problem in implementing it.

## Additional context
I m looking forward for discussion on this issue

## Resolution
- [ ] I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
👍 Thanks for sharing this, it's approved for work.

**Comment by Shukshi** [comment]
Hey I want to work in this issue, Can you please tell me where to start?

**Comment by KarthikSundar2002** [comment]
Is this issue still open?? If it is, I would like to have a look at it.

**Comment by zackkrida** [comment]
@KarthikSundar2002 no, I just merged the existing PR. Thanks!
