### ISSUE TITLE
Cards are not responsive in mobile view.

### ISSUE THREAD

**Issue by frappelatte28** [cc-archive/vocabulary-legacy#860]
## Description
Cards are not responsive in mobile view, as fixed width in the pixels is defined there.

## Reproduction
Sidebar->cards section

## Resolution
![Layouts _ Cards - PostVertical ⋅ Storybook](https://user-images.githubusercontent.com/64382399/109396577-4ebca180-7958-11eb-87c2-f875c0193e6e.gif)

- [x] I would be interested in resolving this bug.

**Comment by frappelatte28** [comment]
Can i raise a PR @zackkrida @dhruvkb @nimishbongale.

**Comment by clasick** [comment]
Fixed by #906.

**Comment by Akpjunior94** [comment]
@brylie I want to work on this. Can I go ahead?

**Comment by brylie** [comment]
Sure thing. Most of the related changes are available in the pull request. They just need to be applied against the files that have been moved to new locations.

**Comment by Akpjunior94** [comment]
Okay. I will take note of that.
