### ISSUE TITLE
Add Definition (Patterns)

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#88]
**Description**
We want to make changes to the Definition (in Patterns).

First, we will make updates to Definition in Vue Vocabulary:
https://github.com/creativecommons/vue-vocabulary/issues/136

These updates are as follows:
1. Remove Colored and Indicating.
2. Rename Branded to be "Default"
3. Rework "Default" to only match the style necessary for the Vocabulary homepage.

Once these update are made, we need to:
1. Add Definition to Vocabulary
2. Add a style, "Default", to match that which is in Vue Vocabulary.

**Comment by dhruvkb** [comment]
This won't be necessary anymore.
