### ISSUE TITLE
Add Header to Vocabulary

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#91]
Blocked by https://github.com/creativecommons/vocabulary/issues/100 where we just need to wrap up language changes to the Header.

We need to add the Header to Vocabulary to match the Figma DL: https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=179%3A0

**Comment by annatuma** [comment]
#100 is now complete, this ticket is no longer blocked by anything.

**Comment by dhruvkb** [comment]
Header is broken after #161 changed color token names. Main issue: #174.
