### ISSUE TITLE
Add Footer to Vocabulary

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#92]
We need to add the Footer to Vocabulary to match the Figma DL: https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=639%3A24

**Comment by Qay-Tekkie** [comment]
@annatuma I am an Outreahy applicant. Please can i work on this issue?

**Comment by chidexebere** [comment]
Hello @Qay-Tekkie , this is already being worked on. Kindly pick another issue
