### ISSUE TITLE
Add License Badges to License Iconography page in Figma DL

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#93]
**Description**
We need to add the License Badges, visible here:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/patterns-licensebadge--licenses

To the License Iconography page in Figma DL. (We will also be moving the License Badges into Vocabulary).

**Comment by fcoveram** [comment]
Done. All badges are now available on the same page in Design Library
