### ISSUE TITLE
RFC: Use GitHub Pages for deployment

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#932]
## Problem

The project currently uses Netlify for static deployment. However, we want to move our static documentation sites over to GitHub Pages.

## Description

Configure the project to deploy to GitHub pages. Leave the default URL settings so that the deployment appears as a sub-URL of the Creative Commons Open Source documentation portal.

## Additional context

The [storybook-deployer](https://github.com/storybookjs/storybook-deployer) package has a `storybook-to-ghpages` command that we can use.

NOTE: we need to determine what features of Netlify we might need when considering this RFC. E.g. do we need branch-specific deployments?

**Comment by brylie** [comment]
@dhruvkb I believe this issue is blocked by the need for a simpler architecture #905. In effect, I believe we would need to have a single Storybook app in order to use the [storybook-deployer](https://github.com/storybookjs/storybook-deployer) utility.

**Comment by dhruvkb** [comment]
@brylie the documentation for Storybook Deployer has a section on [deployment of monorepos](https://github.com/storybookjs/storybook-deployer#deploy-a-monorepo). Can you give that a try to see if it works for our case?
