### ISSUE TITLE
Add Locale into Figma DL

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#94]
**Description**
We need to create a new page, Locale, and add it to the Figma DL.

The current Locale in Vue Vocabulary looks like this:
https://cc-vue-vocabulary.netlify.com/storybook/?path=/story/patterns-locale--standard

A potential alternate/similar style is that on the license pages:
https://creativecommons.org/licenses/by/4.0/

After this has been added to Figma DL, we need to create two new tickets:
In Vue Vocabulary: Update Locale to match Figma DL
In Vocabulary: Add Locale

**Comment by fcoveram** [comment]
The element is in the Design Library
