### ISSUE TITLE
Create Icons page in Vocabulary

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#95]
**Description**
We need to create an Icons page in Vocabulary, based on the Icons page in the Figma DL:
https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A135

**Comment by megha070** [comment]
@dhruvkb I am an outreachy aspirant, I am new to open source and wants help in getting started with the same. Kindly help me out, also I wanted to inquire if I can work on this issue.

**Comment by dhruvkb** [comment]
@megha070 please feel free to take it up. Do look into [Storybook DS docs](https://storybook-design-system.netlify.com/?path=/docs/design-system-icon--labels) and its source code for pointers to get started.

**Comment by Emuohwo** [comment]
I would like to work on this issue if it has not been assigned yet.

**Comment by dhruvkb** [comment]
Sorry @Emuohwo it has been assigned to @megha070. Please feel free to find another issue that hasn't been assigned.

**Comment by Bob160** [comment]
Hello @dhruvkb, can I work on this?

**Comment by dhruvkb** [comment]
@Bob160 we are looking for something identical to creativecommons/fonts#14.

**Comment by kushaggarwal** [comment]
Hello @dhruvkb if this issue is still open I would like to work on it

**Comment by dhruvkb** [comment]
No @kushaggarwal, @Bob160 is working on the issue and it hasn't seen 7 days of inactivity. So you cannot work on it as of now. I've assigned you to 2 other issues.

**Comment by kushaggarwal** [comment]
Okay thank you very much @dhruvkb  
I will start working on others

**Comment by megha070** [comment]
Hey, @Bob160 are you working on this? If you need help I can help you with this or if you are working on any other issue can I take this up?

**Comment by Bob160** [comment]
@megha070 , I'd sincerely appreciate your help. Let's discuss via Slack - @Bob160 .

Thanks

**Comment by megha070** [comment]
Sure @Bob160, Let's take this to slack.
