### ISSUE TITLE
Broken package links on the Readme

### ISSUE THREAD

**Issue by Akpjunior94** [cc-archive/vocabulary-legacy#959]
## Description
We Noticed that links on the package sections of the Readme are broken (this returns a 404 error when clicked on) 

## Expectation
The links are expected to link to the individual package pages.

## Screenshots
![image](https://user-images.githubusercontent.com/56775903/136827895-1ba7deed-eb34-4847-a9e9-5ebe8febecda.png)

**Comment by neeraj-2** [comment]
Would like to fix it. Can I?

**Comment by neeraj-2** [comment]
@brylie as I can see there are a lot of new changes have been made on the repo. There was been a ./packages folder in which we were had all our three packages i.e fonts, vocabulary, and vue-vocabulary. But that folder does not exist anymore.

**Comment by brylie** [comment]
Yes, here is the old file structure for the project:

https://github.com/creativecommons/vocabulary/tree/5e7f4331d62267a4332da2ca484d29b0575e6007

We will need to restore some files from the historic commits.
