### ISSUE TITLE
Run npm run lint npm ERR! missing script: lint

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#961]
Our CI pipeline is failing with the following error:

> Run npm run lint
> npm ERR! missing script: lint

## Task

- [ ] create or restore the `lint` command so lint issues will be detected during development and pull requests

**Comment by brylie** [comment]
From what I can tell, we already have a `lint` command. Perhaps this issue is no longer relevant?

https://github.com/creativecommons/vocabulary/blob/238a272adc1f942a43ca6d9d72f0ddabc08c9df4/package.json#L29

**Comment by MuluhGodson** [comment]
Yes, the project was updated some months ago but the github actions wasn't updated to reflect these changes.

**Comment by brylie** [comment]
@MuluhGodson, good point. I'm creating tasks so we can restore the GitHub actions. Would you like to take any of the recent tasks?

**Comment by MuluhGodson** [comment]
I will love to take this issue and #963 since it involves refactoring the same files (The CI) files.

**Comment by brylie** [comment]
OK, I've assigned you to this issue. Please also comment in #963, so I can assign you there. GitHub won't let me assign you until you've commented on the issue.
