### ISSUE TITLE
Broken code in getting started doc page

### ISSUE THREAD

**Issue by Akpjunior94** [cc-archive/vocabulary-legacy#972]
## Description
Noticed a broken code on the getting started doc page. This should be as a result of the omission of a closing tag.

## Screenshots
![image](https://user-images.githubusercontent.com/56775903/137119178-a96feb5a-a831-4333-b3ec-fdeaa859e697.png)

- [ ] I would be interested in resolving this bug.

**Comment by Akpjunior94** [comment]
@brylie I would love to fix this

**Comment by brylie** [comment]
@Akpjunior94, thanks! I've assigned you to the task.

**Comment by Akpjunior94** [comment]
Okay. Thanks

**Comment by Lovelynchristian** [comment]
Can i fix this too?

**Comment by brylie** [comment]
@Lovelynchristian, sure thing. I'll assign you to this issue.

**Comment by brylie** [comment]
@Akpjunior94 and @Lovelynchristian would you discuss with one another how to collaborate on this task?

**Comment by Lovelynchristian** [comment]
Awesome. We would collaborate and fix it

**Comment by Akpjunior94** [comment]
Hi @Lovelynchristian. I have worked on it but couldn't create the pull request because my device screen had issues yesterday. Can we hook up on slack @Akpan Abraham

**Comment by Akpjunior94** [comment]
@Lovelynchristian Noticed some of those code syntax templates needed space for them to show up well-formatted
for example` <div style="max-width: ${width}px;">` is changed to `<div style=" max-width: ${width}px;">`

**Comment by Lovelynchristian** [comment]
Yes, i noticed that. @Akpjunior94  Can you drop your contact so i could reach out to you?

**Comment by Akpjunior94** [comment]
@Akpan Abraham on the slack channel

**Comment by Akpjunior94** [comment]
@Lovelynchristian what is your slack ID or Name?

**Comment by Lovelynchristian** [comment]
@Akpjunior94  my slack ID is Lovelyn Christian.
