### ISSUE TITLE
npm ERR! enoent ENOENT: no such file or directory, open '/package.json'

### ISSUE THREAD

**Issue by MuluhGodson** [cc-archive/vocabulary-legacy#979]
## Description
CI pipeline failing due to the package.json file not being found. I think related to it being searched for in the wrong path.

## Reproduction

1. Trigger the CI pipeline to run.
2. See error.

## Expectation
CI pipeline runs without the package.json error

## Screenshots
![image](https://user-images.githubusercontent.com/40151808/137174750-0facc8e7-8e41-4b16-b1c9-51fe41b847f4.png)

## Additional context
When working on the CI/CD files, it would be a good idea to test it locally using this package:
`https://github.com/nektos/act`

## Resolution
- [x] I would be interested in resolving this bug.

**Comment by brylie** [comment]
@MuluhGodson, would you like to resolve this task?

**Comment by MuluhGodson** [comment]
Yes, i would be happy to.

**Comment by brylie** [comment]
Thanks! There may be similar issues in our other CI workflows.

**Comment by MuluhGodson** [comment]
okay. I will be sure to check all of them.
