### ISSUE TITLE
Add existing CC product logos to Figma DL

### ISSUE THREAD

**Issue by annatuma** [cc-archive/vocabulary-legacy#98]
**Description**
Let's create a new page in the Figma DL, called "Product logos", and add all of CC's individual product logos into the Figma DL. For high-res versions, if those even exist, it's possible you'll have to sync with Hugo/Breno. Note, this is just an addition of the **existing** logos.

Products:
https://opensource.creativecommons.org/
https://summit.creativecommons.org/
https://certificates.creativecommons.org/
https://cc-vocabulary.netlify.com/
https://network.creativecommons.org/
https://search.creativecommons.org/

Products that do not have a distinct logo presently:
https://stateof.creativecommons.org/

As a side note, we do intend to overhaul these logos in the long run, and the "in the works" improvements should remain in Figma LT: https://www.figma.com/file/V0nHqFuIeWvXjOyyxfzFiT/Library-tests?node-id=41%3A0

**Comment by fcoveram** [comment]
Done. The product logos are in the Design Library
