### ISSUE TITLE
fix path issues for CD pipeline

### ISSUE THREAD

**Issue by MuluhGodson** [cc-archive/vocabulary-legacy#981]
## Description
With regards to issue #979 , the CD pipeline if run will have the same problems with scripts being executed in the wrong path.
With the CD pipeline failing packages and updates won't be published to NPM

## Reproduction

1. Trigger the CD pipeline to run
2. See error.

## Expectation
Packages should publish to NPM

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by MuluhGodson** [comment]
@brylie I will be happy to fix this

**Comment by brylie** [comment]
@MuluhGodson, great! I'll assign you.
