### ISSUE TITLE
Add local CI development tool

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#983]
We use GitHub actions for our continuous integration. When making changes to the CI scripts, it is desirable to test changes locally before committing them to the project repository.
## Task

- [ ] test the chosen library on our CI scripts: `lint`, `test`, and `build`
- [ ] add a section to the development documentation describing how to run tasks locally for CI development

**Comment by MuluhGodson** [comment]
If that's okay, I will be happy to take on this. It sounds interesting to work on.

**Comment by MuluhGodson** [comment]
@brylie I have a quick question. The repository https://github.com/phishy/wflow was last updated in 2019 and has been archived with 10 open Issues and 13PRs.
Should I still go ahead to implement it as a library, given the possibility that bugs may arise which may never be corrected upstream in the archived repo.

**Comment by brylie** [comment]
Ah, good catch. It just seemed like a recommendation from the GitHub Actions documentation. What other tool can we use to run CI workflows locally?

**Comment by MuluhGodson** [comment]
Might I suggest https://github.com/nektos/act which is actively being maintained and I have used it both on `Windows` and `Ubuntu` in the last 2 days.

**Comment by brylie** [comment]
Sounds good.

**Comment by MuluhGodson** [comment]
Okay great.

**Comment by MuluhGodson** [comment]
Also, it would suffice to remove the first task in the description given that the package is not installed as a dependency. It installs as a standalone package on the system (kinda like `node js` or `pip`

**Comment by brylie** [comment]
OK, I updated the title and checklist
