### ISSUE TITLE
Optimize resource usage in our CI scripts

### ISSUE THREAD

**Issue by brylie** [cc-archive/vocabulary-legacy#984]
In discussion https://github.com/creativecommons/vocabulary/discussions/970, we have identified some inefficiencies in our CI scripts, such as duplicate code installing `npm` modules.

## Task

- [ ] reduce the resource usage of our CI workflows, such as by removing redundant steps
- [ ] investigate how we might reduce resource usage _across_ all of, in addition to within, our CI workflows

**Comment by MuluhGodson** [comment]
Okay. Will open a PR shortly.
Running final testing locally.
